src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Auto_Number__c.object
<CustomObject>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Auto Number</label>
    <nameField>
        <label>Lead Auto Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testCopyCallDisposition.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class testCopyCallDisposition {

    static testMethod void myUnitTest(){
    	
    	lead_auto_number__c leadnum = new lead_auto_number__c(round_robin_number__c = 0);
		insert leadnum;
    	
		Account acct = new Account (Name = 'Test Company', Industry = 'Financial Services');
        insert acct;
        
        Task tsk = new Task(Subject = 'Test', ActivityDate=Date.today(), WhatId = acct.id, CallDisposition = 'No Answer');
        insert tsk;
		
		tsk = [select CallDisposition, Call_Disposition__c from Task where id=:tsk.id];
		System.assert( tsk.CallDisposition.equals(tsk.Call_Disposition__c) );
		
		Task tsk2 = new Task(Subject = 'Test2', ActivityDate=Date.today(), WhatId = acct.id, CallDisposition = 'Left Voicemail');
        insert tsk2;
		
		tsk2 = [select CallDisposition, Call_Disposition__c from Task where id=:tsk2.id];
		System.assert( tsk2.CallDisposition.equals(tsk2.Call_Disposition__c) );
	}
}