src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>A_and_B_Graded_Sales_Partners__c</fullName>
        <defaultValue>0</defaultValue>
        <label>A and B Graded Sales Partners</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>A_and_B_Graded_Tech_Partners__c</fullName>
        <defaultValue>0</defaultValue>
        <label>A and B Graded Tech Partners</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Registration_Date__c</fullName>
        <label>First Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Graded_Partners_C_and_Above__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Graded Partners C and Above</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IR12_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IR12 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incremental_Bookings_Last_12_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Incremental Bookings (Last 12 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Registration_Date__c</fullName>
        <label>Last Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NAC_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NAC Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NAS_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NAS Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NAT_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NAT Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NGPC_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NGPC Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NMA_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NMA Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NPO_Score__c</fullName>
        <label>NPO Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_ACE_Certified_Contacts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of ACE Certified Contacts</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Booked_Registrations__c</fullName>
        <label>Number of Booked Registrations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Mapped_Sales_Accounts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Mapped Sales Accounts</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Partner_Offices__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Partner Offices</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Registrations__c</fullName>
        <label>Number of Registrations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Account_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>As of 11/2/2017:

Customer&apos;s Declared Preferred Partner</description>
        <inlineHelpText>Customer&apos;s Declared Preferred Partner</inlineHelpText>
        <label>Customer Preferred Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <filterItems>
                <field>$Source.Type</field>
                <operation>notEqual</operation>
                <value>Enduser</value>
            </filterItems>
            <infoMessage>The Partner Account must be of Account Record Type &quot;Partner&quot;</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Partner Account 1)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_Bookings_Last_12_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Registered Bookings (Last 12 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Registered_Bookings_Last_6_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Registered Bookings (Last 6 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR12_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TR12 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR6_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TR6 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ace_Certification__c</fullName>
        <label>Ace Certification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>Ace Pro</fullName>
                </value>
                <value>
                    <fullName>Ace Champ</fullName>
                </value>
                <value>
                    <fullName>Ace Master: Cloud</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Contact_Department__c</fullName>
        <label>Partner Contact Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Management</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <description>A – Gets VMTurbo, Has Registered and Closed Business
B – Gets VMTurbo, Has Registered but not Closed Business
C – Getting VMTurbo, Has Not Registered or Closed Business yet
D – Not getting the message, has Not Registered or Closed Business
F – Actively selling against us in Accounts</description>
        <inlineHelpText>A - understands VMT message, Has Regs &amp; Closed Business
B - understands VMT message, Has Regs &amp; No Closed Business
C - learning VMT message, No Regs or business
D - doesn&apos;t understand VMT message
F - selling against VMT
NLT - no longer at company</inlineHelpText>
        <label>Partner Contact Grade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>NLT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <description>Deal type for Registrations</description>
        <inlineHelpText>Deal type for Registrations. Select &quot;Direct&quot; if this deal does not have any partner involvement.</inlineHelpText>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Deal_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Approved_Registrations__c</fullName>
        <description># of registrations that have been approved historically for this opportunity. Updated by batch.</description>
        <label>Number of Approved Registrations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID_Date__c</fullName>
        <inlineHelpText>This is the date that the opportunity was moved to Pipeline or above (VMT&apos;s definition of an opportunity being identified - the Identify stage doesn&apos;t count).  This field is updated automatically - DO NOT UPDATE MANUALLY.</inlineHelpText>
        <label>Opportunity ID Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Office</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner Office)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Office__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Reseller, Reseller - Current, Technology Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Offices</relationshipLabel>
        <relationshipName>Partner_Offices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Partner Office</label>
    <nameField>
        <label>Partner Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VartopiaDRS__Registration__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incremental</fullName>
                </value>
                <value>
                    <fullName>Joint/Accelerated</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specific partner office (physical location) that the registration is coming from</description>
        <label>Partner Office</label>
        <referenceTo>Partner_Office__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations (Partner Account)</relationshipLabel>
        <relationshipName>Registrations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Vendor_Status__c</fullName>
        <label>Vendor Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Closed-Won</fullName>
                </value>
                <value>
                    <fullName>Closed-Lost</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>Reg{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Deal_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Incremental</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated</fullName>
    </customValue>
    <customValue>
        <fullName>Fulfillment</fullName>
    </customValue>
    <customValue>
        <fullName>Cisco</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated-Revived</fullName>
        <isActive>false</isActive>
        <label>Joint/Accelerated-Revived</label>
    </customValue>
    <description>Registration Deal Type</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

src/classes/BatchUpdatePartnerInfo.cls
global class BatchUpdatePartnerInfo implements Database.batchable<sObject>{

	public String query;
	
	//query should return all partner accounts where recordtype = partner
	global database.querylocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC,List<sObject> scope) {
		
		VMTUtils.inBatch = true;
		
		Map<id,Account> allAccts = new Map<id,Account>();
		
		// ACCOUNT TO PARTNER OFFICE MAP
		//num of Partner offices per account mapping
		Map<id,Integer> acctPOCount = new Map<id,Integer>();
		
		// ACCOUNT TO APPROVED REG MAPS
		//num of Approved Regs in last 365 days per account mapping
		Map<id,Integer> acctToRegActivePartnerList = new Map<id,Integer>();
		//num of Approved Regs in last 180 days per account mapping
		Map<id,Integer> acctToRegActivePartner6List = new Map<id,Integer>();
		
		Map<id,Double> acctToTotalBookings12 = new Map<id,Double>();
		Map<id,Double> acctToTotalBookings6 = new Map<id,Double>();
		
		Map<id,Double> acctToIncrementalBookings12 = new Map<id,Double>();
		Map<id,Double> acctToIncrementalBookings6 = new Map<id,Double>();
		
		Map<id,Double> acctToTotalPipe12 = new Map<id,Double>();
		Map<id,Double> acctToTotalPipe6 = new Map<id,Double>();
		
		Map<id,Double> acctToIncrementalPipe12 = new Map<id,Double>();
		Map<id,DOuble> acctToIncrementalPipe6 = new Map<id,Double>();
		
		
		//all reg to account mapping
		Map<id,List<VartopiaDRS__Registration__c>> acctToAllRegList = new Map<id,List<VartopiaDRS__Registration__c>>();
		//all booked reg to account mapping
		Map<id,List<VartopiaDRS__Registration__c>> acctToBookedRegList = new Map<id,List<VartopiaDRS__Registration__c>>();
		
		// OPP TO REG MAPS
		//num of Approved Regs to Opportunity mapping
		Map<id,List<VartopiaDRS__Registration__c>> oppToApprovedRegList = new Map<id,List<VartopiaDRS__Registration__c>>();
		
		// ACCOUNT TO CONTACT MAPS
		//all contacts with C or above to account mapping
		Map<id,Integer> acctConCGradeMap = new Map<id,Integer>();
		//all Sales contacts with A or B grading to account mapping
		Map<id,Integer> acctConSalesMap = new Map<id,Integer>();
		//all tech contacts with A or B grading to account mapping
		Map<id,Integer> acctConTechMap = new Map<id,Integer>();
		//all ace certified contacts to account mapping
		Map<id,Integer> acctConACEMap = new Map<id,Integer>();
		
		Map<id,Integer> acctMappedCount = new Map<id,Integer>();
				
		List<Account> accountUpdate = new List<Account>();
		List<Opportunity> oppUpdate = new List<Opportunity>();
		
		for (sObject s: scope) {
			Account a = (Account)s;
			allAccts.put(a.id,a);
			acctPOCount.put(a.id,0);
			acctConCGradeMap.put(a.id,0);
			acctConSalesMap.put(a.id,0);
			acctConTechMap.put(a.id,0);
			acctConACEMap.put(a.id,0);
			acctToTotalBookings12.put(a.id,0);
			acctToTotalBookings6.put(a.id,0);
			acctToIncrementalBookings12.put(a.id,0);
			acctToIncrementalBookings6.put(a.id,0);
			acctToTotalPipe12.put(a.id,0);
			acctToTotalPipe6.put(a.id,0);
			acctToIncrementalPipe12.put(a.id,0);
			acctToIncrementalPipe6.put(a.id,0);
			acctMappedCount.put(a.id,0);
			acctToRegActivePartnerList.put(a.id,0);
			acctToRegActivePartner6List.put(a.id,0);
			List<VartopiaDRS__Registration__c> regList = new List<VartopiaDRS__Registration__c>();
			acctToAllRegList.put(a.id,regList);
		}
		
		
		
		//queries for Partner Offices and registrations
		Map<id,VartopiaDRS__Registration__c> allRegs = new Map<id,VartopiaDRS__Registration__c>([select id, VartopiaDRS__Vendor_Status__c, VartopiaDRS__Opportunity__c, Deal_Type__c, VartopiaDRS__Partner_Account__c, VartopiaDRS__Date_Submitted__c, VartopiaDRS__Approved_Date__c from VartopiaDRS__Registration__c where VartopiaDRS__Partner_Account__c in: allAccts.KeySet()]);
		Map<id,Partner_Office__c> allOffices = new Map<id,Partner_Office__c>([select id, Parent_Partner_Account__c from Partner_Office__c where Parent_Partner_Account__c in: allAccts.KeySet()]);
		Map<id,Contact> allContacts = new Map<id,Contact>([select id, accountId, partner_contact_department__c, partner_Contact__c, ace_certification__c from Contact where accountId in: allAccts.KeySet() and (partner_contact__c = 'C' or Partner_contact__c = 'B' or partner_contact__c = 'A') ]);
		Map<id,Account> allMappedAccts = new Map<id,Account>([select id, name, Partner_Account_1__c from Account where Partner_Account_1__c in: allAccts.KeySet()]);
		
		
		for (Contact c : allContacts.values()) {
			
			// map C graded partners to accounts
			if (acctConCGradeMap.containsKey(c.accountId)) {
				Integer i = acctConCGradeMap.get(c.AccountId);
				i++;
				acctConCGradeMap.put(c.AccountId,i);
			}
			
			// map A & B Sales contacts
			if (acctConSalesMap.containsKey(c.AccountId)) {
				if (c.partner_contact_department__c != null) {
					if (c.partner_contact_department__c == 'Sales' && (c.Partner_Contact__c == 'A' || c.Partner_Contact__c == 'B')) {
						Integer i = acctConSalesMap.get(c.AccountId);
						i++;
						acctConSalesMap.put(c.AccountId,i);
					}
				}
			}
			
			// map A & B Tech contacts
			if (acctConTechMap.containsKey(c.AccountId)) {
				if (c.partner_contact_department__c != null) {
					if (c.partner_contact_department__c == 'Technical' && (c.Partner_Contact__c == 'A' || c.Partner_Contact__c == 'B')) {
						Integer i = acctConTechMap.get(c.AccountId);
						i++;
						acctConTechMap.put(c.AccountId,i);
					}
				}
			}
			
			// map ACE certified contacts
			if (acctConACEMap.containsKey(c.AccountId)) {
				if (c.Ace_certification__c != null) {
					Integer i = acctConACEMap.get(c.AccountId);
					i++;
					acctConACEMap.put(c.AccountId,i);
				}
			}
			
		}
		
		// map all accounts whose Partner Account 1 is in current set of partner accounts
		for (Account a : allMappedAccts.values()) {
			if (acctMappedCount.containsKey(a.partner_account_1__c)) {
				Integer i = acctMappedCount.get(a.partner_account_1__c);
				i++;
				acctMappedCount.put(a.partner_account_1__c,i);
			}
		}
		
		
		Set<id> oppIdSet = new Set<id>();
		for (VartopiaDRS__Registration__c reg : allRegs.values()) {
			if (reg.VartopiaDRS__Opportunity__c != null && reg.VartopiaDRS__Opportunity__c != '006D000000GvUcfIAF') {
				oppIdSet.add(reg.VartopiaDRS__Opportunity__c);
			}
		}
		
		//query for opportunities on Regs
		Map<id,Opportunity> allOpps = new Map<id,Opportunity>([select id, stageName, opportunity_id_date__c, amount, deal_type__c, closeDate, number_of_approved_registrations__c from Opportunity where id in: oppIdSet]);
		
		//throw all partner offices into mapping
		for (Partner_Office__c po : allOffices.values()) {
			if (acctPOCount.containsKey(po.parent_partner_account__c)) {
				Integer i = acctPOCount.get(po.parent_partner_account__c);
				i++;
				acctPOCount.put(po.parent_partner_account__c,i);
			}
		}
		
		for (VartopiaDRS__Registration__c currReg : allRegs.values()) {
			//throw all regs into mapping
			if (acctToAllRegList.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
				List<VartopiaDRS__Registration__c> regList = acctToAllRegList.get(currReg.VartopiaDRS__Partner_Account__c);
				regList.add(currReg);
				acctToAllRegList.put(currReg.VartopiaDRS__Partner_Account__c,regList);
			}
		
			
			if (allOpps.containskey(currReg.VartopiaDRS__Opportunity__c)) {
				Opportunity o = allOpps.get(currReg.VartopiaDRS__Opportunity__c);
				
				if ((o.Deal_Type__c == 'Incremental' || currReg.Deal_Type__c == 'Incremental') && currReg.VartopiaDRS__Approved_Date__c != null) {
					if (o.opportunity_id_date__c != null) {
						if (o.opportunity_id_date__c.daysBetween(date.today()) <= 365) {
							if (acctToIncrementalPipe12.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToIncrementalPipe12.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToIncrementalPipe12.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
						if (o.opportunity_id_date__c.daysBetween(date.today()) <= 182) {
							if (acctToIncrementalPipe6.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToIncrementalPipe6.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToIncrementalPipe6.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
					}
					
					
					if (o.stageName == 'Closed Won') {
						if (o.closeDate.daysBetween(date.today()) <= 365 ) {
							if (acctToIncrementalBookings12.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToIncrementalBookings12.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToIncrementalBookings12.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
						if (o.closeDate.daysBetween(date.today()) <= 182) {
							if (acctToIncrementalBookings6.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToIncrementalBookings6.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToIncrementalBookings6.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
					}
				}
				
				
				
				
				if (currReg.VartopiaDRS__Approved_Date__c != null) {
					
					if (o.opportunity_id_date__c != null) {
						if (o.opportunity_id_date__c.daysBetween(date.today()) <= 365) {
							if (acctToTotalPipe12.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToTotalPipe12.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToTotalPipe12.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
						if (o.opportunity_id_date__c.daysBetween(date.today()) <= 182) {
							if (acctToTotalPipe6.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToTotalPipe6.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToTotalPipe6.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
					}
					
					if (o.stageName == 'Closed Won') {
						if (o.closeDate.daysBetween(date.today()) <= 365 ) {
							if (acctToTotalBookings12.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToTotalBookings12.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToTotalBookings12.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
						if (o.closeDate.daysBetween(date.today()) <= 182) {
							if (acctToTotalBookings6.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
								Double currAmt = acctToTotalBookings6.get(currReg.VartopiaDRS__Partner_Account__c);
								currAmt += o.amount;
								acctToTotalBookings6.put(currReg.VartopiaDRS__Partner_Account__c,currAmt);
							}
						}
					}
					
					
					//throw approved regs into opp mapping
					if (oppToApprovedRegList.containsKey(o.id)) {
						List<VartopiaDRS__Registration__c> regList = oppToApprovedRegList.get(o.id);
						regList.add(currReg);
						oppToApprovedRegList.put(o.id,regList);
					} else {
						List<VartopiaDRS__Registration__c> regList = new List<VartopiaDRS__Registration__c>();
						regList.add(currReg);
						oppToApprovedRegList.put(o.id,regList);
					}
					
				}
				
				//throw regs with closed won opps into acct mapping
				if (o.stageName == 'Closed Won') {
					if (acctToBookedRegList.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
						List<VartopiaDRS__Registration__c> regList = acctToBookedRegList.get(currReg.VartopiaDRS__Partner_Account__c);
						regList.add(currReg);
						acctToBookedRegList.put(currReg.VartopiaDRS__Partner_Account__c,regList);
					} else {
						List<VartopiaDRS__Registration__c> regList = new List<VartopiaDRS__Registration__c>();
						regList.add(currReg);
						acctToBookedRegList.put(currReg.VartopiaDRS__Partner_Account__c,regList);
					}
				}
			}
			
			//throw regs that are approved within last 180/365 days into mapping
			if (currReg.VartopiaDRS__Approved_Date__c != null) {
				//365 day mapping
				if ( currReg.VartopiaDRS__Approved_Date__c.daysBetween(date.today()) <= 365) {
					if (acctToRegActivePartnerList.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
						Integer i = acctToRegActivePartnerList.get(currReg.VartopiaDRS__Partner_Account__c);
						i++;
						acctToRegActivePartnerList.put(currReg.VartopiaDRS__Partner_Account__c,i);
					}
				}
				//180 day mapping
				if ( currReg.VartopiaDRS__Approved_Date__c.daysBetween(date.today()) <= 182) {
					if (acctToRegActivePartner6List.containsKey(currReg.VartopiaDRS__Partner_Account__c)) {
						Integer i = acctToRegActivePartner6List.get(currReg.VartopiaDRS__Partner_Account__c);
						i++;
						acctToRegActivePartner6List.put(currReg.VartopiaDRS__Partner_Account__c,i);
					}
				}	
			}
		}
		
		
		Boolean updated = false;
		for (Opportunity o : allOpps.values()) {
			updated = false;
			
			if (oppToApprovedRegList.containsKey(o.id)) {
				List<VartopiaDRS__Registration__c> regList = oppToApprovedRegList.get(o.id);
				if (o.Number_of_Approved_Registrations__c != regList.size()) {
					o.Number_of_Approved_Registrations__c =  regList.size();
					updated = true;
				}
			} else {
				if (o.Number_of_Approved_Registrations__c != 0) {
					o.Number_of_Approved_Registrations__c = 0;
					updated = true;
				}
			}
			
			if(updated) oppUpdate.add(o);
		}
		
		for (Account a : allAccts.values()) {
			updated = false;
			
			//set number of C+ graded partner contacts
			if (acctConCGradeMap.containsKey(a.id)) {
				if (a.Graded_Partners_C_and_Above__c == null || (a.Graded_Partners_C_and_Above__c == 0 && a.NGPC_Score__c == null) ||a.Graded_Partners_C_and_Above__c != acctConCGradeMap.get(a.id)) {
					a.Graded_Partners_C_and_Above__c = acctConCGradeMap.get(a.id);
					if (a.Graded_Partners_C_and_Above__c >= 50) {
						a.NGPC_Score__c = 5;
					} else if (a.Graded_Partners_C_and_Above__c >= 40) {
						a.NGPC_Score__c = 4;
					} else if (a.Graded_Partners_C_and_Above__c >= 30) {
						a.NGPC_Score__c = 3;
					} else if (a.Graded_Partners_C_and_Above__c >= 20) {
						a.NGPC_Score__c = 2;
					} else if (a.Graded_Partners_C_and_Above__c >= 10) {
						a.NGPC_Score__c = 1;
					} else {
						a.NGPC_Score__c = 0;
					}
					updated = true;
				}
			}
			
			//set number of A & B sales contacts
			if (acctConSalesMap.containsKey(a.id)) {
				if (a.A_and_B_Graded_Sales_Partners__c == null || (a.A_and_B_Graded_Sales_Partners__c == 0 && a.NAS_Score__c == null) ||a.A_and_B_Graded_Sales_Partners__c != acctConSalesMap.get(a.id)) {
					a.A_and_B_Graded_Sales_Partners__c = acctConSalesMap.get(a.id);
					if (a.A_and_B_Graded_Sales_Partners__c >= 25) {
						a.NAS_Score__c = 5;
					} else if (a.A_and_B_Graded_Sales_Partners__c >= 20) {
						a.NAS_Score__c = 4;
					} else if (a.A_and_B_Graded_Sales_Partners__c >= 15) {
						a.NAS_Score__c = 3;
					} else if (a.A_and_B_Graded_Sales_Partners__c >= 10) {
						a.NAS_Score__c = 2;
					} else if (a.A_and_B_Graded_Sales_Partners__c >= 5) {
						a.NAS_Score__c = 1;
					} else {
						a.NAS_Score__c = 0;
					}
					updated = true;
				}
			}
			
			//set number of A & B tech contacts
			if (acctConTechMap.containsKey(a.id)) {
				if (a.A_and_B_Graded_Tech_Partners__c == null || (a.A_and_B_Graded_Tech_Partners__c == 0 && a.NAT_Score__c == null) ||a.A_and_B_Graded_Tech_Partners__c != acctConTechMap.get(a.id)) {
					a.A_and_B_Graded_Tech_Partners__c = acctConTechMap.get(a.id);
					if (a.A_and_B_Graded_Tech_Partners__c >= 15) {
						a.NAT_Score__c = 5;
					} else if (a.A_and_B_Graded_Tech_Partners__c >= 12) {
						a.NAT_Score__c = 4;
					} else if (a.A_and_B_Graded_Tech_Partners__c >= 9) {
						a.NAT_Score__c = 3;
					} else if (a.A_and_B_Graded_Tech_Partners__c >= 6) {
						a.NAT_Score__c = 2;
					} else if (a.A_and_B_Graded_Tech_Partners__c >= 3) {
						a.NAT_Score__c = 1;
					} else {
						a.NAT_Score__c = 0;
					}
					updated = true;
				}
			}
			
			//set number of ace certified contacts
			if (acctConACEMap.containsKey(a.id)) {
				if (a.Number_of_ACE_Certified_Contacts__c == null || (a.Number_of_ACE_Certified_Contacts__c == 0 && a.NAC_Score__c == null) ||a.Number_of_ACE_Certified_Contacts__c != acctConACEMap.get(a.id)) {
					a.Number_of_ACE_Certified_Contacts__c = acctConACEMap.get(a.id);
					if (a.Number_of_ACE_Certified_Contacts__c >= 10) {
						a.NAC_Score__c = 5;
					} else if (a.Number_of_ACE_Certified_Contacts__c >= 8) {
						a.NAC_Score__c = 4;
					} else if (a.Number_of_ACE_Certified_Contacts__c >= 6) {
						a.NAC_Score__c = 3;
					} else if (a.Number_of_ACE_Certified_Contacts__c >= 4) {
						a.NAC_Score__c = 2;
					} else if (a.Number_of_ACE_Certified_Contacts__c >= 2) {
						a.NAC_Score__c = 1;
					} else {
						a.NAC_Score__c = 0;
					}
					updated = true;
				}
			}
			
			//set number of partner offices - don't need an else
			if (acctPOCount.containsKey(a.id)) {
				a.Number_Of_Partner_Offices__c = acctPOCount.get(a.id);
				system.debug('### acct ' + a.name);
				if (a.Number_Of_Partner_Offices__c >= 10) {
					a.NPO_Score__c = 5;
				} else if (a.Number_Of_Partner_Offices__c >= 8) {
					a.NPO_Score__c = 4;
				} else if (a.Number_Of_Partner_Offices__c >= 6) {
					a.NPO_Score__c = 3;
				} else if (a.Number_Of_Partner_Offices__c >= 4) {
					a.NPO_Score__c = 2;
				} else if (a.Number_Of_Partner_Offices__c >= 2) {
					a.NPO_Score__c = 1;
				} else {
					a.NPO_Score__c = 0;
				}
				updated = true;
			}
			
			//set number of mapped accounts to partner account 1
			if (acctMappedCount.containsKey(a.id)) {
				if (a.number_of_mapped_sales_accounts__c == null || (a.number_of_mapped_sales_accounts__c == 0 && a.NMA_Score__c == null) || a.number_of_mapped_sales_accounts__c != acctMappedCount.get(a.id)) {
					a.number_of_mapped_sales_accounts__c = acctMappedCount.get(a.id);
					if (a.number_of_mapped_sales_accounts__c >= 50) {
						a.NMA_Score__c = 5;
					} else if (a.number_of_mapped_sales_accounts__c >= 40) {
						a.NMA_Score__c = 4;
					} else if (a.number_of_mapped_sales_accounts__c >= 30) {
						a.NMA_Score__c = 3;
					} else if (a.number_of_mapped_sales_accounts__c >= 20) {
						a.NMA_Score__c = 2;
					} else if (a.number_of_mapped_sales_accounts__c >= 10) {
						a.NMA_Score__c = 1;
					} else {
						a.NMA_Score__c = 0;
					}
					updated = true;
				}
			}
			
			//set number of booked regs tied to this partner - need an else
			if (acctToBookedRegList.containsKey(a.id)) {
				List<VartopiaDRS__Registration__c> regList = acctToBookedRegList.get(a.id);
				if(a.number_of_booked_registrations__c != null && a.number_of_booked_registrations__c != regList.size()) {
					a.number_of_booked_registrations__c = regList.size();
					updated = true;
				} else {
					a.number_of_booked_registrations__c = regList.size();
					updated = true;
				}
			} else {
				if (a.Number_of_booked_registrations__c != 0) {
					a.number_of_booked_registrations__c = 0;
					updated = true;
				}
			}
			
			//determine first/last registration date based on submit date
			if (acctToAllRegList.containsKey(a.id)) {
				List<VartopiaDRS__Registration__c> regList = acctToAllRegList.get(a.id);
				system.debug('### ' + regList.size());
				
				if (!regList.isEmpty()) {
					
					List<RegistrationWrapper> regWrapList = new List<RegistrationWrapper>();
					for (VartopiaDRS__Registration__c reg : regList) {
						regWrapList.add(new RegistrationWrapper(reg));
					}
					regWrapList.sort();
					
					if (a.first_registration_date__c != regWrapList.get(0).thisReg.VartopiaDRS__Date_Submitted__c) {
						a.first_registration_date__c = regWrapList.get(0).thisReg.VartopiaDRS__Date_Submitted__c;
						updated = true;	
					}
					if (a.last_registration_date__c != regWrapList.get(regWrapList.size()-1).thisReg.VartopiaDRS__Date_Submitted__c) {
						a.last_registration_date__c = regWrapList.get(regList.size()-1).thisReg.VartopiaDRS__Date_Submitted__c;
						updated = true;
					}
					if (a.number_of_registrations__c != regList.size()) {
						a.number_of_registrations__c = regList.size();
						updated = true;
					}
				} else {
					if (a.first_registration_date__c != null || a.last_registration_date__c != null || a.number_of_registrations__c != 0 || a.number_of_registrations__c != null) {
						a.first_registration_date__c = null;
						a.last_registration_date__c = null;
						a.number_of_registrations__c = 0;
						updated = true;
					}
				}
			}
			
			if (acctToTotalBookings12.containsKey(a.id)) {
				if (a.registered_bookings_last_12_months__c == null || (a.registered_bookings_last_12_months__c == 0 && a.TR12_Score__c == null) ||a.registered_bookings_last_12_months__c != acctToTotalBookings12.get(a.id)) {
					a.registered_bookings_last_12_months__c = acctToTotalBookings12.get(a.id);
					if (a.registered_bookings_last_12_months__c >= 500000) {
						a.TR12_Score__c = 5;
					} else if (a.registered_bookings_last_12_months__c >= 400000) {
						a.TR12_Score__c = 4;
					} else if (a.registered_bookings_last_12_months__c >= 300000) {
						a.TR12_Score__c = 3;
					} else if (a.registered_bookings_last_12_months__c >= 200000) {
						a.TR12_Score__c = 2;
					} else if (a.registered_bookings_last_12_months__c >= 100000) {
						a.TR12_Score__c = 1;
					} else {
						a.TR12_Score__c = 0;
					}
					updated = true;
				}
			}
			
			if (acctToTotalBookings6.containsKey(a.id)) {
				if (a.registered_bookings_last_6_months__c == null || (a.registered_bookings_last_6_months__c == 0 && a.TR6_Score__c == null) || a.registered_bookings_last_6_months__c != acctToTotalBookings6.get(a.id)) {
					a.registered_bookings_last_6_months__c = acctToTotalBookings6.get(a.id);
					if (a.registered_bookings_last_6_months__c >= 250000) {
						a.TR6_Score__c = 5;
					} else if (a.registered_bookings_last_6_months__c >= 200000) {
						a.TR6_Score__c = 4;
					} else if (a.registered_bookings_last_6_months__c >= 150000) {
						a.TR6_Score__c = 3;
					} else if (a.registered_bookings_last_6_months__c >= 100000) {
						a.TR6_Score__c = 2;
					} else if (a.registered_bookings_last_6_months__c >= 50000) {
						a.TR6_Score__c = 1;
					} else {
						a.TR6_Score__c = 0;
					}
					updated = true;
				}
			}
			
			if (acctToIncrementalBookings12.containsKey(a.id)) {
				if (a.incremental_bookings_last_12_months__c == null || (a.incremental_bookings_last_12_months__c == 0 && a.IR12_Score__c == null) || a.incremental_bookings_last_12_months__c != acctToIncrementalBookings12.get(a.id)) {
					a.incremental_bookings_last_12_months__c = acctToIncrementalBookings12.get(a.id);
					if (a.incremental_bookings_last_12_months__c >= 250000) {
						a.IR12_Score__c = 5;
					} else if (a.incremental_bookings_last_12_months__c >= 200000) {
						a.IR12_Score__c = 4;
					} else if (a.incremental_bookings_last_12_months__c >= 150000) {
						a.IR12_Score__c = 3;
					} else if (a.incremental_bookings_last_12_months__c >= 100000) {
						a.IR12_Score__c = 2;
					} else if (a.incremental_bookings_last_12_months__c >= 50000) {
						a.IR12_Score__c = 1;
					} else {
						a.IR12_Score__c = 0;
					}
					updated = true;
				}
			}
			
			if (acctToIncrementalBookings6.containsKey(a.id)) {
				if (a.incremental_bookings_last_6_months__c == null || (a.incremental_bookings_last_6_months__c == 0 && a.IR6_Score__c == null) || a.incremental_bookings_last_6_months__c != acctToIncrementalBookings6.get(a.id)) {
					a.incremental_bookings_last_6_months__c = acctToIncrementalBookings6.get(a.id);
					if (a.incremental_bookings_last_6_months__c >= 125000) {
						a.IR6_Score__c = 5;
					} else if (a.incremental_bookings_last_6_months__c >= 100000) {
						a.IR6_Score__c = 4;
					} else if (a.incremental_bookings_last_6_months__c >= 75000) {
						a.IR6_Score__c = 3;
					} else if (a.incremental_bookings_last_6_months__c >= 50000) {
						a.IR6_Score__c = 2;
					} else if (a.incremental_bookings_last_6_months__c >= 25000) {
						a.IR6_Score__c = 1;
					} else {
						a.IR6_Score__c = 0;
					}
					updated = true;
				}
			}
			
			if (acctToIncrementalPipe12.containsKey(a.id)) {
				if (a.incremental_pipe_adds_last_12_months__c == null || (a.incremental_pipe_adds_last_12_months__c == 0 && a.IP12_Score__c == null) ||a.incremental_pipe_adds_last_12_months__c != acctToIncrementalPipe12.get(a.id)) {
					a.incremental_pipe_adds_last_12_months__c = acctToIncrementalPipe12.get(a.id);
					if (a.incremental_pipe_adds_last_12_months__c >= 1000000) {
						a.IP12_Score__c = 5;
					} else if (a.incremental_pipe_adds_last_12_months__c >= 800000) {
						a.IP12_Score__c = 4;
					} else if (a.incremental_pipe_adds_last_12_months__c >= 600000) {
						a.IP12_Score__c = 3;
					} else if (a.incremental_pipe_adds_last_12_months__c >= 400000) {
						a.IP12_Score__c = 2;
					} else if (a.incremental_pipe_adds_last_12_months__c >= 200000) {
						a.IP12_Score__c = 1;
					} else {
						a.IP12_Score__c = 0;
					}
					updated = true;
				} 
			}
			
			if (acctToIncrementalPipe6.containsKey(a.id)) {
				if (a.incremental_pipe_adds_last_6_months__c == null || (a.incremental_pipe_adds_last_6_months__c == 0 && a.IP6_Score__c == null) || a.incremental_pipe_adds_last_6_months__c != acctToIncrementalPipe6.get(a.id)) {
					a.incremental_pipe_adds_last_6_months__c = acctToIncrementalPipe6.get(a.id);
					if (a.incremental_pipe_adds_last_6_months__c >= 500000) {
						a.IP6_Score__c = 5;
					} else if (a.incremental_pipe_adds_last_6_months__c >= 400000) {
						a.IP6_Score__c = 4;
					} else if (a.incremental_pipe_adds_last_6_months__c >= 300000) {
						a.IP6_Score__c = 3;
					} else if (a.incremental_pipe_adds_last_6_months__c >= 200000) {
						a.IP6_Score__c = 2;
					} else if (a.incremental_pipe_adds_last_6_months__c >= 100000) {
						a.IP6_Score__c = 1;
					} else {
						a.IP6_Score__c = 0;
					}
					updated = true;
				}
			}
			
			if (acctToTotalPipe12.containsKey(a.id)) {
				if (a.registered_pipe_adds_last_12_months__c == null || (a.registered_pipe_adds_last_12_months__c == 0 && a.TP12_Score__c == null) || a.registered_pipe_adds_last_12_months__c != acctToTotalPipe12.get(a.id)) {
					a.registered_pipe_adds_last_12_months__c = acctToTotalPipe12.get(a.id);
					if (a.registered_pipe_adds_last_12_months__c >= 2000000) {
						a.TP12_Score__c = 5;
					} else if (a.registered_pipe_adds_last_12_months__c >= 1600000) {
						a.TP12_Score__c = 4;
					} else if (a.registered_pipe_adds_last_12_months__c >= 1200000) {
						a.TP12_Score__c = 3;
					} else if (a.registered_pipe_adds_last_12_months__c >= 800000) {
						a.TP12_Score__c = 2;
					} else if (a.registered_pipe_adds_last_12_months__c >= 400000) {
						a.TP12_Score__c = 1;
					} else {
						a.TP12_Score__c = 0;
					}
					updated = true;
				}
			}
			
			if (acctToTotalPipe6.containsKey(a.id)) {
				if (a.registered_pipe_adds_last_6_months__c == null || (a.registered_pipe_adds_last_6_months__c == 0 && a.TP6_Score__c == null) ||a.registered_pipe_adds_last_6_months__c != acctToTotalPipe6.get(a.id)) {
					a.registered_pipe_adds_last_6_months__c = acctToTotalPipe6.get(a.id);
					if (a.registered_pipe_adds_last_6_months__c >= 1000000) {
						a.TP6_Score__c = 5;
					} else if (a.registered_pipe_adds_last_6_months__c >= 800000) {
						a.TP6_Score__c = 4;
					} else if (a.registered_pipe_adds_last_6_months__c >= 600000) {
						a.TP6_Score__c = 3;
					} else if (a.registered_pipe_adds_last_6_months__c >= 400000) {
						a.TP6_Score__c = 2;
					} else if (a.registered_pipe_adds_last_6_months__c >= 200000) {
						a.TP6_Score__c = 1;
					} else {
						a.TP6_Score__c = 0;
					}
					updated = true;
				}
			}			
			
			
			
			if (acctToRegActivePartnerList.containsKey(a.id)) {
				//set whether this partner should be labeled an active partner
				if (acctToRegActivePartnerList.get(a.id) > 0 && a.Active_Partner__c == false) {
					a.Active_Partner__c = true;
					updated = true;
				} else if (a.Active_Partner__c == true && acctToRegActivePartnerList.get(a.id) == 0) {
					a.Active_Partner__c = false;
					updated = true;
				}
				
				//set number of approved regs in last 12 months
				if (a.approved_registrations_last_12_months__c == null || (a.approved_registrations_last_12_months__c == 0 && a.AR12_Score__c == null) ||a.approved_registrations_last_12_months__c != acctToRegActivePartnerList.get(a.id)) {
					a.approved_registrations_last_12_months__c = acctToRegActivePartnerList.get(a.id);
					if (a.approved_registrations_last_12_months__c >= 50) {
						a.AR12_Score__c = 5;
					} else if (a.approved_registrations_last_12_months__c >= 40) {
						a.AR12_Score__c = 4;
					} else if (a.approved_registrations_last_12_months__c >= 30) {
						a.AR12_Score__c = 3;
					} else if (a.approved_registrations_last_12_months__c >= 20) {
						a.AR12_Score__c = 2;
					} else if (a.approved_registrations_last_12_months__c >= 10) {
						a.AR12_Score__c = 1;
					} else {
						a.AR12_Score__c = 0;
					}
					updated = true;
				}
			}
			
			if (acctToRegActivePartner6List.containsKey(a.id)) {
				//set number of approved regs in last 6 months
				if (a.approved_registrations_last_6_months__c == null || (a.approved_registrations_last_6_months__c == 0 && a.AR6_Score__c == null) || a.approved_registrations_last_6_months__c != acctToRegActivePartner6List.get(a.id)) {
					a.approved_registrations_last_6_months__c = acctToRegActivePartner6List.get(a.id);
					if (a.approved_registrations_last_6_months__c >= 25) {
						a.AR6_Score__c = 5;
					} else if (a.approved_registrations_last_6_months__c >= 20) {
						a.AR6_Score__c = 4;
					} else if (a.approved_registrations_last_6_months__c >= 15) {
						a.AR6_Score__c = 3;
					} else if (a.approved_registrations_last_6_months__c >= 10) {
						a.AR6_Score__c = 2;
					} else if (a.approved_registrations_last_6_months__c >= 5) {
						a.AR6_Score__c = 1;
					} else {
						a.AR6_Score__c = 0;
					}
					updated = true;
				} 
			}
			
			if (updated) accountUpdate.add(a);
		}
		
		
		if (!oppUpdate.isEmpty()) update oppUpdate;
		if (!accountUpdate.isEmpty()) update accountUpdate;
		
		VMTUtils.inBatch = false;
		
	}
	
	global void finish(Database.BatchableContext BC){
		
		AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed, ExtendedStatus, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
		if (a.NumberOfErrors > 0 && !(a.ExtendedStatus.contains('UNABLE_TO_LOCK_ROW'))) {
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = new String[] {a.CreatedBy.Email, 'justin.chang@vmturbo.com', 'nadine.tardiff@turbonomic.com', 'charmian.mcintyre@turbonomic.com', 'SFAdmin@turbonomic.com'};
			mail.setToAddresses(toAddresses);
			mail.setSubject('Batch Update Partner Account Info: ' + a.Status);
			mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.\n' + a.ExtendedStatus);
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		}
		
		
	}


}