src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Latitude_Longitude__c</fullName>
        <label>Latitude/Longitude</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Coordinates__c.object
<CustomObject>
    <description>latitude/longitude lookup by zip code</description>
    <fields>
        <fullName>Latitude_Longitude__c</fullName>
        <label>Latitude/Longitude</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Coordinates</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Account Coordinates Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Coordinates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Auto_Number__c.object
<CustomObject>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Auto Number</label>
    <nameField>
        <label>Lead Auto Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testAcctLookupLatLong.cls
/* Created by: Eustace Consulting [www.eustaceconsulting.com][Developer: Jennifer Blair]  
 * Description: test class for AcctLookupLatLongByZip.trigger
 */
@isTest
private class testAcctLookupLatLong {

    static testMethod void myUnitTest() {
    	
      lead_auto_number__c leadnum = new lead_auto_number__c(round_robin_number__c = 0);
	  insert leadnum;
	  
      //create Account Coordinate Entry
      Account_Coordinates__c ac = new Account_Coordinates__c(Zip_Code__c = '12345', Latitude_Longitude__c = '18.14;-66.26');
      insert ac;
      
      //create Account
      Account acct = new Account(Name = 'MyAccount', BillingPostalCode = '12345');
      insert acct;

      //verify Lat/Long info populated
      acct = [select Latitude_Longitude__c from Account where id =: acct.id];
      system.assertEquals(acct.Latitude_Longitude__c, '18.14;-66.26');
    }
}