src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AE_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Focus_Account_Date_Stamp__c</fullName>
        <label>Focus Account Date (Stamp)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Focus_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Focus Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_in_Focus_Accounts__c</fullName>
        <formula>IF(AND(	
OR(
	In_DiscoverOrg__c=&quot;Yes&quot;,
	NOT(ISBLANK(RainKing_ID__c)),
	AND(NOT(ISNULL(VM_Count__c)),VM_Count__c&gt;100),
	AND(NOT(ISNULL(Socket_Count__c)),Socket_Count__c&gt;20)
),RecordType.Name&lt;&gt;&quot;Partner&quot;),
true,false)</formula>
        <label>Include in Focus Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Socket_Count__c</fullName>
        <label>Socket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>RIGHT(Status_Ordered__c,LEN(Status_Ordered__c)-4)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VMT_Account_Score__c</fullName>
        <description>Target accounts get min of 500
Make given industry 1000 to run a campaign (max 1500 to not mess up other rankings - Prospects get 2000 and ~400 or so can come from company size, last call, title, and other), or use &quot;Include in Marketo&quot; field on lead record to toggle campaign (adds extra points to score)</description>
        <formula>IF(Socket_Count__c+VM_Count__c&gt;0,MAX(Socket_Count__c,VM_Count__c/15),
CASE(Industry_clean_text__c, 
&quot;Biotech &amp; Pharma&quot;,0.3,
&quot;Construction &amp; Engineering&quot;,0.25,
&quot;Education&quot;,0.25,
&quot;Energy &amp; Utilities&quot;,0.3,
&quot;Financial Services&quot;,0.55,
&quot;Food &amp; Beverage&quot;,0.2,
&quot;Government&quot;,0.05,
&quot;Healthcare&quot;,0.4,
&quot;Insurance&quot;,0.45,
&quot;Manufacturing &amp; Industrials&quot;,0.1,
&quot;Nonprofit&quot;,0.05,
&quot;Professional Services: Legal&quot;,0.4,
&quot;Professional Services: Other&quot;,0.4,
&quot;Retail &amp; Consumer Products&quot;,0.2,
&quot;Service Providers&quot;,1,
&quot;Tech: Internet&quot;,1,
&quot;Tech: All Other&quot;,0.6,
&quot;Tech: Software&quot;,1,
&quot;Telecom &amp; Media&quot;,0.5,
&quot;Transportation &amp; Logistics&quot;,0.1,
&quot;Travel &amp; Leisure&quot;,0.1,
&quot;Wholesale&quot;,0.1,
&quot;Other&quot;,0.1,
0.2)*NumberOfEmployees)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VMT Account Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Auto_Number__c.object
<CustomObject>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Auto Number</label>
    <nameField>
        <label>Lead Auto Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Focus_Account__c</fullName>
        <formula>Account.Focus_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Focus Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName&amp;&quot; &quot;&amp;LastName</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>For lead score (for US reps, foreign leads show up at the top of the lead view in the morning)</description>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/VMT_Account_Score__c.object
<CustomObject>
    <label>VMT Opportunity Account Score</label>
    <nameField>
        <label>VMT Account Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VMT Opportunity Account Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatchAssignFocusAccounts.cls
@isTest
private class TestBatchAssignFocusAccounts {

    static testMethod void myUnitTest() {
/*    	
    	lead_auto_number__c leadnum = new lead_auto_number__c(round_robin_number__c = 0);
		insert leadnum;
        
    	User user1 = [select id, name, location__c from User where full_name__c =: 'Jay Pyburn'];
        
        Integer socketCount = 1000;
        
//        Account acct1 = new Account(Name = 'Acct1', AE_Rep__c = user1.id, socket_count__c = 100000, status_change_date__c = null);
//        insert acct1;
//        Account acct2 = new Account(Name = 'Acct2', AE_Rep__c = user1.id, socket_count__c = 100000, Focus_Account__c = true, Focus_Account_Date_Stamp__c = Date.today(), status_change_date__c = null);
//        insert acct2;
        List<Account> acctList = new List<Account>();
        
        Account nonFocusAcct;
        
		for(Integer i=0; i<30; i++) {

			if (i < 10) {
				Account tempAcct = new Account(name = 'Acct' + i, AE_Rep__c = user1.id, socket_count__c = socketCount, status_change_date__c = null, focus_account__c = true, focus_account_date_stamp__c = date.today().addDays(-5));
				socketCount += 100;
				acctList.add(tempAcct);			
				nonFocusAcct = tempAcct;	
			} else {
				Account tempAcct = new Account(name = 'Acct' + i, AE_Rep__c = user1.id, socket_count__c = socketCount, status_change_date__c = null);
				socketCount += 100;
				acctList.add(tempAcct);			
			}
		}
		system.debug('$$$ acctList has ' + acctList.size() + ' accounts' );
		insert acctList;
		        
        Test.StartTest();
        BatchAssignFocusAccounts n = new BatchAssignFocusAccounts();
      	n.query = 'SELECT id, name, location__c FROM User WHERE id = \'' + user1.id + '\'';
      	ID batchprocessid = Database.executeBatch(n);
      	Test.StopTest();
        
        
		// test code for assigning focus accounts
//		Account getAcct1 = [select id, name, focus_account__c, focus_account_date_stamp__c, status_change_date__c, Include_in_Focus_Accounts__c from Account where id =: acct1.id limit 1];
//      system.debug(getAcct1.status_change_date__c);
//      system.assertEquals(getAcct1.focus_account__c,true);
//      system.assertEquals(getAcct1.focus_account_date_stamp__c,date.today());

		List<Account> acctList2 = [select id, name, focus_account__c, focus_account_date_stamp__c, status_change_date__c from Account where (focus_account__c = true and AE_Rep__c = :user1.id 
					and (Status__c =: 'No Traction' or Status__c =: 'Dial in Last 45 Days' or Status__c =: 'Connect in Last 45 Days' or Status__c =: 'Conversation in Last 45 Days'
					or Status__c =: 'Needs Sourcing' or Status__c =: 'Opportunity Unqualified' or Status__c =: 'Opportunity Lost')) order by VMT_Account_Score__c desc nulls last];
        system.assertEquals(acctList2.size(),15);
        Account nonFocusAcct2 = [select id, name, focus_account__c from Account where id =: nonFocusAcct.id];
        system.assertEquals(nonFocusAcct2.Focus_Account__c,false);
        
*/		
    }
}