src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Post-Sales field. Checked if Customer has no maintenance renewals greater than 6k (open or closed within last 6 months/current year). Set by BatchUpdateTaskOthers.</description>
        <label>Auto Bill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Core_Count__c</fullName>
        <label>Core Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_LTV_Tier__c</fullName>
        <label>Customer LTV Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1 (1M+)</fullName>
                    <color>#33CC00</color>
                    <label>Tier 1</label>
                </value>
                <value>
                    <fullName>Tier 2 (500K+)</fullName>
                    <color>#3366FF</color>
                    <label>Tier 2</label>
                </value>
                <value>
                    <fullName>Tier 3 (100K+)</fullName>
                    <color>#FF0000</color>
                    <label>Tier 3</label>
                </value>
                <value>
                    <fullName>Tier 4 (50K+)</fullName>
                    <color>#FF6600</color>
                    <label>Tier 4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demo_Count__c</fullName>
        <label>Demo Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Evaluation_Meeting_Count__c</fullName>
        <label>Evaluation Meeting Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exclude_From_Auto_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manual Checkbox to exclude account from auto bill process</description>
        <label>Exclude From Auto Bill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Demo_Date__c</fullName>
        <label>First Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Evaluation_Meeting_Date__c</fullName>
        <label>First Evaluation Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hypervisor_Vendor__c</fullName>
        <label>Hypervisor Vendor</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VMware</fullName>
                </value>
                <value>
                    <fullName>Hyper-V (Microsoft)</fullName>
                </value>
                <value>
                    <fullName>Xen (Open Source)</fullName>
                </value>
                <value>
                    <fullName>Xen (Citrix)</fullName>
                </value>
                <value>
                    <fullName>KVM (Openstack)</fullName>
                </value>
                <value>
                    <fullName>KVM (Redhat)</fullName>
                </value>
                <value>
                    <fullName>OracleVM</fullName>
                </value>
                <value>
                    <fullName>Heterogeneous</fullName>
                </value>
                <value>
                    <fullName>IBM PowerVM</fullName>
                </value>
                <value>
                    <fullName>Acropolis</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Other (Specify)</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Activity_with_Outcome_Date__c</fullName>
        <label>Last Activity with Outcome Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Core_Count_Update_Date__c</fullName>
        <label>Last Core Count Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Evaluation_Meeting_Date__c</fullName>
        <label>Last Evaluation Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Socket_Count_Update_Date__c</fullName>
        <label>Last Socket Count Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_VM_Count_Update_Date__c</fullName>
        <label>Last VM Count Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Demo_Date__c</fullName>
        <label>Last Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_EBC_Meeting__c</fullName>
        <description>Filled by batch. Looks for most recent Customer EBC task created for this account</description>
        <label>Most Recent EBC Meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Roadmap_Meeting__c</fullName>
        <description>Filled by Batch. Most Recent Customer Roadmap Meeting task logged for the account.</description>
        <label>Most Recent Roadmap Meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opps_Closed_Won__c</fullName>
        <label>Opps (Closed Won)</label>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>New,Upsell,Training Only,Subscription Renewal</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opps_Identify__c</fullName>
        <label>Opps (Identify)</label>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Identify</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opps_open_Pipe__c</fullName>
        <label>Opps (open, Pipe+)</label>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>PO received, Commit, Strong Upside, Upside, Pipeline</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>New,Upsell,Training Only</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Revisit_Date__c</fullName>
        <inlineHelpText>When should the account be revisited?</inlineHelpText>
        <label>Revisit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Socket_Count__c</fullName>
        <label>Socket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>RIGHT(Status_Ordered__c,LEN(Status_Ordered__c)-4)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Owner_Team__c</fullName>
        <formula>IF(ISBLANK(AE_Rep__c),&quot;No Team Assigned&quot;,TEXT(AE_Rep__r.Team__c))

/*
IF(AND(NOT(ISBLANK(AE_Rep__c)),AE_Rep__r.UserRole.Name&lt;&gt;&quot;VMT SF admin&quot; ),TEXT(AE_Rep__r.Team__c),
IF(AE_Rep__r.Full_Name__c=&quot;Chris MacNaughton&quot;,&quot;Enterprise Unassigned&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Stuart Horgan&quot;,&quot;US Commercial&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Ben Waller&quot;,&quot;&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Eddie Genao&quot;,&quot;N/A&quot;,
IF(OR(UPPER(BillingCountry)=&quot;UNITED STATES&quot;,UPPER(BillingCountry)=&quot;CANADA&quot;, UPPER(BillingCountry)=&quot;US&quot;,UPPER(BillingCountry)=&quot;CA&quot;),
Territory_Team__c,IF(Region_country_1__c = &quot;LATAM&quot;,&quot;LATAM&quot;,&quot;EMEA Commercial&quot;)))))))
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SchedBatchUpdateOthersEMEAEnt.cls
global class SchedBatchUpdateOthersEMEAEnt implements Schedulable {
  
  global void execute(SchedulableContext sc) {
        BatchUpdateTaskOthers b = new BatchUpdateTaskOthers();
       b.query = 'SELECT id, First_Demo_Date__c, First_Evaluation_Meeting_Date__c, Demo_Count__c, Evaluation_Meeting_Count__c, Last_Evaluation_Meeting_Date__c, Rating, Revisit_Date__c, ' + 
            'Latest_Demo_Date__c, Opps_Identify__c, Opps_open_pipe__c, Opps_closed_Won__c, Hypervisor_Vendor__c, Core_Count__c, Last_Core_Count_Update_Date__c, ' + 
            'Last_Activity_With_Outcome_Date__c, Socket_Count__c, VM_Count__c, Last_Socket_Count_Update_Date__c, Last_VM_Count_Update_Date__c, Name, auto_bill__c, Status__c, Customer_LTV_Tier__c, Exclude_From_Auto_Bill__c, Most_Recent_EBC_Meeting__c, Most_Recent_Roadmap_Meeting__c ' +
            'FROM Account where (Id != \'001D000000v5q5N\' and Status__c != \'Defunct Account\' and (Territory_Owner_Team__c = \'EMEA Enterprise\'))';
       
       ID batchprocessid = Database.executeBatch(b, 4);
  }
  
}