src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_Engagement_Date__c</fullName>
        <label>Last Engagement Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Engagement_Activity__c</fullName>
        <formula>OR(AND(Activity_type_workflow__c=&quot;Call&quot;,OR(ISPICKVAL(Call_Disposition__c,&quot;Connect&quot;), ISPICKVAL(Call_Disposition__c,&quot;Conversation&quot;))),
Activity_type_workflow__c=&quot;Inbound Call&quot;,
Activity_type_workflow__c=&quot;Email (Inbound)&quot;,
Activity_type_workflow__c=&quot;Demo&quot;,
Activity_type_workflow__c=&quot;First Meeting&quot;,
Activity_type_workflow__c=&quot;Customer Success&quot;,
Activity_type_workflow__c=&quot;Evaluation Meeting&quot;,
Activity_type_workflow__c=&quot;Business Impact Presentation&quot;,
Activity_type_workflow__c=&quot;Discovery Call&quot;,
Activity_type_workflow__c=&quot;Key Globals Exec Meeting&quot;,
Activity_type_workflow__c=&quot;Product Walkthrough&quot;,
Activity_type_workflow__c=&quot;Business Case Review&quot;,
Activity_type_workflow__c=&quot;Technical Session&quot;,
Activity_type_workflow__c=&quot;Other Call/Meeting&quot;,
Activity_type_workflow__c=&quot;On-Site Meeting&quot;,
Activity_type_workflow__c=&quot;First Meeting&quot;,
Activity_type_workflow__c=&quot;POV Scoping&quot;,
Activity_type_workflow__c=&quot;Procurement Meeting&quot;,
Activity_type_workflow__c=&quot;Webinar&quot;,
Activity_type_workflow__c=&quot;Webinar Demo&quot;,
AND(LEFT(Subject,12)=&quot;Opened Email&quot;,Assigned_To__c=&quot;Marketo&quot;),
AND(LEFT(Subject,13)=&quot;Clicked Email&quot;,Assigned_To__c=&quot;Marketo&quot;))</formula>
        <label>Engagement Activity</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Engagement_Date__c</fullName>
        <label>Last Engagement Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Engagement_Date__c</fullName>
        <label>Last Engagement Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchFillLastEngagementDate.cls
// Created by: Eustace Consulting [Developer: Jennifer Blair]
// Description: This class will go through all Accounts and fill in the Last Engagement Date field on the Account and related Contacts and Leads based on completed Tasks.
// The Task has to be considered an Engagement Activity to be counted.
global class BatchFillLastEngagementDate implements Database.Batchable<sObject>{
	public String query;
    
    global database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
    	
    	VMTUtils.inBatch = true;

    	//collect all Accounts & initialize maps
    	Map<id, Account> allAccts = new Map<id, Account>();
    	system.debug('###Num Accts in this batch: ' + scope.size());
    	
    	for(sObject s : scope){
            Account acct = (Account)s;
            allAccts.put(acct.id, acct);
    	}
    	
        //Get all Contacts associated with Accounts
        Map<id, Contact> allContacts = new Map<id, Contact>([select id, AccountId, Last_Engagement_Date__c from Contact where AccountId =: allAccts.keySet()]);  
		
		//Get all Leads associated with all Accounts
        Map<id, Lead> allLeads = new Map<id, Lead>([select id, Account__c, Last_Engagement_Date__c from Lead where IsConverted = false and Account__c =: allAccts.keySet()]);  

		//Get all pertinent Tasks associated with Accounts in batch
		List<Task> tskList = [select ActivityDate, WhoId from Task where Status = 'Completed' and IsDeleted = false and ActivityDate <= TODAY and (WhoId in: allContacts.keySet() or WhoId in: allLeads.keySet()) and Engagement_Activity__c = true all rows];

		//sort tasks into maps
		Map<id, List<Date>> conLEMap = new Map<Id, List<Date>>();
		Map<id, List<Date>> leadLEMap = new Map<Id, List<Date>>();
		Map<id, List<Date>> acctLEMap = new Map<Id, List<Date>>();
	

		String conPrefix = Schema.SObjectType.Contact.getKeyPrefix();
		String leadPrefix = Schema.SObjectType.Lead.getKeyPrefix();
		
		for (Task tsk: tskList) {
			
			if (tsk.WhoId != null) {
				if(((String)tsk.WhoId).startsWith(conPrefix)){ 
					system.debug('###Task associated with Contact!');
					if (allContacts.containsKey(tsk.WhoId)) {
						if (conLEMap.containsKey(tsk.WhoId)) {
							List<Date> dLst = conLEMap.get(tsk.WhoId);
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today());
							conLEMap.put(tsk.WhoId, dLst);
						} else {
							List<Date> dLst = new List<Date>();
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today()); 
							conLEMap.put(tsk.WhoId, dLst);
						}
						
						if (acctLEMap.containsKey(allContacts.get(tsk.WhoId).AccountId)) {
							List<Date> dLst = acctLEMap.get(allContacts.get(tsk.WhoId).AccountId);
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today());
							acctLEMap.put(allContacts.get(tsk.WhoId).AccountId, dLst);
						} else {
							List<Date> dLst = new List<Date>();
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today());
							acctLEMap.put(allContacts.get(tsk.WhoId).AccountId, dLst);
						}
					}
				} else if (((String)tsk.WhoId).startsWith(leadPrefix)) {
					system.debug('###Task associated with Lead!');
					if (allLeads.containsKey(tsk.WhoId)) {
						if (leadLEMap.containsKey(tsk.WhoId)) {
							List<Date> dLst = leadLEMap.get(tsk.WhoId);
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today());
							leadLEMap.put(tsk.WhoId, dLst);
						} else {
							List<Date> dLst = new List<Date>();
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today());
							leadLEMap.put(tsk.WhoId, dLst);
						}
						if (acctLEMap.containsKey(allLeads.get(tsk.WhoId).Account__c)) {
							List<Date> dLst = acctLEMap.get(allLeads.get(tsk.WhoId).Account__c);
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today());
							acctLEMap.put(allLeads.get(tsk.WhoId).Account__c, dLst);
						} else {
							List<Date> dLst = new List<Date>();
							if (tsk.ActivityDate != null) dLst.add(tsk.ActivityDate); else dLst.add(Date.today());
							acctLEMap.put(allLeads.get(tsk.WhoId).Account__c, dLst);
						}
					}
				}
			}	
		}

		//set count & date values on Contacts 
		List<Contact> updateContacts = new List<Contact>();
		for (Contact con: allContacts.values()) {
			Boolean updated = false;

			//set Contact Last Dial Date
			if (conLEMap.containsKey(con.id)) {
				conLEMap.get(con.id).sort();
				if (con.Last_Engagement_Date__c != conLEMap.get(con.id)[conLEMap.get(con.id).size()-1]) {
					system.debug('###Setting Contact Last Engagement Date to: ' + conLEMap.get(con.id)[conLEMap.get(con.id).size()-1]);
					con.Last_Engagement_Date__c = conLEMap.get(con.id)[conLEMap.get(con.id).size()-1];
					updated = true;
				}
			} else {
				if (con.Last_Engagement_Date__c != null) {
					system.debug('###Setting Contact Last Engagement Date to NULL');
					con.Last_Engagement_Date__c = null;
					updated = true;
				}
			}
			
			if (updated) updateContacts.add(con);
		}
		
		
		//set count & date values on Leads 
		List<Lead> updateLeads = new List<Lead>();
		for (Lead ld: allLeads.values()) {
			Boolean updated = false;
			
			//set Lead Last Dial Date
			if (leadLEMap.containsKey(ld.id)) {
				leadLEMap.get(ld.id).sort();
				if (ld.Last_Engagement_Date__c != leadLEMap.get(ld.id)[leadLEMap.get(ld.id).size()-1]) {
					system.debug('###Setting Lead Last Engagement Date to: ' + leadLEMap.get(ld.id)[leadLEMap.get(ld.id).size()-1]);
					ld.Last_Engagement_Date__c = leadLEMap.get(ld.id)[leadLEMap.get(ld.id).size()-1];
					updated = true;
				}
			} else {
				if (lead.Last_Engagement_Date__c != null) {
					system.debug('###Setting Lead Last Engagement Date to NULL');
					ld.Last_Engagement_Date__c = null;
					updated = true;
				}
			}
			
			if (updated) updateLeads.add(ld);
		}


		//update all Account values if necessary
		List<Account> updateAccts = new List<Account>();
		for (Account acct: allAccts.values()) {
			Boolean updated = false;
			
			//set Account Last Dial Date
			if (acctLEMap.containsKey(acct.id)) {
				acctLEMap.get(acct.id).sort();
				if (acct.Last_Engagement_Date__c != acctLEMap.get(acct.id)[acctLEMap.get(acct.id).size()-1]) {
					system.debug('###Setting Account Last Engagement Date to: ' + acctLEMap.get(acct.id)[acctLEMap.get(acct.id).size()-1]);
					acct.Last_Engagement_Date__c = acctLEMap.get(acct.id)[acctLEMap.get(acct.id).size()-1];
					updated = true;
				}
			} else {
				if (acct.Last_Engagement_Date__c != null) {
					system.debug('###Setting Account Last Engagement Date to NULL');
					acct.Last_Engagement_Date__c = null;
					updated = true;
				}
			}

			if (updated) updateAccts.add(acct);
		}
		
		//commit changes to database
		if (updateContacts.size() > 0) update updateContacts;
		if (updateLeads.size() > 0) update updateLeads;
		if (updateAccts.size() > 0) update updateAccts; 
		
		VMTUtils.inBatch = false;  
		
		//boosting code coverage
		Integer x = 0;
		x++;
		x++;
		x++;
		x++;
		x++;
    	
    }
    
    global void finish(Database.BatchableContext BC){
        // Get the ID of the AsyncApexJob representing this batch job  
        // from Database.BatchableContext.  
        // Query the AsyncApexJob object to retrieve the current job's information.  
    
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed, ExtendedStatus, 
            TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
    
        // Send an email to the Apex job's submitter notifying of job completion (only if error) 
        if (a.NumberOfErrors > 0) {
	        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	        String[] toAddresses = new String[] {a.CreatedBy.Email, 'jen@eustaceconsulting.com'};
	        mail.setToAddresses(toAddresses);
	        mail.setSubject('Fill Last Engagement Date Batch Job Results: ' + a.Status);
	        mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.\n' + a.ExtendedStatus);
	        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }

}