src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Attention_Reason_NEW__c</fullName>
        <label>Customer Attention Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown product usage</fullName>
                </value>
                <value>
                    <fullName>Minimal product usage</fullName>
                </value>
                <value>
                    <fullName>No relationship kickoff call</fullName>
                </value>
                <value>
                    <fullName>Renewal due in &lt;2 mos, opp not in Commit</fullName>
                </value>
                <value>
                    <fullName>Stakeholders dissatisfied</fullName>
                </value>
                <value>
                    <fullName>Competitive pressure</fullName>
                </value>
                <value>
                    <fullName>No interaction in 4+ months</fullName>
                </value>
                <value>
                    <fullName>Technical issue</fullName>
                </value>
                <value>
                    <fullName>Training/services not scheduled</fullName>
                </value>
                <value>
                    <fullName>VMTurbo user left</fullName>
                </value>
                <value>
                    <fullName>Plan to outsource</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Status__c</fullName>
        <label>Customer Churn Risk</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                    <color>#78C953</color>
                    <label>Green</label>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                    <color>#F3D904</color>
                    <label>Yellow</label>
                </value>
                <value>
                    <fullName>Red</fullName>
                    <color>#FF0000</color>
                    <label>Red</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <color>#3333FF</color>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Activity_with_Outcome_Date__c</fullName>
        <label>Last Activity with Outcome Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Customer_Touchpoint__c</fullName>
        <description>For the Customer Experience team</description>
        <label>Last Customer Touchpoint</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>RIGHT(Status_Ordered__c,LEN(Status_Ordered__c)-4)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Owner_Team__c</fullName>
        <formula>IF(ISBLANK(AE_Rep__c),&quot;No Team Assigned&quot;,TEXT(AE_Rep__r.Team__c))

/*
IF(AND(NOT(ISBLANK(AE_Rep__c)),AE_Rep__r.UserRole.Name&lt;&gt;&quot;VMT SF admin&quot; ),TEXT(AE_Rep__r.Team__c),
IF(AE_Rep__r.Full_Name__c=&quot;Chris MacNaughton&quot;,&quot;Enterprise Unassigned&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Stuart Horgan&quot;,&quot;US Commercial&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Ben Waller&quot;,&quot;&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Eddie Genao&quot;,&quot;N/A&quot;,
IF(OR(UPPER(BillingCountry)=&quot;UNITED STATES&quot;,UPPER(BillingCountry)=&quot;CANADA&quot;, UPPER(BillingCountry)=&quot;US&quot;,UPPER(BillingCountry)=&quot;CA&quot;),
Territory_Team__c,IF(Region_country_1__c = &quot;LATAM&quot;,&quot;LATAM&quot;,&quot;EMEA Commercial&quot;)))))))
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Owner Team</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SchedBatchUpdateLastActOutDateUSVel.cls
global class SchedBatchUpdateLastActOutDateUSVel implements schedulable {
	
	global void execute(SchedulableContext sc) {
		BatchUpdateLastAcctOutcomeDate b = new BatchUpdateLastAcctOutcomeDate();
		b.query = 'SELECT id, Last_Activity_With_Outcome_Date__c, customer_status__c, last_customer_touchpoint__c, Customer_Attention_Reason_NEW__c, Name FROM Account where (Id != \'001D000000v5q5N\' and Status__c != \'Defunct Account\' and (Territory_Owner_Team__c = \'Closers Club\' or Territory_Owner_Team__c = \'Notti By Nature\' or Territory_Owner_Team__c = \'Green Berets\' or Territory_Owner_Team__c = \'Shake n Bake\' or Territory_Owner_Team__c = \'SEC\' or Territory_Owner_Team__c = \'The Kitchen\' or Territory_Owner_Team__c = \'The Hunchbacks\' or Territory_Owner_Team__c = \'The Wild West\' or Territory_Owner_Team__c = \'The Titans\' or Territory_Owner_Team__c = \'Xccelerators\' or Territory_Owner_Team__c = \'Los Conquistadores\'))';
	   	
	   	ID batchprocessid = Database.executeBatch(b, 20); 
		
	}

}