src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Demo__c.object
<CustomObject>
    <label>Demo</label>
    <nameField>
        <label>Demo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meaningful Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Auto_Number__c.object
<CustomObject>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Auto Number</label>
    <nameField>
        <label>Lead Auto Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Monthly_Rep_Goals__c.object
<CustomObject>
    <fields>
        <fullName>Goal_Label_for_Rep_Dash__c</fullName>
        <label>Goal Label (for Rep Dash)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rep_Type__c</fullName>
        <label>Rep Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Type__c</fullName>
        <label>Team Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Monthly Rep Goals</label>
    <nameField>
        <label>Goal Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Rep Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <inlineHelpText>Date when the deal should show up on financial statements (for accounting purposes).  This field is for Finance use only.</inlineHelpText>
        <label>Close Date (Finance)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Identified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person who identified the opportunity.  Can be a member of the channel team if the deal was referred to VMTurbo by the channel.</inlineHelpText>
        <label>Identified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID_Date__c</fullName>
        <inlineHelpText>This is the date that the opportunity was moved to Pipeline or above (VMT&apos;s definition of an opportunity being identified - the Identify stage doesn&apos;t count).  This field is updated automatically - DO NOT UPDATE MANUALLY.</inlineHelpText>
        <label>Opportunity ID Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <inlineHelpText>Name of the opportunity owner&apos;s team.  This is the team that the deal is assigned to for reporting (the team that is actually driving the deal, regardless of whether or not it goes through the channel)</inlineHelpText>
        <label>Owner Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC Enterprise</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 1</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 2</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 3</fullName>
                </value>
                <value>
                    <fullName>US Commercial West 1</fullName>
                </value>
                <value>
                    <fullName>US Commercial West 2</fullName>
                </value>
                <value>
                    <fullName>US Commercial West 3</fullName>
                </value>
                <value>
                    <fullName>Enterprise East 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise East 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise East 3</fullName>
                </value>
                <value>
                    <fullName>Enterprise Central 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise Central 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise Central 3</fullName>
                </value>
                <value>
                    <fullName>Enterprise West 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise West 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise SDR</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial France</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise France</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise SDR</fullName>
                </value>
                <value>
                    <fullName>Global Accounts International</fullName>
                </value>
                <value>
                    <fullName>Global Accounts US</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>Candy Time</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Xccelerators</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testChartController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 */
@isTest
private class testChartController {

    static testMethod void getChartData_Demos() {
		Test.StartTest();
		CreateNDemoScheduledTasks();
		CreateNDemoCompletedTasks();
		Test.StopTest();
		
		testChartController.BuildMonthlyRepGoals();

		ChartController.getRemoteData_DemosCompleted();
		ChartController.getRemoteData_DemosScheduled();
/*

		ChartController.getChartData_DemosCompleted();
		ChartController.getChartData_DemosScheduled();
*/
    }

    static testMethod void OpportunityUnitTest() {
		Test.StartTest();
		CreateNPipelineOpportunities();
		CreateNClosedWonOpportunities();
		Test.StopTest();
		
		testChartController.BuildMonthlyRepGoals();
		ChartController.getRemoteData_OpportunitiesIdentifiedAmount();
		ChartController.getRemoteData_OpportunitiesIdentifiedCount();
		ChartController.getRemoteData_BookingsIdentifiedAmount();

    }
    static testMethod void CreateNClosedWonOpportunities() {
    	
    	lead_auto_number__c leadnum = new lead_auto_number__c(round_robin_number__c = 0);
		insert leadnum;
		
		Date startRange = Date.today().addDays(-365);
		Date endRange = Date.today().addDays(14);
		Integer numOfOppsToCreate = 2; // ideal value 4, but org is not bulkified    	
		Id ownerId = UserInfo.getUserId();

		Campaign cpg = new Campaign(
				Name = 'Test One',
				IsActive = true,
				StartDate = date.today().addDays(-10),
				Type = 'Advertisement',
				Status = 'In Progress'
			);
		insert cpg;
		
		Account a = new Account(name = 'Test Account',ownerId=ownerId);
		insert a;

		Date oppDate = startRange;
		for (Integer opp = 0; opp < numOfOppsToCreate; opp++){
			oppDate = oppDate.addDays((Math.random() * 10).intValue() * 7);

			
			Opportunity o = new Opportunity(
								Name = 'Test Opp ' + opp,
								StageName = 'Closed Won',
								Owner_Team__c = 'Virtual Empire',
								accountid = a.id,
								amount = (Math.random() * 100000).intValue(),
								CloseDate = oppDate,
								Booking_Date__c = oppDate,
								Type = 'New',
								Identified_By__c = ownerId,
								Opportunity_ID_Date__c = oppDate,
								LeadSource = '3PT: eMedia 2013Q4',
								CampaignId = cpg.id,
								ownerId = ownerId
								);
			insert o;
		}
 
    }
	
	static testMethod void CreateNPipelineOpportunities() {
		
		lead_auto_number__c leadnum = new lead_auto_number__c(round_robin_number__c = 0);
		insert leadnum;
		
		Date startRange = Date.today().addDays(-365);
		Date endRange = Date.today().addDays(14);
		Integer numOfOppsToCreate = 2; // ideal value 8, but org is not bulkified    	
		Id ownerId = UserInfo.getUserId();

		Campaign cpg = new Campaign(
				Name = 'Test One',
				IsActive = true,
				StartDate = date.today().addDays(-10),
				Type = 'Advertisement',
				Status = 'In Progress'
			);
		insert cpg;
		
		Account a = new Account(name = 'Test Account',ownerId=ownerId);
		insert a;

		Date oppDate = startRange;
		for (Integer opp = 0; opp < numOfOppsToCreate; opp++){
			oppDate = oppDate.addDays((Math.random() * 10).intValue() * 7);

			
			Opportunity o = new Opportunity(
								Name = 'Test Opp ' + opp,
								StageName = 'Pipeline',
								Owner_Team__c = 'Virtual Empire',
								accountid = a.id,
								amount = (Math.random() * 100000).intValue(),
								CloseDate = oppDate,
								Booking_Date__c = oppDate,
								Type = 'New',
								Identified_By__c = ownerId,
								Opportunity_ID_Date__c = oppDate,
								LeadSource = '3PT: eMedia 2013Q4',
								CampaignId = cpg.id,
								ownerId = ownerId
								);
			insert o;
		}
 
    }

	static testMethod void CreateNDemoCompletedTasks() {
		Date startRange = Date.today().addDays(-365);
		Date endRange = Date.today().addDays(14);
		Integer numToCreate = 2; // ideal value 70, but org is not bulkified    	
		Id ownerId = UserInfo.getUserId();

		Demo__c d = new Demo__c(name = 'Test Demo');
		insert d;

		Date taskDate = startRange;
		for (Integer i = 0; i < numToCreate; i++){
			taskDate = taskDate.addDays((Math.random() * 10).intValue() * 1);

			
			Task t = new Task(
							Subject = 'Test Task ' + i,
							Type = 'Demo',
							Status = 'Completed',
							ActivityDate = taskDate,
							WhatId = d.id,
							priority = 'Normal',
							ownerid = ownerId
							);
			insert t;

		}
 
    }

	static testMethod void CreateNDemoScheduledTasks() {
		Date startRange = Date.today().addDays(-365);
		Date endRange = Date.today().addDays(14);
		Integer numToCreate = 2; // ideal value 30, but org is not bulkified    	
		Id ownerId = UserInfo.getUserId();

		Demo__c d = new Demo__c(name = 'Test Demo');
		insert d;

		Date taskDate = startRange;
		for (Integer i = 0; i < numToCreate; i++){
			taskDate = taskDate.addDays((Math.random() * 10).intValue() * 3);

			
			Task t = new Task(
							Subject = 'Test Task ' + i,
							Type = 'Demo',
							Status = 'New',
							ActivityDate = taskDate,
							WhatId = d.id,
							priority = 'Normal',
							ownerid = ownerId
							);
			insert t;

		}
 
    }
    static testMethod void BuildMonthlyRepGoals() {
		Monthly_Rep_Goals__c demosSched = new Monthly_Rep_Goals__c(
												Name = 'Demos Scheduled',
												Goal_Label_for_Rep_Dash__c = 'Demos Scheduled',
												Team_Type__c = 'BDR',
												Rep_Type__c = 'BDR',
												Goal__c = 16.00,
												Minimum__c = 10.00												
												);
		insert demosSched;
		Monthly_Rep_Goals__c[] demosSchedList = [SELECT id,name from Monthly_Rep_Goals__c WHERE id = :demosSched.id];
		System.Assert(demosSchedList.size() > 0);
		System.Assert(demosSchedList[0].name == 'Demos Scheduled');
		
		Monthly_Rep_Goals__c demosComp = new Monthly_Rep_Goals__c(
												Name = 'Demos Completed (Scheduled By)',
												Goal_Label_for_Rep_Dash__c = 'Demos Completed',
												Team_Type__c = 'BDR',
												Rep_Type__c = 'BDR',
												Goal__c = 12.00,
												Minimum__c = 7.00												
												);
		insert demosComp;
		Monthly_Rep_Goals__c[] demosCompList = [SELECT id,name from Monthly_Rep_Goals__c WHERE id = :demosComp.id];
		System.Assert(demosCompList.size() > 0);
		System.Assert(demosCompList[0].name == 'Demos Completed (Scheduled By)');

		Monthly_Rep_Goals__c oppsId = new Monthly_Rep_Goals__c(
												Name = 'Total Opportunities IDed',
												Goal_Label_for_Rep_Dash__c = 'Opps IDed',
												Team_Type__c = 'BDR',
												Rep_Type__c = 'BDR',
												Goal__c = 3.75,
												Minimum__c = 2.00												
												);
		insert oppsId;
		Monthly_Rep_Goals__c[] oppsIdList = [SELECT id,name from Monthly_Rep_Goals__c WHERE id = :oppsId.id];
		System.Assert(oppsIdList.size() > 0);
		System.Assert(oppsIdList[0].name == 'Total Opportunities IDed');
		
		Monthly_Rep_Goals__c asp = new Monthly_Rep_Goals__c(
												Name = 'BDR ASP',
												Goal_Label_for_Rep_Dash__c = 'BDR ASP',
												Team_Type__c = 'BDR',
												Rep_Type__c = 'BDR',
												Goal__c = 40000,
												Minimum__c = 0												
												);
		insert asp;
		Monthly_Rep_Goals__c[] aspList = [SELECT id,name from Monthly_Rep_Goals__c WHERE id = :asp.id];
		System.Assert(aspList.size() > 0);
		System.Assert(aspList[0].name == 'BDR ASP');

		Monthly_Rep_Goals__c bookId = new Monthly_Rep_Goals__c(
												Name = 'Bookings ID\'d',
												Goal_Label_for_Rep_Dash__c = 'Bookings ID\'d',
												Team_Type__c = 'BDR',
												Rep_Type__c = 'BDR',
												Goal__c = 40000.00,
												Minimum__c = 25000.00												
												);
		insert bookId;
		Monthly_Rep_Goals__c[] bookIdList = [SELECT id,name from Monthly_Rep_Goals__c WHERE id = :bookId.id];
		System.Assert(bookIdList.size() > 0);
		System.Assert(bookIdList[0].name == 'Bookings ID\'d');
    }

    static testMethod void QueryForGoalThatDoesntExist() {
		testChartController.BuildMonthlyRepGoals();
		ChartController.getMonthlyRepGoal('ZZZZZZ');    	
    }
}