src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AE_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_for_Lead_link__c</fullName>
        <externalId>true</externalId>
        <label>Email for Lead link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_source_transfer__c</fullName>
        <description>Transfers the lead source upon conversion</description>
        <label>Lead source transfer</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Owner_Team__c</fullName>
        <formula>IF(ISBLANK(AE_Rep__c),&quot;No Team Assigned&quot;,TEXT(AE_Rep__r.Team__c))

/*
IF(AND(NOT(ISBLANK(AE_Rep__c)),AE_Rep__r.UserRole.Name&lt;&gt;&quot;VMT SF admin&quot; ),TEXT(AE_Rep__r.Team__c),
IF(AE_Rep__r.Full_Name__c=&quot;Chris MacNaughton&quot;,&quot;Enterprise Unassigned&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Stuart Horgan&quot;,&quot;US Commercial&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Ben Waller&quot;,&quot;&quot;,
IF(AE_Rep__r.Full_Name__c=&quot;Eddie Genao&quot;,&quot;N/A&quot;,
IF(OR(UPPER(BillingCountry)=&quot;UNITED STATES&quot;,UPPER(BillingCountry)=&quot;CANADA&quot;, UPPER(BillingCountry)=&quot;US&quot;,UPPER(BillingCountry)=&quot;CA&quot;),
Territory_Team__c,IF(Region_country_1__c = &quot;LATAM&quot;,&quot;LATAM&quot;,&quot;EMEA Commercial&quot;)))))))
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Owner Team</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Owner_Team__c</fullName>
        <formula>Account__r.Territory_Owner_Team__c</formula>
        <label>Territory Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mkto71_Inferred_Country__c</fullName>
        <label>Inferred Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mkto71_Inferred_State_Region__c</fullName>
        <label>Inferred State Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executive</fullName>
                    <label>a_Executive</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <label>a_Finance</label>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                    <label>a_Marketing</label>
                </value>
                <value>
                    <fullName>Recruiting</fullName>
                    <label>a_Recruiting</label>
                </value>
                <value>
                    <fullName>Sales Enablement</fullName>
                    <label>a_Sales Enablement</label>
                </value>
                <value>
                    <fullName>APAC Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial France</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise France</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise Germany</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise SDR</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise Unallocated</fullName>
                </value>
                <value>
                    <fullName>Global Accounts International</fullName>
                </value>
                <value>
                    <fullName>Global Accounts US</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>No Team Assigned</fullName>
                    <default>true</default>
                    <label>No Team Assigned</label>
                </value>
                <value>
                    <fullName>Candy Time</fullName>
                    <label>p_Candy Time</label>
                </value>
                <value>
                    <fullName>Technical Account Managers</fullName>
                    <label>p_Technical Account Managers</label>
                </value>
                <value>
                    <fullName>The Methodology Commercial</fullName>
                </value>
                <value>
                    <fullName>The Pack Commercial</fullName>
                </value>
                <value>
                    <fullName>US Commercial</fullName>
                </value>
                <value>
                    <fullName>US Commercial East</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 1</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 2</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 3</fullName>
                </value>
                <value>
                    <fullName>US Commercial East SDR</fullName>
                </value>
                <value>
                    <fullName>US Commercial Unallocated</fullName>
                </value>
                <value>
                    <fullName>US Commercial West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Role_Name__c</fullName>
        <formula>UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Role Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/testLeadLinkToAccount.cls
// Created by: Eustace Consulting [www.eustaceconsulting.com][Developer: Jennifer Blair]
// Tests: LeadLinkToAccount.trigger      
@isTest
private class testLeadLinkToAccount {
/*

    static testMethod void myUnitTest() {
    	
        User usr = [select id from User where UserType = 'Standard' and IsActive = true limit 1];
//        List<User> bangersnCash = [select id, name from User where (Team__c =: 'Bangers n Cash' and name != 'Brady Lenahan' and isActive = true and (userRole.name like '%Account Executive%' or userRole.name like '%Key Account%')) order by lastName asc];

        //Create Account & Lead w/ same Company Name
        Account acct1 = new Account(Name = 'Bose Headphones');
        insert acct1;
        
        Lead lead1 = new Lead(FirstName = 'Bob', LastName = 'Jones', Company = 'Bose Headphones', LeadSource = 'Prospecting - RainKing', AnnualRevenue = 10, NumberOfEmployees = 66,
        	Street = '1 Pine St.', City = 'Springfield', mkto71_Inferred_State_Region__c = 'Nebraska', PostalCode = '12345', mkto71_Inferred_Country__c = 'United States', Industry = 'Healthcare', Website = 'www.test.com');
        insert lead1;
        
        //make sure Lead is placed under the Account & fields set on Acct
        lead1 = [select id, OwnerId, Account__c, LeadSource, AnnualRevenue, NumberOfEmployees, Street, City, mkto71_Inferred_State_Region__c, PostalCode, mkto71_Inferred_Country__c, Industry, Website from Lead where id =: lead1.id];
        acct1 = [select id, OwnerId, Lead_source_transfer__c, AnnualRevenue, NumberOfEmployees, BillingStreet, BillingState, BillingCity, BillingPostalCode, BillingCountry, Industry, Website from Account where id =: acct1.id];
        system.assertEquals(lead1.Account__c, acct1.id);
        system.assertEquals(lead1.OwnerId, acct1.OwnerId);
        system.assertEquals(acct1.Lead_source_transfer__c, lead1.LeadSource);
        system.assertEquals(acct1.AnnualRevenue, lead1.AnnualRevenue);
        system.assertEquals(acct1.NumberOfEmployees, lead1.NumberOfEmployees);
        system.assertEquals(acct1.BillingStreet, lead1.Street);
        system.assertEquals(acct1.BillingCity, lead1.City);
        system.assertEquals(acct1.BillingState, lead1.mkto71_Inferred_State_Region__c);
        system.assertEquals(acct1.BillingPostalCode, lead1.PostalCode);
        system.assertEquals(acct1.BillingCountry, lead1.mkto71_Inferred_Country__c);
        system.assertEquals(acct1.Industry, lead1.Industry);
        system.assertEquals(acct1.Website, lead1.Website);
       
        //create another lead with different Co.
        Lead lead2 = new Lead(OwnerId = usr.id, FirstName = 'Jeff', LastName = 'King', Company = 'Kings, Inc.', LeadSource = 'Prospecting - DiscoverOrg', AnnualRevenue = 10, NumberOfEmployees = 66,
        	Street = '1 Pine St.', City = 'Springfield', State = 'Nebraska', PostalCode = '12345', Country = 'United States', Industry = 'Healthcare', Website = 'www.test.com');
        insert lead2;
        //make sure new Account is created with fields set
        Account newAcct = [select id, OwnerId, Lead_source_transfer__c, AnnualRevenue, NumberOfEmployees, BillingStreet, BillingState, BillingCity, BillingPostalCode, BillingCountry, Industry, Website from Account where Name = 'Kings, Inc.'];
        lead2 = [select Account__c, OwnerId, LeadSource, AnnualRevenue, NumberOfEmployees, Street, City, State, PostalCode, Country, Industry, Website from Lead where id =: lead2.id];
        
        system.assertEquals(lead2.Account__c, newAcct.id);
        system.assertEquals(lead2.OwnerId, newAcct.OwnerId);
        system.assertEquals(newAcct.Lead_source_transfer__c, lead2.LeadSource);
        system.assertEquals(newAcct.AnnualRevenue, lead2.AnnualRevenue);
        system.assertEquals(newAcct.NumberOfEmployees, lead2.NumberOfEmployees);
        system.assertEquals(newAcct.BillingStreet, lead2.Street);
        system.assertEquals(newAcct.BillingCity, lead2.City);
        system.assertEquals(newAcct.BillingState, lead2.State);
        system.assertEquals(newAcct.BillingPostalCode, lead2.PostalCode);
        system.assertEquals(newAcct.BillingCountry, lead2.Country);
        system.assertEquals(newAcct.Industry, lead2.Industry);
        system.assertEquals(newAcct.Website, lead2.Website);
        
        //Create a new Account & attached Lead
        Account acct3 = new Account(Name = 'ZZY', OwnerId = usr.id);
        insert acct3;
        
        Lead lead3 = new Lead(Account__c = acct3.id, FirstName = 'Bob', LastName = 'Jones', Company = 'ZZY', LeadSource = 'Unknown', AnnualRevenue = 10, NumberOfEmployees = 66,
        	Street = '1 Pine St.', City = 'Springfield', State = 'NE', PostalCode = '12345', Country = 'USA', Industry = 'Healthcare', Website = 'www.eustace.com');
        insert lead3;
        
        //make sure Lead owner changed & fields set on Acct
        lead3 = [select id, OwnerId, Account__c, LeadSource, AnnualRevenue, NumberOfEmployees, Street, City, State, PostalCode, Country, Industry, Website from Lead where id =: lead3.id];
        acct3 = [select id, OwnerId, Lead_source_transfer__c, AnnualRevenue, NumberOfEmployees, BillingStreet, BillingState, BillingCity, BillingPostalCode, BillingCountry, Industry, Website from Account where id =: acct3.id];
        system.assertEquals(lead3.Account__c, acct3.id);
        system.assertEquals(lead3.OwnerId, acct3.OwnerId);
        system.assertEquals(acct3.Lead_source_transfer__c, lead3.LeadSource);
        system.assertEquals(acct3.AnnualRevenue, lead3.AnnualRevenue);
        system.assertEquals(acct3.NumberOfEmployees, lead3.NumberOfEmployees);
        system.assertEquals(acct3.BillingStreet, lead3.Street);
        system.assertEquals(acct3.BillingCity, lead3.City);
        system.assertEquals(acct3.BillingState, lead3.State);
        system.assertEquals(acct3.BillingPostalCode, lead3.PostalCode);
        system.assertEquals(acct3.BillingCountry, lead3.Country);
        system.assertEquals(acct3.Industry, lead3.Industry);
        system.assertEquals(acct3.Website, lead3.Website);

// start comment block        
        Lead lead4 = new Lead(firstName = 'Intl', lastName = 'Lead', Company = 'UK Trading Co.', city = 'London', country = 'United Kingdom', Industry = 'Retail', Website = 'www.uktrading.co.uk', leadSource = 'Inbound - Website');
        insert lead4;
        
        Account newAcct2 = [select id, OwnerId, Lead_source_transfer__c, BillingCity, BillingCountry, Industry, Territory_Owner_Team__c, Website, AE_Rep__c from Account where Name = 'UK Trading Co.'];
        lead4 = [select Account__c, OwnerId, LeadSource, City, Country, Industry, Website from Lead where id =: lead4.id];
        system.assertEquals(lead4.Account__c, newAcct2.id);
        system.assert(newAcct2.ae_rep__c != null);
        system.assertEquals(newAcct2.Territory_Owner_Team__c,'Bangers n Cash');
        
        Lead lead5 = new Lead(firstName = 'Intl', lastName = 'Lead2', Company = 'Spanish Trading Co.', city = 'Madrid', country = 'Germany', Industry = 'Retail', Website = 'www.sptrading.co.uk', leadSource = 'Inbound - Website');
        insert lead5;
        
        Account newAcct3 = [select id, OwnerId, Lead_source_transfer__c, BillingCity, BillingCountry, Industry, Territory_Owner_Team__c, Website, AE_Rep__c from Account where Name = 'Spanish Trading Co.'];
        lead5 = [select Account__c, OwnerId, LeadSource, City, Country, Industry, Website from Lead where id =: lead5.id];
        system.assertEquals(lead5.Account__c, newAcct3.id);
        system.assert(newAcct3.AE_Rep__c != null);
        system.assertEquals(newAcct3.Territory_Owner_Team__c,'Bangers n Cash');
// end comment block
    }
    
    static testMethod void myUnitTest2() {
    	
    	User testUser = [select id, name from User where user_role_Name__c = 'VMT SF admin' limit 1];
    	
    	Account a2 = new Account(name = 'ESPN News', email_for_lead_link__c = 'def.com', ownerId = testUser.id);
    	insert a2;
    	
    	Lead l4 = new Lead(firstName = 'Justin', lastName = 'Chang', company = 'def', email = 'justin.chang@def.com', leadSource = 'Inbound - Website', status = 'Suspect');
    	insert l4;
    	
    	List<Account> acctList = [select id, name, email_for_lead_link__c from Account where id =: a2.id];
    	system.assertEquals(acctList.size(),1);
    	Lead afterl4 = [select id, ownerId, account__c from Lead where id =: l4.id];
    	system.assertEquals(afterl4.account__c,acctList.get(0).id);
    	system.assertEquals(afterl4.ownerId,testUser.id);
    	
    	Lead l5 = new Lead(firstName = 'Brandon', lastName = 'Chang', company = 'abc', email = 'brandon.chang@abc.com', leadSource = 'Inbound - Website', status = 'Suspect');
    	insert l5;
    	
    	Lead afterl5 = [select id, ownerId, account__c from Lead where id =: l5.id];
    	system.assertEquals(afterl5.account__c,null);
    	
    }
*/
}