src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Active_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Lookup</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Sales Opportunities</relationshipLabel>
        <relationshipName>Open_Sales_Opps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closed Lookup</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Closed Opportunities</relationshipLabel>
        <relationshipName>Closed_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lost_Unqual_Date__c</fullName>
        <label>Lost/Unqual Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maintenance_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maintenance Lookup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Type</field>
                <operation>equals</operation>
                <value>Maintenance Renewal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Maintenance Renewals</relationshipLabel>
        <relationshipName>Open_Maintenance_Renewals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Essentials</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Workload</fullName>
                    <default>true</default>
                    <label>Workload</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Cloud Native</fullName>
                </value>
                <value>
                    <fullName>Virtualization</fullName>
                </value>
                <value>
                    <fullName>Workload Starter</fullName>
                    <isActive>false</isActive>
                    <label>Workload Starter</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_or_Perm__c</fullName>
        <label>Term or Perm</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Term</fullName>
                    <default>true</default>
                    <label>Term</label>
                </value>
                <value>
                    <fullName>Perm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_or_SNM_Length_in_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <label>Term or SNM Length (in Months)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Undiscounted_Renewal_Amount__c</fullName>
        <label>Undiscounted Renewal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>of_CPU_Sockets__c</fullName>
        <description>The number of CPU Sockets (or processors) in the contact&apos;s environment. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</description>
        <inlineHelpText>The number of CPU Sockets (or processors) related to this opportunity. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</inlineHelpText>
        <label># of CPU Sockets [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Cores__c</fullName>
        <label># of Cores [R]</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Virtual_Machines__c</fullName>
        <description>Number of Virtual Machines related to this opportunity.</description>
        <inlineHelpText>Number of Virtual Machines related to this opportunity.</inlineHelpText>
        <label># of Virtual Machines [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestOppSetAcctLookups.cls
/**
 * Test Class for the setOppLookups in the Opportunity Methods Class
 *
 *	Case 1: Closed Won Opp
 *	Case 2: Closed Lost Opp
 *	Case 3: Unqualified Opp within Last 3 Months
 *	Case 4: Unqualified Opp older than 3 Months
 *	Case 5: Maintenance Renewal
 *	Case 6: Normal Open Opp
 *	Case 7: Open opp closed
 *	Case 8: Maintenance Renewal Closed
 *	Case 9: Open Opp switched to Maintenance Renewal
 *	Case 10: Maintenance Renewal switched to Non-Maintenance Renewal
 *  Case 11: Closed Opp Reopened
 *
 *
 *
 */
@isTest
private class TestOppSetAcctLookups {

    static testMethod void myUnitTest() {
    	
        //Create Test Account
		Account acct1 = new Account(Name = 'acct1');
		insert acct1;
		
		//Create Test Cases
		List<Opportunity> oppInsert = new List<Opportunity>();
		
		//Case 1
		Opportunity opp1 = new Opportunity(Type='New',amount=100000,closedate=date.Today(),stageName='Closed Won',name='opp1',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 2
		Opportunity opp2 = new Opportunity(Type='Upsell',amount=100000,closedate=date.Today(),stageName='Closed Lost',name='opp2',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 3
		Opportunity opp3 = new Opportunity(Type='New',amount=100000,closedate=date.Today(),Lost_Unqual_Date__c = date.today(),stageName='Unqualified',name='opp3',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 4
		Opportunity opp4 = new Opportunity(Type='New',amount=100000,closedate=date.Today(),Lost_Unqual_Date__c=date.today().addMonths(-3),stageName='Unqualified',name='opp4',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 5
		Opportunity opp5 = new Opportunity(Type='Maintenance Renewal',amount=100000,Undiscounted_Renewal_Amount__c = 100000,closedate=date.Today(),stageName='Upside',name='opp5',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 6
		Opportunity opp6 = new Opportunity(Type='Subscription Renewal',amount=100000,closedate=date.Today(),stageName='Pipeline',name='opp6',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 7
		Opportunity opp7 = new Opportunity(Type='New',amount=100000,closedate=date.Today(),stageName='PO received',name='opp7',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 8
		Opportunity opp8 = new Opportunity(Type='Maintenance Renewal',amount=100000,Undiscounted_Renewal_Amount__c = 100000,closedate=date.Today(),stageName='Commit',name='opp8',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 9
		Opportunity opp9 = new Opportunity(Type='New',amount=100000,Undiscounted_Renewal_Amount__c = 100000,closedate=date.Today(),stageName='Strong Upside',name='opp9',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 10
		Opportunity opp10 = new Opportunity(Type='Maintenance Renewal',amount=100000,Undiscounted_Renewal_Amount__c = 100000,closedate=date.Today(),stageName='Identify',name='opp10',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		//Case 11
		Opportunity opp11 = new Opportunity(Type='New',amount=100000,closedate=date.Today(),stageName='Closed Won',name='opp11',accountId=acct1.Id,leadsource='Tradeshow',Term_or_Perm__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80, of_Cores__c = 640, Term_or_SNM_Length_in_Months__c = 12, Product_Type__c = 'Workload');
		
		oppInsert.add(opp1); oppInsert.add(opp2); oppInsert.add(opp3); oppInsert.add(opp4); oppInsert.add(opp5);
		oppInsert.add(opp6); oppInsert.add(opp7); oppInsert.add(opp8); oppInsert.add(opp9); oppInsert.add(opp10);
		oppInsert.add(opp11);
        
        insert oppInsert;
        
        List<Opportunity> oppUpdate = new List<Opportunity>();
        
        List<Opportunity> oppQuery= new List<Opportunity>([SELECT id, type, stageName FROM Opportunity WHERE id =: opp7.id or id =: opp8.id or id =: opp9.id or id =: opp10.id or id =: opp11.id]);
        
        for (Opportunity o: oppQuery) {
        	if (o.id == opp7.id) {o.StageName = 'Closed Lost'; oppUpdate.add(o);}
        	else if (o.id == opp8.id) {o.StageName = 'Closed Won'; oppUpdate.add(o);}
        	else if (o.id == opp9.id) {o.Type = 'Maintenance Renewal'; oppUpdate.add(o);}
        	else if (o.id == opp10.id) {o.Type = 'Upsell'; oppUpdate.add(o);}
        	else if (o.id == opp11.id) {o.StageName = 'Commit'; oppUpdate.add(o);}
        } 
        
        update oppUpdate;
        
        
        
        //Query all test opportunities and place in a list
		List<Opportunity> oppAsserts = [SELECT id, AccountId, Closed_Lookup__c, Maintenance_Lookup__c, Active_Lookup__c FROM Opportunity WHERE id =: opp1.id or id =: opp2.id or id =: opp3.id or id =: opp4.id or id =: opp5.id or id =: opp6.id or id =: opp7.id or id =: opp8.id or id =: opp9.id or id =: opp10.id or id =: opp11.id];
		//system.debug('debugOppName: ' + oppList);
		
		//Run through all the test opportunities to check that they match what we expect
		for (Opportunity oppResult: oppAsserts) {
			if (oppResult.id == opp1.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,oppResult.AccountId);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp2.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,oppResult.AccountId);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp3.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,oppResult.AccountId);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp4.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,null);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp5.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,null);
				System.assertEquals(oppResult.Maintenance_Lookup__c,oppResult.AccountId);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp6.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,null);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,oppResult.AccountId);
			}
			else if (oppResult.id == opp7.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,oppResult.AccountId);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp8.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,oppResult.AccountId);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp9.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,null);
				System.assertEquals(oppResult.Maintenance_Lookup__c,oppResult.AccountId);
				System.assertEquals(oppResult.Active_Lookup__c,null);
			}
			else if (oppResult.id == opp10.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,null);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,oppResult.AccountId);
			}
			else if (oppResult.id == opp11.id) {
				System.assertEquals(oppResult.Closed_Lookup__c,null);
				System.assertEquals(oppResult.Maintenance_Lookup__c,null);
				System.assertEquals(oppResult.Active_Lookup__c,oppResult.AccountId);
			}
		} 
    }
}