src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Assign_North_East_2__c</fullName>
        <formula>CASE(UPPER(State_For_Assignment_Rules__c), 
&quot;PA&quot;,&quot;Y&quot;,
&quot;OH&quot;,&quot;Y&quot;, 
&quot;KY&quot;, &quot;Y&quot;,
&quot;IN&quot;, &quot;Y&quot;,
&quot;DE&quot;,&quot;Y&quot;,
&quot;PENNSYLVANIA&quot;,&quot;Y&quot;,
&quot;OHIO&quot;,&quot;Y&quot;,
&quot;KENTUCKY&quot;,&quot;Y&quot;,
&quot;INDIANA&quot;,&quot;Y&quot;,
&quot;DELAWARE&quot;,&quot;Y&quot;,
&quot;N&quot;)</formula>
        <label>Lead Assign (North East 2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assign_North_East_3__c</fullName>
        <formula>CASE(UPPER(State_For_Assignment_Rules__c), 
&quot;AL&quot;,&quot;Y&quot;, 
&quot;AR&quot;,&quot;Y&quot;, 
&quot;DC&quot;,&quot;Y&quot;, 
&quot;FL&quot;,&quot;Y&quot;,
&quot;GA&quot;,&quot;Y&quot;,
&quot;MD&quot;,&quot;Y&quot;, 
&quot;MS&quot;,&quot;Y&quot;, 
&quot;NC&quot;,&quot;Y&quot;,
&quot;SC&quot;,&quot;Y&quot;, 
&quot;TN&quot;,&quot;Y&quot;, 
&quot;VA&quot;,&quot;Y&quot;, 
&quot;WV&quot;,&quot;Y&quot;, 
&quot;ALABAMA&quot;,&quot;Y&quot;, 
&quot;ARKANSAS&quot;,&quot;Y&quot;, 
&quot;DISTRICT OF COLUMBIA&quot;,&quot;Y&quot;, 
&quot;FLORIDA&quot;,&quot;Y&quot;,
&quot;GEORGIA&quot;,&quot;Y&quot;,
&quot;MARYLAND&quot;,&quot;Y&quot;, 
&quot;MISSISSIPPI&quot;,&quot;Y&quot;, 
&quot;NORTH CAROLINA&quot;,&quot;Y&quot;, 
&quot;SOUTH CAROLINA&quot;,&quot;Y&quot;,
&quot;TENNESSEE&quot;,&quot;Y&quot;, 
&quot;VIRGINIA&quot;,&quot;Y&quot;, 
&quot;WEST VIRGINIA&quot;,&quot;Y&quot;, 
&quot;N&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Assign (North East 3)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assign_North_East__c</fullName>
        <formula>CASE(UPPER(State_For_Assignment_Rules__c),
&quot;NY&quot;,&quot;Y&quot;,
&quot;NJ&quot;,&quot;Y&quot;,
&quot;ON&quot;,&quot;Y&quot;,
&quot;NB&quot;,&quot;Y&quot;,
&quot;NL&quot;,&quot;Y&quot;,
&quot;NS&quot;,&quot;Y&quot;,
&quot;PE&quot;,&quot;Y&quot;,
&quot;QC&quot;,&quot;Y&quot;,
&quot;CT&quot;,&quot;Y&quot;,
&quot;MA&quot;,&quot;Y&quot;,
&quot;ME&quot;,&quot;Y&quot;,
&quot;RI&quot;,&quot;Y&quot;,
&quot;VT&quot;,&quot;Y&quot;,
&quot;NH&quot;,&quot;Y&quot;,
&quot;NEW YORK&quot;,&quot;Y&quot;,
&quot;NEW JERSEY&quot;,&quot;Y&quot;,
&quot;ONTARIO&quot;,&quot;Y&quot;,
&quot;QUEBEC&quot;,&quot;Y&quot;,
&quot;NEW BRUNSWICK&quot;,&quot;Y&quot;,
&quot;NEWFOUNDLAND&quot;,&quot;Y&quot;,
&quot;NOVA SCOTIA&quot;,&quot;Y&quot;,
&quot;PRINCE EDWARDS ISLAND&quot;,&quot;Y&quot;,
&quot;CONNECTICUT&quot;,&quot;Y&quot;,
&quot;MASSACHUSETTS&quot;,&quot;Y&quot;,
&quot;MAINE&quot;,&quot;Y&quot;,
&quot;RHOSE ISLAND&quot;,&quot;Y&quot;,
&quot;VERMONT&quot;,&quot;Y&quot;,
&quot;NEW HAMPSHIRE&quot;,&quot;Y&quot;,
&quot;N&quot;)</formula>
        <label>Lead Assign (North East 1)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assign_West_2__c</fullName>
        <formula>CASE(UPPER(State_For_Assignment_Rules__c),
&quot;TX&quot;,&quot;Y&quot;,
&quot;OK&quot;,&quot;Y&quot;, 
&quot;LA&quot;,&quot;Y&quot;,
&quot;NM&quot;,&quot;Y&quot;,
&quot;CO&quot;,&quot;Y&quot;,
&quot;UT&quot;,&quot;Y&quot;,
&quot;TEXAS&quot;,&quot;Y&quot;,
&quot;OKLAHOMA&quot;,&quot;Y&quot;, 
&quot;LOUISIANA&quot;,&quot;Y&quot;,
&quot;NEW MEXICO&quot;,&quot;Y&quot;,
&quot;COLORADO&quot;,&quot;Y&quot;,
&quot;UTAH&quot;,&quot;Y&quot;,
&quot;N&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Assign (West 2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assign_West_3__c</fullName>
        <formula>CASE(UPPER(State_For_Assignment_Rules__c),
&quot;HAWAII&quot;,&quot;Y&quot;,
&quot;IDAHO&quot;,&quot;Y&quot;,
&quot;OREGON&quot;,&quot;Y&quot;,
&quot;WASHINGTON&quot;,&quot;Y&quot;,
&quot;BRITISH COLUMBIA&quot;,&quot;Y&quot;,
&quot;ALBERTA&quot;,&quot;Y&quot;,
&quot;SASKATCHEWAN&quot;,&quot;Y&quot;,
&quot;YUKON TERRITORY&quot;,&quot;Y&quot;,
&quot;MANITOBA&quot;,&quot;Y&quot;,
&quot;CALIFORNIA&quot;,&quot;Y&quot;,
&quot;ALASKA&quot;,&quot;Y&quot;,
&quot;ARIZONA&quot;,&quot;Y&quot;,
&quot;NEVADA&quot;,&quot;Y&quot;,
&quot;HI&quot;,&quot;Y&quot;,
&quot;ID&quot;,&quot;Y&quot;,
&quot;OR&quot;,&quot;Y&quot;,
&quot;WA&quot;,&quot;Y&quot;,
&quot;BC&quot;,&quot;Y&quot;,
&quot;AB&quot;,&quot;Y&quot;,
&quot;SK&quot;,&quot;Y&quot;,
&quot;YT&quot;,&quot;Y&quot;,
&quot;MB&quot;,&quot;Y&quot;,
&quot;CA&quot;,&quot;Y&quot;,
&quot;AK&quot;,&quot;Y&quot;,
&quot;AZ&quot;,&quot;Y&quot;,
&quot;NV&quot;,&quot;Y&quot;,
&quot;N&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Assign (West 3)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assign_West__c</fullName>
        <description>The Wild West</description>
        <formula>CASE(UPPER(State_For_Assignment_Rules__c),
&quot;IL&quot;,&quot;Y&quot;,
&quot;IA&quot;,&quot;Y&quot;,
&quot;MO&quot;,&quot;Y&quot;,
&quot;MI&quot;,&quot;Y&quot;,
&quot;MN&quot;,&quot;Y&quot;,
&quot;WI&quot;,&quot;Y&quot;,
&quot;KS&quot;,&quot;Y&quot;,
&quot;MT&quot;,&quot;Y&quot;,
&quot;NE&quot;,&quot;Y&quot;,
&quot;ND&quot;,&quot;Y&quot;,
&quot;SD&quot;,&quot;Y&quot;,
&quot;WY&quot;,&quot;Y&quot;,
&quot;ILLINOIS&quot;,&quot;Y&quot;,
&quot;IOWA&quot;,&quot;Y&quot;,
&quot;MISSOURI&quot;,&quot;Y&quot;,
&quot;MICHIGAN&quot;,&quot;Y&quot;,
&quot;MINNESOTA&quot;,&quot;Y&quot;,
&quot;WISCONSIN&quot;,&quot;Y&quot;,
&quot;KANSAS&quot;,&quot;Y&quot;,
&quot;MONTANA&quot;,&quot;Y&quot;,
&quot;NEBRASKA&quot;,&quot;Y&quot;,
&quot;NORTH DAKOTA&quot;,&quot;Y&quot;,
&quot;SOUTH DAKOTA&quot;,&quot;Y&quot;,
&quot;WYOMING&quot;,&quot;Y&quot;,
&quot;N&quot;)</formula>
        <label>Lead Assign (West 1)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Round_Robin__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Lead_Field_Regions__c</fullName>
        <label>Lead Field Regions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Round Robin</label>
</CustomObject>

src/classes/TestLeadFillRoundRobin.cls
@isTest
private class TestLeadFillRoundRobin {

	static testMethod void myUnitTest() {
		
		List<Lead_Round_Robin__c> lrrInsert = new List<Lead_Round_Robin__c>();
		Lead_Round_Robin__c lrr1 =  new Lead_Round_Robin__c(name = 'East RR', Lead_Field_Regions__c = 'Lead_Assign_North_East__c;Lead_Assign_North_East_2__c;Lead_Assign_North_East_3__c', round_robin_number__c = 0);
		lrrInsert.add(lrr1);
		Lead_Round_Robin__c lrr2 =  new Lead_Round_Robin__c(name = 'West RR', Lead_Field_Regions__c = 'Lead_Assign_West__c;Lead_Assign_West_2__c;Lead_Assign_West_3__c', round_robin_number__c = 0);
		lrrInsert.add(lrr2);
		
		insert lrrInsert;
		
		List<Account> acctInsert = new List<Account>();
		
		Account acct1 = new Account(name = 'New Account');
		acctInsert.add(acct1);
		
		insert acctInsert;
		
		List<Lead> leadInsert = new List<Lead>();
		
		
		Lead lead1 = new Lead(firstName = 'first', lastName = 'last', company = 'VMTurbo', state = 'Massachusetts', country = 'United States', leadSource = 'Tradeshow', email = 'first.last@vmturbo.com');
		leadInsert.add(lead1);
		Lead lead2 = new Lead(firstName = 'first', lastName = 'last2', company = 'VMTurbo', state = 'New Hampshire', country = 'United States', leadSource = 'Tradeshow', email = 'first.last2@vmturbo.com');
		leadInsert.add(lead2);
		Lead lead3 = new Lead(firstName = 'first', lastName = 'last3', company = 'VMTurbo', account__c = acct1.id, state = 'Massachusetts', country = 'United States', leadSource = 'Tradeshow', email = 'first.last3@vmturbo.com');
		leadInsert.add(lead3);
		Lead lead4 = new Lead(firstName = 'first', lastName = 'last4', company = 'VMTurbo', state = 'Oregon', country = 'United States', leadSource = 'Tradeshow', email = 'first.last4@vmturbo.com');
		leadInsert.add(lead4);
		Lead lead5 = new Lead(firstName = 'first', lastName = 'last5', company = 'VMTurbo', state = 'California', country = 'United States', leadSource = 'Tradeshow', email = 'first.last5@vmturbo.com');
		leadInsert.add(lead5);
		
		insert leadInsert;
		
		List<Lead> afterInsert = [select id, round_robin_number__c, ownerId, account__c from Lead where id =: lead1.id or id =: lead2.id or id =: lead3.id or id =: lead4.id or id =: lead5.id];
		double firstNum;
		double secondNum;
		double thirdNum;
		double fourthNum;
		for (Lead l : afterInsert) {
			
			if (l.id == lead1.id) {
				system.assert(l.round_robin_number__c >= 0.0);
				firstNum = l.round_robin_number__c;
			} else if (l.id == lead2.id) {
				system.assert(l.round_robin_number__c >= 0.0);
				secondNum = l.round_robin_number__c;
			} else if (l.id == lead3.id) {
				system.assertEquals(l.round_robin_number__c,null);
			} else if (l.id == lead4.id) {
				system.assert(l.round_robin_number__c >= 0.0);
				thirdNum = l.round_robin_number__c;
			} else if (l.id == lead5.id) {
				system.assert(l.round_robin_number__c >= 0.0);
				fourthNum = l.round_robin_number__c;
			}
		}
		
		system.assert(firstNum != secondNum);
		system.assert(thirdNum != fourthNum);
		
		List<Lead_Round_Robin__c> lrrResults = Lead_Round_Robin__c.getAll().values();
		for (Lead_Round_Robin__c lrr : lrrResults) {
			if (lrr.name == 'East RR') {
				system.assertEquals(lrr.Round_Robin_Number__c,2);
			} else if (lrr.name == 'West RR'){
				system.assertEquals(lrr.Round_Robin_Number__c,2);
			}
		}
		
		List<Lead> leadInsert2 = new List<Lead>();
		Lead lead6 = new Lead(firstName = 'first', lastName = 'last6', company = 'VMTurbo', state = 'New Hampshire', country = 'United States', leadSource = 'Tradeshow', email = 'first.last6@vmturbo.com');
		leadInsert2.add(lead6);
		Lead lead7 = new Lead(firstName = 'first', lastName = 'last7', company = 'VMTurbo', state = 'California', country = 'United States', leadSource = 'Tradeshow', email = 'first.last7@vmturbo.com');
		leadInsert2.add(lead7);
		
		insert leadInsert2;
		
		afterInsert = [select id, round_robin_number__c, ownerId, account__c from Lead where id =: lead6.id or id =: lead7.id];
		
		for (Lead l : afterInsert) {
			if (l.id == lead6.id) {
				system.assert(l.round_robin_number__c == 2);
			} else if (l.id == lead7.id) {
				system.assert(l.round_robin_number__c == 2);
			}
		}
		
		lrrResults = Lead_Round_Robin__c.getAll().values();
		for (Lead_Round_Robin__c lrr : lrrResults) {
			if (lrr.name == 'East RR') {
				system.assertEquals(lrr.Round_Robin_Number__c,3);
			} else {
				system.assertEquals(lrr.Round_Robin_Number__c,3);
			}
		}
		
	}


}