src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Auto_Number__c.object
<CustomObject>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Auto Number</label>
    <nameField>
        <label>Lead Auto Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testSetActivityTypeText.cls
// Created by: Eustace Consulting [www.eustaceconsulting.com][Developer: Jennifer Blair]
// Description: This class tests TaskSetActivityTypeText.trigger
@isTest
private class testSetActivityTypeText {

    static testMethod void myUnitTest() {
    	Lead_Auto_Number__c lan = new Lead_Auto_Number__c(round_robin_number__c = 0);
        insert lan;    	
    	
        //Create Account
        Account acct1 = new Account(Name = 'Innitech');
        insert acct1;
        
        //Create Lead
        Lead lead1 = new Lead(Account__c = acct1.id, FirstName = 'Bob', LastName = 'Jones', Company = 'Innitech', LeadSource = 'Unknown');
        insert lead1;
        
        //Create completed Task under Lead
        Task tsk1 = new Task(Status='Completed', Subject ='Call', Type = 'Call', ActivityDate=Date.Today().addDays(-10), WhoId=lead1.id);
        insert tsk1;
        
        //verify text field set
        tsk1 = [select id, Activity_Type_workflow__c from Task where id =: tsk1.id];
        system.assertEquals(tsk1.Activity_Type_workflow__c, 'Call');
    }
}