src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <label>Partner Manager1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
            <errorMessage>The Partner Manager needs to be in a Channel Manager role</errorMessage>
            <filterItems>
                <field>User.Team__c</field>
                <operation>equals</operation>
                <value>Xccelerators</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Channel Manager&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Director of Channels&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Luis DaSilva</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Greg Beale</value>
            </filterItems>
            <infoMessage>Filter calls for users in the Channel Manager role</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Partner_Manager__c</fullName>
        <label>Registration Partner Manager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executive</fullName>
                    <label>a_Executive</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <label>a_Finance</label>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                    <label>a_Marketing</label>
                </value>
                <value>
                    <fullName>Recruiting</fullName>
                    <label>a_Recruiting</label>
                </value>
                <value>
                    <fullName>Sales Enablement</fullName>
                    <label>a_Sales Enablement</label>
                </value>
                <value>
                    <fullName>APAC Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial France</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise France</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise Germany</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise SDR</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise Unallocated</fullName>
                </value>
                <value>
                    <fullName>Global Accounts International</fullName>
                </value>
                <value>
                    <fullName>Global Accounts US</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>No Team Assigned</fullName>
                    <default>true</default>
                    <label>No Team Assigned</label>
                </value>
                <value>
                    <fullName>Candy Time</fullName>
                    <label>p_Candy Time</label>
                </value>
                <value>
                    <fullName>Technical Account Managers</fullName>
                    <label>p_Technical Account Managers</label>
                </value>
                <value>
                    <fullName>The Methodology Commercial</fullName>
                </value>
                <value>
                    <fullName>The Pack Commercial</fullName>
                </value>
                <value>
                    <fullName>US Commercial</fullName>
                </value>
                <value>
                    <fullName>US Commercial East</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 1</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 2</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 3</fullName>
                </value>
                <value>
                    <fullName>US Commercial East SDR</fullName>
                </value>
                <value>
                    <fullName>US Commercial Unallocated</fullName>
                </value>
                <value>
                    <fullName>US Commercial West</fullName>
                </value>
                <value>
                    <fullName>Xccelerators</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/VartopiaDRS__Registration__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Manager_Name__c</fullName>
        <formula>Partner_Manager__r.Full_Name__c</formula>
        <label>Partner Manager Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Vendor_Status__c</fullName>
        <label>Vendor Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Closed-Won</fullName>
                </value>
                <value>
                    <fullName>Closed-Lost</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>Reg{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRegFillPartnerManager.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestRegFillPartnerManager {

    static testMethod void myUnitTest() {
        
		List<User> partnerMgrs = [select id, name from User where team__c = 'Xccelerators' and isActive = true limit 2];
        
        Account acct = new Account(name = 'test Acct');
        insert acct;
        
        Opportunity channelOpp = new Opportunity(name = 'test Opp', amount = 10000, stageName = 'Identify', closeDate = date.today().addDays(30), type = 'New', accountId = acct.id);
        insert channelOpp;
        
        VartopiaDRS__Registration__c vrc = new VartopiaDRS__Registration__c ( VartopiaDRS__Vendor_Status__c = 'Submitted', VartopiaDRS__Opportunity__c = channelOpp.id, VartopiaDRS__Date_Submitted__c = date.today(), Partner_Manager__c = partnerMgrs.get(0).id);
        insert vrc;
        
        Opportunity afterTestOpp = [select id, Partner_Manager__c, Registration_Partner_Manager__c from Opportunity where id =: channelOpp.id];
        system.assert(afterTestOpp.Partner_Manager__c == partnerMgrs.get(0).id);
        system.assert(afterTestOpp.Registration_Partner_Manager__c == partnerMgrs.get(0).name);
        
        VartopiaDRS__Registration__c vrcUpdate = [select id, Partner_Manager__c, Partner_Manager_Name__c from VartopiaDRS__Registration__c where id =: vrc.id];
        vrcUpdate.Partner_Manager__c = partnerMgrs.get(1).id;
        update vrcUpdate;
        
        afterTestOpp = [select id, Partner_Manager__c, Registration_Partner_Manager__c from Opportunity where id =: channelOpp.id];
        system.assertEquals(afterTestOpp.Partner_Manager__c,partnerMgrs.get(1).id);
        system.assertEquals(afterTestOPp.Registration_Partner_Manager__c,partnerMgrs.get(1).name);
    }
}