src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AE_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wi__Share_to_WI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Share to WI</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DealRegq1__c</fullName>
        <description>First Question on Partner deal reg</description>
        <label>Registration Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <description>WI Partner - Joint/Accelerated or Incremental</description>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incremental</fullName>
                </value>
                <value>
                    <fullName>Joint/Accelerated</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Cisco</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>wi__Associated_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wi__Share_to_WI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Share to WI</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cisco_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cisco Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DealRegq1__c</fullName>
        <description>WI Question from the Deal Reg Lead</description>
        <label>Registration Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <description>Deal type for Registrations</description>
        <inlineHelpText>Deal type for Registrations. Select &quot;Direct&quot; if this deal does not have any partner involvement.</inlineHelpText>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Deal_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage_Change_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Stage Change Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_CPU_Sockets__c</fullName>
        <description>The number of CPU Sockets (or processors) in the contact&apos;s environment. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</description>
        <inlineHelpText>The number of CPU Sockets (or processors) related to this opportunity. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</inlineHelpText>
        <label># of CPU Sockets [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Virtual_Machines__c</fullName>
        <description>Number of Virtual Machines related to this opportunity.</description>
        <inlineHelpText>Number of Virtual Machines related to this opportunity.</inlineHelpText>
        <label># of Virtual Machines [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>wi__Associated_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wi__Share_to_WI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Share to WI</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Deal_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Incremental</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated</fullName>
    </customValue>
    <customValue>
        <fullName>Fulfillment</fullName>
    </customValue>
    <customValue>
        <fullName>Cisco</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated-Revived</fullName>
        <isActive>false</isActive>
        <label>Joint/Accelerated-Revived</label>
    </customValue>
    <description>Registration Deal Type</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

src/classes/TestLeadAssignDealReg.cls
@isTest(SeeAllData=false)
public class TestLeadAssignDealReg {
    static testMethod void myUnitTest(){
        Test.startTest();
        LeadAssignDealRegCL[] leadassigndealreg = new List<LeadAssignDealRegCL>();
        LeadAssignDealRegCL.LeadAssignFunc1();
        LeadAssignDealRegCL.LeadAssignFunc2();
        LeadAssignDealRegCL.LeadAssignFunc3();
        LeadAssignDealRegCL.LeadAssignFunc4();
        LeadAssignDealRegCL.LeadAssignFunc5();
        LeadAssignDealRegCL.LeadAssignFunc6();
        LeadAssignDealRegCL.LeadAssignFunc7();
        LeadAssignDealRegCL.LeadAssignFunc8();
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        UserRole ur1 = new UserRole(Name = 'Customer Account Manager');
        UserRole ur2 = new UserRole(Name = 'Sales Engineer');
        insert ur1;
        insert ur2;
        
        User user1 = new User(Alias = 'standt1', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser12@testor.com', UserRoleId = ur1.Id);
        
        User user2 = new User(Alias = 'standt2', Email='standarduser2@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing2', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@testor.com', UserRoleId = ur2.Id);     
       
        System.runAs(user1) {      
        List<Lead> leadList = new List<Lead>();
        List<Account> acctInsert = new List<Account>(); 
        List<Opportunity> oppList = new List<Opportunity>();
        Map<id,Opportunity> oppMap = new Map<id,Opportunity>();
         
        Account a1 = new Account(name = 'Test Acct 1',Website='http://www.testcompany1.com',AE_Rep__c=user1.id,wi__Share_to_WI__c=true);
        acctInsert.add(a1);
        Account a2 = new Account(name = 'Test Acct 2',Website='http://www.testcompany2.com',AE_Rep__c=user2.id);
        acctInsert.add(a2); 
        Account a3 = new Account(name = 'Test Acct 3',Website='http://www.testcompany3.com');
        acctInsert.add(a3);
        insert acctInsert;

        List<Account> accLst = [select id,name from Account where id=:a1.Id or id=:a2.Id];  
                    
        Opportunity opp1 = new Opportunity(name = 'test opp 1',amount = 10000, type = 'New',of_CPU_Sockets__c= 2,of_Virtual_Machines__c=2,closeDate = date.today().addDays(30), StageName = 'New', Cisco_Opportunity__c=False,Stage_Change_Date__c=Date.valueof('2018-02-12'),AccountId = a2.Id);
        //insert opp1;
        Opportunity opp2 = new Opportunity(name = 'test opp 2',amount = 10000, type = 'Upsell',of_CPU_Sockets__c=2,of_Virtual_Machines__c=2,closeDate = date.today().addDays(30), StageName = 'Upsell',Cisco_Opportunity__c=False,Stage_Change_Date__c=Date.valueof('2018-03-23'),AccountId = a2.Id);
       //insert opp2;
        Opportunity opp3 = new Opportunity(name = 'test opp 3',amount = 10000, type = 'New',of_CPU_Sockets__c= 2,of_Virtual_Machines__c=2,closeDate = date.today().addDays(30), StageName = 'New', Cisco_Opportunity__c=False,Stage_Change_Date__c=Date.valueof('2018-02-12'),AccountId = a3.Id);
        
        oppList.add(opp1); 
        oppList.add(opp2);
        oppList.add(opp3);    
        insert oppList;
        
        List<Opportunity> oppLst = new List<Opportunity>([select id,name,amount,type,closeDate,StageName,Stage_Change_Date__c,IsClosed,IsWon,AccountId,DealRegq1__c from opportunity]);
                     
        Lead l1 = new Lead(firstName = 'Lead1',lastName = 'One', company = 'Test Acct 1', Website='http://www.testcompany1.com',Deal_Type__c = 'Incremental',wi__Share_to_WI__c = true,wi__Associated_Partner__c=a1.Id);
        leadList.add(l1);
   
        Lead l2 = new Lead(firstName = 'Lead2', lastName = 'Two',company = 'Test Acct 2', Website='http://www.testcompany2.com',wi__Share_to_WI__c = true,wi__Associated_Partner__c=a1.Id);    
        leadList.add(l2);
            
        Lead l3 = new Lead(firstName = 'Lead3', lastName = 'Three',company = 'Test Acct 3', Website='http://www.testcompany3.com',wi__Share_to_WI__c = false);    
        leadList.add(l3);    
        insert leadList;
    
        List<Lead> leadlst = [select id,company,Account__c,website,DealRegq1__c from Lead Where id=: l1.Id or id=: l2.Id];             
            
          Test.stopTest();
        
        }
    }
}