src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Socket_Count__c</fullName>
        <label>Socket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VMT_Account_Score__c</fullName>
        <description>Target accounts get min of 500
Make given industry 1000 to run a campaign (max 1500 to not mess up other rankings - Prospects get 2000 and ~400 or so can come from company size, last call, title, and other), or use &quot;Include in Marketo&quot; field on lead record to toggle campaign (adds extra points to score)</description>
        <formula>IF(Socket_Count__c+VM_Count__c&gt;0,MAX(Socket_Count__c,VM_Count__c/15),
CASE(Industry_clean_text__c, 
&quot;Biotech &amp; Pharma&quot;,0.3,
&quot;Construction &amp; Engineering&quot;,0.25,
&quot;Education&quot;,0.25,
&quot;Energy &amp; Utilities&quot;,0.3,
&quot;Financial Services&quot;,0.55,
&quot;Food &amp; Beverage&quot;,0.2,
&quot;Government&quot;,0.05,
&quot;Healthcare&quot;,0.4,
&quot;Insurance&quot;,0.45,
&quot;Manufacturing &amp; Industrials&quot;,0.1,
&quot;Nonprofit&quot;,0.05,
&quot;Professional Services: Legal&quot;,0.4,
&quot;Professional Services: Other&quot;,0.4,
&quot;Retail &amp; Consumer Products&quot;,0.2,
&quot;Service Providers&quot;,1,
&quot;Tech: Internet&quot;,1,
&quot;Tech: All Other&quot;,0.6,
&quot;Tech: Software&quot;,1,
&quot;Telecom &amp; Media&quot;,0.5,
&quot;Transportation &amp; Logistics&quot;,0.1,
&quot;Travel &amp; Leisure&quot;,0.1,
&quot;Wholesale&quot;,0.1,
&quot;Other&quot;,0.1,
0.2)*NumberOfEmployees)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VMT Account Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Auto_Number__c.object
<CustomObject>
    <fields>
        <fullName>Round_Robin_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Round Robin Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Auto Number</label>
    <nameField>
        <label>Lead Auto Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VMT_Account_Score__c.object
<CustomObject>
    <label>VMT Opportunity Account Score</label>
    <nameField>
        <label>VMT Account Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VMT Opportunity Account Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAccountWrapper.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAccountWrapper {

    static testMethod void myUnitTest() {
        
        lead_auto_number__c leadnum = new lead_auto_number__c(round_robin_number__c = 0);
		insert leadnum;
        
        AccountWrapper[] acctList = new List<AccountWrapper>();
        
        List<Account> insertAccts = new List<Account>();
        Account acct1 = new Account(name = 'United Airlines', socket_count__c = 1000);
        Account acct2 = new Account(name = 'Delta Airlines', socket_count__c = 1500);
        Account acct3 = new Account(name = 'Jet Blue Airlines', socket_count__c = 500);
        insertAccts.add(acct1);
        insertAccts.add(acct2);
        insertAccts.add(acct3);
        
        insert insertAccts;
        
        acct1 = [select id, name, VMT_Account_Score__c from Account where id =:acct1.id];
        acct2 = [select id, name, VMT_Account_Score__c from Account where id =:acct2.id];
        acct3 = [select id, name, VMT_Account_Score__c from Account where id =:acct3.id];
        
        acctList.add( new AccountWrapper(acct1));
        acctList.add( new AccountWrapper(acct2));
        acctList.add( new AccountWrapper(acct3));
        
        acctList.sort();

        system.assertEquals('Jet Blue Airlines', acctList[2].acct.name);
        system.assertEquals('United Airlines', acctList[1].acct.name);
        system.assertEquals('Delta Airlines', acctList[0].acct.name);
        
    }
}