src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Green_Circle_Registration_Date__c</fullName>
        <description>Date this company joined the Green Circle</description>
        <label>Green Circle Last Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <label>Partner Manager1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>RIGHT(Status_Ordered__c,LEN(Status_Ordered__c)-4)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Green_Circle_Registration_Date__c</fullName>
        <label>Green Circle Last Activity Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_Role_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Count of Contact Roles attached to the opportunity</description>
        <label>Number of Key Stakeholders Engaged</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <description>Deal type for Registrations</description>
        <inlineHelpText>Deal type for Registrations. Select &quot;Direct&quot; if this deal does not have any partner involvement.</inlineHelpText>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Deal_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Demo_Contact_Safe_ID__c</fullName>
        <label>First Demo Contact Safe ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Highest_Vendor_Status__c</fullName>
        <description>Filled by batch (BatchFillHighestVendorStatus.cls)</description>
        <label>Highest Vendor Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
            <errorMessage>The Partner Manager needs to be in a Channel Manager role</errorMessage>
            <filterItems>
                <field>User.Team__c</field>
                <operation>equals</operation>
                <value>Xccelerators</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Channel Manager&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Director of Channels&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Luis DaSilva</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Greg Beale</value>
            </filterItems>
            <infoMessage>Filter calls for users in the Channel Manager role</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Recruiting_Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Manual_Last_Modified_Date__c</fullName>
        <label>Manual Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Recruiting_Spec__c</fullName>
        <label>Recruiting Spec</label>
        <referenceTo>Recruiting_Spec__c</referenceTo>
        <relationshipLabel>Recruiting Candidates</relationshipLabel>
        <relationshipName>Recruiting_Candidates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_To__c</fullName>
        <formula>IF(ISBLANK(Recruiting_Spec__r.Report_To__c),Manual_Report_To__c,Recruiting_Spec__r.Report_To__c)</formula>
        <label>Report To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Applicant Submitted</fullName>
                    <default>true</default>
                    <label>1 - Applicant Submitted</label>
                </value>
                <value>
                    <fullName>2 - Initial Outreach Completed</fullName>
                </value>
                <value>
                    <fullName>3 - Screen 1 Completed</fullName>
                </value>
                <value>
                    <fullName>3a - R&amp;D Test Administered</fullName>
                </value>
                <value>
                    <fullName>3b - Screen 2 Completed</fullName>
                </value>
                <value>
                    <fullName>4 - Onsite Interview 1 Completed</fullName>
                </value>
                <value>
                    <fullName>5 - Onsite Interview 2 Completed</fullName>
                </value>
                <value>
                    <fullName>6 - Offer Extended</fullName>
                </value>
                <value>
                    <fullName>7 - Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Did Not Pass - VMT Rejected</fullName>
                </value>
                <value>
                    <fullName>Did Not Pass - Candidate Withdrew</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recruiting Candidate</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruiting Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recruiting_Spec__c.object
<CustomObject>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <label>Hiring Manager</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_To__c</fullName>
        <label>Report To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Open_Date__c &gt; TODAY(),&quot;Planned&quot;,
IF( Number_of_Hires_to_Target__c &lt;=0,&quot;Closed - Filled&quot;,
IF(Close_Date__c &lt;= TODAY(),&quot;Closed - Expired&quot;,
IF(AND( Number_of_Hires_to_Target__c &gt;0,   Start_Date__c &gt;= TODAY()),&quot;Open - On Schedule&quot;,
IF(AND( Number_of_Hires_to_Target__c &gt;0, Start_Date__c &lt; TODAY()),&quot;Open - Overdue&quot;,&quot;Open - On Schedule&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Hires__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Target Hires</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Recruiting Spec</label>
    <nameField>
        <label>Recruiting Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruiting Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VartopiaDRS__Registration__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incremental</fullName>
                </value>
                <value>
                    <fullName>Joint/Accelerated</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Vendor_Status__c</fullName>
        <label>Vendor Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Closed-Won</fullName>
                </value>
                <value>
                    <fullName>Closed-Lost</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>Reg{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Deal_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Incremental</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated</fullName>
    </customValue>
    <customValue>
        <fullName>Fulfillment</fullName>
    </customValue>
    <customValue>
        <fullName>Cisco</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated-Revived</fullName>
        <isActive>false</isActive>
        <label>Joint/Accelerated-Revived</label>
    </customValue>
    <description>Registration Deal Type</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

src/classes/TestFillHighestRegistrationStatus.cls
@isTest
private class TestFillHighestRegistrationStatus {

    static testMethod void myUnitTest() {
        
        List<Opportunity> insertOpps = new List<Opportunity>();
        List<VartopiaDRS__Registration__c> insertVRs = new List<VartopiaDRS__Registration__c>();
        List<Contact> conInsert = new List<Contact>();
    	List<OpportunityContactRole> oppCRInsert = new List<OpportunityContactRole>();
    	List<Task> tskInsert = new List<Task>();
        
        Account acct = new Account(name = 'Some Company');
        insert acct;
        
        //Create Contacts
    	Contact con1 = new Contact(FirstName = 'Contact', LastName = 'One', AccountId = acct.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con1);
    	Contact con2 = new Contact(FirstName = 'Contact', LastName = 'Two', AccountId = acct.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con2);
    	Contact con3 = new Contact(FirstName = 'Contact', LastName = 'Three', AccountId = acct.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con3);
    	Contact con4 = new Contact(FirstName = 'Contact', LastName = 'Four', AccountId = acct.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con4);
    	Contact con5 = new Contact(FirstName = 'Contact', LastName = 'Five', AccountId = acct.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con5);
    	
    	insert conInsert;
        
        Opportunity opp1 = new Opportunity(name = 'Test Opp1', amount = 100, stageName = 'Closed Won', closeDate = date.today(), type = 'New', accountId = acct.id, highest_vendor_status__c = 'Closed-Won');
        insertOpps.add(opp1);
        Opportunity opp2 = new Opportunity(name = 'Test Opp2', amount = 100, stageName = 'Commit', closeDate = date.today(), type = 'Upsell', accountId = acct.id, highest_vendor_status__c = 'Closed-Lost');
        insertOpps.add(opp2);
        Opportunity opp3 = new Opportunity(name = 'Test Opp3', amount = 100, stageName = 'Pipeline', closeDate = date.today().addDays(30), type = 'Upsell', accountId = acct.id, highest_vendor_status__c = 'Approved');
        insertOpps.add(opp3);
        Opportunity opp4 = new Opportunity(name = 'Test Opp4', amount = 100, stageName = 'Pipeline', closeDate = date.today().addDays(30), type = 'Upsell', accountId = acct.id, highest_vendor_status__c = 'Expired');
        insertOpps.add(opp4);
        Opportunity opp5 = new Opportunity(name = 'Test Opp5', amount = 100, stageName = 'Identify', closeDate = date.today().addDays(30), type = 'Upsell', accountId = acct.id, highest_vendor_status__c = 'Submitted');
        insertOpps.add(opp5);
        Opportunity opp6 = new Opportunity(name = 'Test Opp6', amount = 100, stageName = 'Identify', closeDate = date.today().addDays(30), type = 'Upsell', accountId = acct.id, highest_vendor_status__c = 'Returned');
        insertOpps.add(opp6);
        Opportunity opp7 = new Opportunity(name = 'Test Opp7', amount = 100, stageName = 'Identify', closeDate = date.today().addDays(30), type = 'Upsell', accountId = acct.id);
        insertOpps.add(opp7);
        
        insert insertOpps;
        
        //Create Opportunity Contact Roles
		OpportunityContactRole oppCR1 = new OpportunityContactRole(ContactId = con1.id, OpportunityId = opp1.id, Role = 'Manager', IsPrimary = true);
		oppCRInsert.add(oppCR1);
		OpportunityContactRole oppCR2 = new OpportunityContactRole(ContactId = con2.id, OpportunityId = opp1.id, Role = 'Decision Maker');
		oppCRInsert.add(oppCR2);
		OpportunityContactRole oppCR3 = new OpportunityContactRole(ContactId = con3.id, OpportunityId = opp1.id, Role = 'Influencer');
		oppCRInsert.add(oppCR3);
		OpportunityContactRole oppCR4 = new OpportunityContactRole(ContactId = con4.id, OpportunityId = opp1.id, Role = 'Non-Responsive');
		oppCRInsert.add(oppCR4);
		OpportunityContactRole oppCR5 = new OpportunityContactRole(ContactId = con5.id, OpportunityId = opp2.id, Role = 'VMT Champion', IsPrimary = true);
		oppCRInsert.add(oppCR5);
		
		insert oppCRInsert;
        

        VartopiaDRS__Registration__c vr2 = new VartopiaDRS__Registration__c(VartopiaDRS__Vendor_Status__c = 'Closed-Won', Deal_type__c = 'Incremental', VartopiaDRS__Opportunity__c = opp2.id);
        insertVRs.add(vr2);
        VartopiaDRS__Registration__c vr3 = new VartopiaDRS__Registration__c(VartopiaDRS__Vendor_Status__c = 'Closed-Lost', Deal_type__c = 'Incremental', VartopiaDRS__Opportunity__c = opp3.id);
        insertVRs.add(vr3);
        VartopiaDRS__Registration__c vr4 = new VartopiaDRS__Registration__c(VartopiaDRS__Vendor_Status__c = 'Approved', Deal_type__c = 'Incremental', VartopiaDRS__Opportunity__c = opp4.id);
        insertVRs.add(vr4);
        VartopiaDRS__Registration__c vr5 = new VartopiaDRS__Registration__c(VartopiaDRS__Vendor_Status__c = 'Approved', Deal_type__c = 'Incremental', VartopiaDRS__Opportunity__c = opp5.id);
        insertVRs.add(vr5);
        VartopiaDRS__Registration__c vr6 = new VartopiaDRS__Registration__c(VartopiaDRS__Vendor_Status__c = 'Approved', Deal_type__c = 'Incremental', VartopiaDRS__Opportunity__c = opp6.id);
        insertVRs.add(vr6);
        VartopiaDRS__Registration__c vr7 = new VartopiaDRS__Registration__c(VartopiaDRS__Vendor_Status__c = 'Submitted', VartopiaDRS__Opportunity__c = opp7.id);
        insertVRs.add(vr7);
		VartopiaDRS__Registration__c vr8 = new VartopiaDRS__Registration__c(VartopiaDRS__Vendor_Status__c = 'Approved', Deal_type__c = 'Incremental', VartopiaDRS__Opportunity__c = opp7.id);
        insertVRs.add(vr8);

        insert insertVRs;
        
		//Create Demo Tasks
		Task tsk1 = new Task(Status='Not Started', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today().addDays(-10), WhatId=opp1.id, WhoId = Con1.id, CPU_Sockets__c = 10, Virtual_Machines_VMs__c = 100, First_Demo_Scheduled__c = true, First_Demo__c = false);
        tskInsert.add(tsk1);
        Task tsk2 = new Task(Status='Not Started', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today().addDays(-5), WhatId=opp2.id, WhoId = con2.id, CPU_Sockets__c = 20, Virtual_Machines_VMs__c = 150, First_Demo_Scheduled__c = true);
        tskInsert.add(tsk2);
        Task tsk3 = new Task(Status='Completed', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today(), WhatId=opp2.id, WhoId = con3.id, CPU_Sockets__c = 20, Virtual_Machines_VMs__c = 150);
        tskInsert.add(tsk3);
        Task tsk4 = new Task(Status='Completed', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today(), WhatId=opp3.id, CPU_Sockets__c = 20, Virtual_Machines_VMs__c = 150);
        tskInsert.add(tsk4);
        
        insert tskInsert;
        
        //recruiting candidate initialization
/*
        Recruiting_Spec__c rs = new Recruiting_Spec__c(name = 'BDR US - Mar 2015', Report_To__c = 'Justin Chang', target_hires__c = 20, hiring_manager__c = 'Tim Daniels');
        insert rs;
        Recruiting_Candidate__c rc = new Recruiting_Candidate__c(Status__c = '1 - Application Submitted', Recruiting_Spec__c = rs.id);
        DateTime useDate = DateTime.now().addDays(-40);
        rc.Manual_Last_Modified_Date__c = useDate;
        insert rc;
*/
        
        Test.startTest();
        BatchFillHighestRegistrationStatus b = new BatchFillHighestRegistrationStatus();
        b.query = 'SELECT id, name, highest_vendor_status__c, Contact_Role_Count__c, Type, First_Demo_Contact_Safe_Id__c FROM Opportunity WHERE id = \'' + opp1.id + '\' OR id = \'' + opp2.id + '\' OR id = \'' + opp3.id + '\' OR id = \'' + opp4.id + '\' OR id = \'' + opp5.id + '\' OR id = \'' + opp6.id + '\' OR id = \'' + opp7.id + '\'';
        ID batchprocessid = Database.executeBatch(b);
        Test.stopTest();
        
        
        Map<Id,Opportunity> afterOpps = new Map<Id,Opportunity>([select id, highest_vendor_status__c, Partner_Manager__c, Contact_Role_Count__c, first_demo_contact_safe_id__c from Opportunity where (id =: opp1.id or id =: opp2.id or id =: opp3.id or id =: opp4.id or id =: opp5.id or id =:opp6.id or id =:opp7.id)]);
        
        Opportunity afterOpp = afterOpps.get(opp1.id);
        system.assertEquals(afterOpp.highest_vendor_status__c,'Closed-Won');
        system.assertEquals(afterOpp.Contact_Role_Count__c,4);
		system.assertEquals(afterOpp.First_Demo_Contact_Safe_Id__c,con1.id);
        Opportunity afterOpp7 = afterOpps.get(opp7.id);
        system.assertEquals(afterOpp7.highest_vendor_status__c,'Approved');
        Opportunity afterOpp2 = afterOpps.get(opp2.id);
        system.assertEquals(afterOpp2.highest_vendor_status__c,'Closed-Won');
        system.assertEquals(afterOpp2.Contact_Role_Count__c,1);
		system.assertEquals(afterOpp2.First_Demo_Contact_Safe_Id__c,con2.id);
        Opportunity afterOpp3 = afterOpps.get(opp3.id);
        system.assertEquals(afterOpp3.highest_vendor_status__c,'Approved');
        system.assertEquals(afterOpp3.Contact_Role_Count__c,0);
		system.assertEquals(afterOpp3.First_Demo_Contact_Safe_Id__c,null);
        Opportunity afterOpp4 = afterOpps.get(opp4.id);
        system.assertEquals(afterOpp4.highest_vendor_status__c,'Approved');
        Opportunity afterOpp5 = afterOpps.get(opp5.id);
        system.assertEquals(afterOpp5.highest_vendor_status__c,'Approved');
        Opportunity afterOpp6 = afterOpps.get(opp6.id);
        system.assertEquals(afterOpp6.highest_vendor_status__c,'Approved');

       	// test code for recruiting candidate
//        Recruiting_Candidate__c rc1 = [select id, Status__c from Recruiting_Candidate__c where id =: rc.id];
//        system.assertEquals(rc1.Status__c,'Non-Responsive'); 
        
    }
}