src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <inlineHelpText>Name of the opportunity owner&apos;s team.  This is the team that the deal is assigned to for reporting (the team that is actually driving the deal, regardless of whether or not it goes through the channel)</inlineHelpText>
        <label>Owner Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC Enterprise</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 1</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 2</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 3</fullName>
                </value>
                <value>
                    <fullName>US Commercial West 1</fullName>
                </value>
                <value>
                    <fullName>US Commercial West 2</fullName>
                </value>
                <value>
                    <fullName>US Commercial West 3</fullName>
                </value>
                <value>
                    <fullName>Enterprise East 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise East 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise East 3</fullName>
                </value>
                <value>
                    <fullName>Enterprise Central 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise Central 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise Central 3</fullName>
                </value>
                <value>
                    <fullName>Enterprise West 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise West 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise SDR</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial France</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise France</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise SDR</fullName>
                </value>
                <value>
                    <fullName>Global Accounts International</fullName>
                </value>
                <value>
                    <fullName>Global Accounts US</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>Candy Time</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Xccelerators</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Executive</fullName>
                    <label>a_Executive</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <label>a_Finance</label>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                    <label>a_Marketing</label>
                </value>
                <value>
                    <fullName>Recruiting</fullName>
                    <label>a_Recruiting</label>
                </value>
                <value>
                    <fullName>Sales Enablement</fullName>
                    <label>a_Sales Enablement</label>
                </value>
                <value>
                    <fullName>APAC Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial France</fullName>
                </value>
                <value>
                    <fullName>EMEA Commercial UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise France</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise Germany</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise SDR</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise UK</fullName>
                </value>
                <value>
                    <fullName>EMEA Enterprise Unallocated</fullName>
                </value>
                <value>
                    <fullName>Global Accounts International</fullName>
                </value>
                <value>
                    <fullName>Global Accounts US</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>No Team Assigned</fullName>
                    <default>true</default>
                    <label>No Team Assigned</label>
                </value>
                <value>
                    <fullName>Candy Time</fullName>
                    <label>p_Candy Time</label>
                </value>
                <value>
                    <fullName>Technical Account Managers</fullName>
                    <label>p_Technical Account Managers</label>
                </value>
                <value>
                    <fullName>The Methodology Commercial</fullName>
                </value>
                <value>
                    <fullName>The Pack Commercial</fullName>
                </value>
                <value>
                    <fullName>US Commercial</fullName>
                </value>
                <value>
                    <fullName>US Commercial East</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 1</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 2</fullName>
                </value>
                <value>
                    <fullName>US Commercial East 3</fullName>
                </value>
                <value>
                    <fullName>US Commercial East SDR</fullName>
                </value>
                <value>
                    <fullName>US Commercial Unallocated</fullName>
                </value>
                <value>
                    <fullName>US Commercial West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestOpportunityUpdateTeam.cls
@isTest
private class TestOpportunityUpdateTeam {

    static testMethod void myUnitTest() {
        
        User AE = [select Id, Name from User where UserRole.Name like '%Account Executive%' and isActive = true limit 1];
        
        Account acct2 = new Account(Name = 'Test2', OwnerId = AE.Id );
        insert acct2;
        
        Opportunity opp = new Opportunity(Name = 'TestOpp', AccountId = acct2.id, OwnerId = AE.Id, Type = 'New', StageName = 'Identify', CloseDate = Date.today().addDays(30), Owner_Team__c = 'Virtual Empire', Amount = 55000);
        insert opp;
        
        User newOppOwner = [select id, Name, Team__c from User where UserRole.Name like '%Account Executive%' and isActive = true and id !=: AE.id limit 1];
        
        opp.OwnerId = newOppOwner.Id;
        update opp;
        
        
        Opportunity testOpp = [select id, Owner_Team__c from Opportunity where id =: opp.id];
        system.assert(testOpp.Owner_Team__c == newOppOwner.Team__c);
    }
}