src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_Marketing_Interaction__c</fullName>
        <description>Set by BatchUpdateAccountBizibleTouchCounts</description>
        <label>Last Marketing Interaction</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MQI_Last_30_Days__c</fullName>
        <description>Marketing Qualified Interactions in Last 30 Days. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Last 30 Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MQI_Last_60_Days__c</fullName>
        <description>Marketing Qualified Interactions in Last 60 Days. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Last 60 Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MQI_Last_90_Days__c</fullName>
        <description>Marketing Qualified Interactions in Last 90 Days. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Last 90 Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MQI_Total__c</fullName>
        <description>Total number of Marketing Qualified Interactions in the account. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Total)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SchedBatchUpdateAccountBizibleTouches.cls
global class SchedBatchUpdateAccountBizibleTouches implements Schedulable {
	
    global void execute(SchedulableContext sc) {
    	BatchUpdateAccountBizibleTouchCounts b = new BatchUpdateAccountBizibleTouchCounts();
	   	b.query = 'SELECT id, Name, Last_Marketing_Interaction__c, MQI_Last_30_Days__c, MQI_Last_60_Days__c, MQI_Last_90_Days__c, MQI_Total__c FROM Account';
	   	
	   	ID batchprocessid = Database.executeBatch(b, 10);
    }
    
}