src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Demo_Count__c</fullName>
        <label>Demo Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Evaluation_Meeting_Count__c</fullName>
        <label>Evaluation Meeting Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Demo_Date__c</fullName>
        <label>First Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Evaluation_Meeting_Date__c</fullName>
        <label>First Evaluation Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Green_Circle_Registration_Date__c</fullName>
        <description>Date this company joined the Green Circle</description>
        <label>Green Circle Last Activity Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Demo_Count__c</fullName>
        <label>Demo Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Demo_Date__c</fullName>
        <label>First Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Green_Circle_Registration_Date__c</fullName>
        <label>Green Circle Last Activity Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <inlineHelpText>Date when the deal should show up on financial statements (for accounting purposes).  This field is for Finance use only.</inlineHelpText>
        <label>Close Date (Finance)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Count of Contact Roles attached to the opportunity</description>
        <label>Number of Key Stakeholders Engaged</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Demo_Count__c</fullName>
        <label>Demo Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Evaluation_Meeting_Count__c</fullName>
        <label>Evaluation Meeting Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Demo_Contact_Safe_ID__c</fullName>
        <label>First Demo Contact Safe ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Demo_Date__c</fullName>
        <label>First Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Evaluation_Meeting_Date__c</fullName>
        <label>First Evaluation Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hypervisors_Relevant_for_This_Opp__c</fullName>
        <label>Hypervisors Relevant for This Opp</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VMware</fullName>
                </value>
                <value>
                    <fullName>Hyper-V (Microsoft)</fullName>
                </value>
                <value>
                    <fullName>Xen (Open Source)</fullName>
                </value>
                <value>
                    <fullName>Xen (Citrix)</fullName>
                </value>
                <value>
                    <fullName>KVM (Openstack)</fullName>
                </value>
                <value>
                    <fullName>KVM (Redhat)</fullName>
                </value>
                <value>
                    <fullName>OracleVM</fullName>
                </value>
                <value>
                    <fullName>Heterogeneous</fullName>
                </value>
                <value>
                    <fullName>Acropolis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Executive_Visit__c</fullName>
        <label>Last Executive Touch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_SE_Follow_Ups__c</fullName>
        <label>Total # SE Follow-Ups</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_CPU_Sockets__c</fullName>
        <description>The number of CPU Sockets (or processors) in the contact&apos;s environment. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</description>
        <inlineHelpText>The number of CPU Sockets (or processors) related to this opportunity. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</inlineHelpText>
        <label># of CPU Sockets [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Virtual_Machines__c</fullName>
        <description>Number of Virtual Machines related to this opportunity.</description>
        <inlineHelpText>Number of Virtual Machines related to this opportunity.</inlineHelpText>
        <label># of Virtual Machines [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBatchCountOppContactRoles.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBatchCountOppContactRoles {

    static testMethod void myUnitTest() {
    /*	
   		List<Opportunity> oppInsert = new List<Opportunity>();
    	List<Contact> conInsert = new List<Contact>();
    	List<OpportunityContactRole> oppCRInsert = new List<OpportunityContactRole>();
    	List<Task> tskInsert = new List<Task>();
    	
    	//Create Account
        Account acct1 = new Account(Name = 'Acct1');
        insert acct1;
        
        //Create Contacts
    	Contact con1 = new Contact(FirstName = 'Contact', LastName = 'One', AccountId = acct1.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con1);
    	Contact con2 = new Contact(FirstName = 'Contact', LastName = 'Two', AccountId = acct1.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con2);
    	Contact con3 = new Contact(FirstName = 'Contact', LastName = 'Three', AccountId = acct1.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con3);
    	Contact con4 = new Contact(FirstName = 'Contact', LastName = 'Four', AccountId = acct1.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con4);
    	Contact con5 = new Contact(FirstName = 'Contact', LastName = 'Five', AccountId = acct1.id, Green_Circle_Registration_Date__c = Date.today() );
    	conInsert.add(con5);
    	
    	insert conInsert;
    	
    	//Create Opportunities
        Opportunity opp1 = new Opportunity(Name = 'Opp1', CloseDate = Date.today(), type = 'New', Booking_Date__c = Date.today(), StageName = 'Closed Won', AccountId = acct1.id, Hypervisors_Relevant_for_This_Opp__c = 'KVM (Redhat);OracleVM', of_CPU_Sockets__c = 100, of_Virtual_Machines__c = 1000);
        oppInsert.add(opp1);
        Opportunity opp2 = new Opportunity(Name = 'Opp2', CloseDate = Date.today(), type = 'New', Booking_Date__c = Date.today(), StageName = 'Identify', AccountId = acct1.id, Demo_Count__c = 2, First_Demo_Date__c = date.today(), Last_Executive_Visit__c = date.today(), Hypervisors_Relevant_for_This_Opp__c = 'VMware', of_CPU_Sockets__c = 100, of_Virtual_Machines__c = 1000);
        oppInsert.add(opp2);
        Opportunity opp3 = new Opportunity(Name = 'Opp3', CloseDate = Date.today(), type = 'New', Booking_Date__c = Date.today(), StageName = 'Pipeline', AccountId = acct1.id, Evaluation_Meeting_Count__c = 2, First_Evaluation_Meeting_Date__c = date.today(), Total_SE_Follow_Ups__c = 2, of_CPU_Sockets__c = 100, of_Virtual_Machines__c = 1000);
		oppInsert.add(opp3);
		
		insert oppInsert;
		
		//Create Opportunity Contact Roles
		OpportunityContactRole oppCR1 = new OpportunityContactRole(ContactId = con1.id, OpportunityId = opp1.id, Role = 'Manager', IsPrimary = true);
		oppCRInsert.add(oppCR1);
		OpportunityContactRole oppCR2 = new OpportunityContactRole(ContactId = con2.id, OpportunityId = opp1.id, Role = 'Decision Maker');
		oppCRInsert.add(oppCR2);
		OpportunityContactRole oppCR3 = new OpportunityContactRole(ContactId = con3.id, OpportunityId = opp1.id, Role = 'Influencer');
		oppCRInsert.add(oppCR3);
		OpportunityContactRole oppCR4 = new OpportunityContactRole(ContactId = con4.id, OpportunityId = opp1.id, Role = 'Non-Responsive');
		oppCRInsert.add(oppCR4);
		OpportunityContactRole oppCR5 = new OpportunityContactRole(ContactId = con5.id, OpportunityId = opp2.id, Role = 'VMT Champion', IsPrimary = true);
		oppCRInsert.add(oppCR5);
		
		insert oppCRInsert;
		
		//Create Demo Tasks
		Task tsk1 = new Task(Status='Not Started', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today().addDays(-10), WhatId=opp1.id, WhoId = Con1.id, CPU_Sockets__c = 10, Virtual_Machines_VMs__c = 100, First_Demo_Scheduled__c = true, First_Demo__c = false);
        tskInsert.add(tsk1);
        Task tsk2 = new Task(Status='Not Started', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today().addDays(-5), WhatId=opp2.id, WhoId = con2.id, CPU_Sockets__c = 20, Virtual_Machines_VMs__c = 150, First_Demo_Scheduled__c = true);
        tskInsert.add(tsk2);
        Task tsk3 = new Task(Status='Completed', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today(), WhatId=opp2.id, WhoId = con3.id, CPU_Sockets__c = 20, Virtual_Machines_VMs__c = 150);
        tskInsert.add(tsk3);
        Task tsk4 = new Task(Status='Completed', Type = 'Demo', Subject ='Demo', ActivityDate=Date.Today(), WhatId=opp3.id, CPU_Sockets__c = 20, Virtual_Machines_VMs__c = 150);
        tskInsert.add(tsk4);
        
        insert tskInsert;
		
		
		
		Test.StartTest();
		BatchCountOppContactRoles n = new BatchCountOppContactRoles();
		n.query = 'SELECT id, Contact_Role_Count__c, Name, Type, First_Demo_Contact_Safe_Id__c FROM Opportunity WHERE id = \'' + opp1.id + '\' OR id = \'' + opp2.id + '\' OR id = \'' + opp3.id + '\'';
		ID batchprocessid = Database.executeBatch(n);
		Test.StopTest();
		
		List<Opportunity> getOpps = [SELECT id, Contact_Role_Count__c, First_Demo_Contact_Safe_Id__c FROM Opportunity WHERE id =: opp1.id  OR id =: opp2.id OR id =: opp3.id];
		
		for (Opportunity opp : getOpps) {
			if (opp.id == opp1.id) {
				system.assertEquals(opp.Contact_Role_Count__c,4);
				system.assertEquals(opp.First_Demo_Contact_Safe_Id__c,con1.id);
				
			}
			else if (opp.id == opp2.id) {
				system.assertEquals(opp.Contact_Role_Count__c,1);
				system.assertEquals(opp.First_Demo_Contact_Safe_Id__c,con2.id);
			}
			else if (opp.id == opp3.id) {
				system.assertEquals(opp.Contact_Role_Count__c,0);
				system.assertEquals(opp.First_Demo_Contact_Safe_Id__c,null);
			}
			
		}
        */
    }
}