src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry_clean__c</fullName>
        <formula>IF(Industry_clean_1__c&lt;&gt;&quot;Other&quot;,Industry_clean_1__c,
IF(Industry_clean_2__c&lt;&gt;&quot;Other&quot;,Industry_clean_2__c,
IF(Industry_clean_3__c&lt;&gt;&quot;Other&quot;,Industry_clean_3__c,
IF(Industry_clean_4__c&lt;&gt;&quot;Other&quot;,Industry_clean_4__c,
&quot;Other&quot;))))</formula>
        <inlineHelpText>See industry help text above.</inlineHelpText>
        <label>Industry (clean)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_clean_text__c</fullName>
        <label>Industry (clean - text)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IndustrySetter.cls
/** 
* Created by: Eustace Consulting [www.eustaceconsulting.com][Developer: Jennifer Blair] 
* Description: Class that holds asynchronous methods that set Industry text field on Account based
*  on formula field that relies on a workflow rule.
*/
public class IndustrySetter {
	
	@future
	public static void setIndustryOnAcct (Set<Id> acctIds) {
		List<Account> acctList = [select id, Industry_clean__c, Industry_clean_text__c from Account where id in: acctIds];
		List<Account> updateList = new List<Account>();
		
		for (Account acct: acctList) {
			if (acct.Industry_clean_text__c != acct.Industry_clean__c) {
				system.debug('@@@IndustrySetter.cls: Industry mismatch!');
				system.debug('@@@IndustrySetter.cls: Industry_clean__c = ' + acct.Industry_clean__c);
				system.debug('@@@IndustrySetter.cls: Industry_clean_text__c = ' + acct.Industry_clean_text__c);
				acct.Industry_clean_text__c = acct.Industry_clean__c;
				updateList.add(acct);
			}
		}
		
		if (updateList.size() > 0) update updateList;	
	}

}