src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AR12_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AR12 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AR6_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AR6 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>A_and_B_Graded_Sales_Partners__c</fullName>
        <defaultValue>0</defaultValue>
        <label>A and B Graded Sales Partners</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>A_and_B_Graded_Tech_Partners__c</fullName>
        <defaultValue>0</defaultValue>
        <label>A and B Graded Tech Partners</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active_Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>system to track active partners with registrations within the last year</description>
        <label>Active Partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_Registrations_Last_12_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved Registrations (Last 12 Months)</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Registrations_Last_6_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved Registrations (Last 6 Months)</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Registration_Date__c</fullName>
        <label>First Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Graded_Partners_C_and_Above__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Graded Partners C and Above</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IP12_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IP12 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IP6_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IP6 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IR12_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IR12 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IR6_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IR6 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incremental_Bookings_Last_12_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Incremental Bookings (Last 12 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incremental_Bookings_Last_6_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Incremental Bookings (Last 6 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incremental_Pipe_Adds_Last_12_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Incremental Pipe Adds (Last 12 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incremental_Pipe_Adds_Last_6_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Incremental Pipe Adds (Last 6 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Registration_Date__c</fullName>
        <label>Last Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NAC_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NAC Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NAS_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NAS Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NAT_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NAT Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NGPC_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NGPC Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NMA_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NMA Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NPO_Score__c</fullName>
        <label>NPO Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_ACE_Certified_Contacts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of ACE Certified Contacts</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Booked_Registrations__c</fullName>
        <label>Number of Booked Registrations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Mapped_Sales_Accounts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Mapped Sales Accounts</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Partner_Offices__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Partner Offices</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Registrations__c</fullName>
        <label>Number of Registrations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Registered_Bookings_Last_12_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Registered Bookings (Last 12 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Registered_Bookings_Last_6_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Registered Bookings (Last 6 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Registered_Pipe_Adds_Last_12_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Registered Pipe Adds (Last 12 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Registered_Pipe_Adds_Last_6_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Registered Pipe Adds (Last 6 Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TP12_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TP12 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TP6_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TP6 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR12_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TR12 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR6_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TR6 Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SchedBatchUpdatePartnerInfo.cls
global class SchedBatchUpdatePartnerInfo implements schedulable{
	
	global void execute(SchedulableContext sc) {
		BatchUpdatePartnerInfo b = new BatchUpdatePartnerInfo();
		b.query = 'SELECT ID, Name, AR12_Score__c, AR6_Score__c, IP12_Score__c, IP6_Score__c, TP12_Score__c, TP6_Score__c, IR12_Score__c, IR6_Score__c, TR12_Score__c, ' +
					'TR6_Score__c, NGPC_Score__c, NAS_Score__c, NAT_Score__c, NPO_Score__c, NMA_Score__c, NAC_Score__c, Graded_Partners_C_and_Above__c, A_and_B_Graded_Sales_Partners__c,' +
					'A_and_B_Graded_Tech_Partners__c, Number_of_ACE_Certified_Contacts__c, number_of_mapped_sales_accounts__c, Number_Of_Partner_Offices__c, registered_bookings_last_12_months__c, ' +
					'registered_bookings_last_6_months__c, incremental_bookings_last_12_months__c, incremental_bookings_last_6_months__c, registered_pipe_adds_last_12_months__c, ' +
					'registered_pipe_adds_last_6_months__c, incremental_pipe_adds_last_12_months__c, incremental_pipe_adds_last_6_months__c, approved_registrations_last_12_months__c, ' + 
					'approved_registrations_last_6_months__c, Active_Partner__c, first_registration_date__c, last_registration_date__c, number_of_registrations__c, number_of_booked_registrations__c ' + 
 					'from Account where recordTypeId = \'012D0000000kbiU\' and id != \'001D000000ev464IAA\'';					
		ID batchprocessid = Database.executeBatch(b, 10);
	}
	
}