src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_Marketing_Interaction__c</fullName>
        <description>Set by BatchUpdateAccountBizibleTouchCounts</description>
        <label>Last Marketing Interaction</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MQI_Last_30_Days__c</fullName>
        <description>Marketing Qualified Interactions in Last 30 Days. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Last 30 Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MQI_Last_60_Days__c</fullName>
        <description>Marketing Qualified Interactions in Last 60 Days. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Last 60 Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MQI_Last_90_Days__c</fullName>
        <description>Marketing Qualified Interactions in Last 90 Days. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Last 90 Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MQI_Total__c</fullName>
        <description>Total number of Marketing Qualified Interactions in the account. 

Determined by associated Bizible Touchpoints. Updated by Trigger and corrected weekly by BatchUpdateAccountBizibleTouchCounts.</description>
        <label>MQI (Total)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bizible2__Bizible_Person__c.object
<CustomObject>
    <fields>
        <fullName>bizible2__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Bizible_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bizible2__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Bizible_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bizible Person</label>
    <nameField>
        <label>Person Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bizible Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/bizible2__Bizible_Touchpoint__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bizible Touchpoints</relationshipLabel>
        <relationshipName>Bizible_Touchpoints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bizible2__Bizible_Person__c</fullName>
        <label>Person Id</label>
        <referenceTo>bizible2__Bizible_Person__c</referenceTo>
        <relationshipLabel>Bizible Touchpoint</relationshipLabel>
        <relationshipName>Bizible_Touchpoints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>bizible2__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bizible Touchpoint</relationshipLabel>
        <relationshipName>Bizible_Touchpoints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bizible2__Touchpoint_Date__c</fullName>
        <description>The date that the session activity occurred</description>
        <inlineHelpText>The date that the session activity occurred</inlineHelpText>
        <label>Touchpoint Date</label>
        <type>DateTime</type>
    </fields>
    <label>Bizible Touchpoint</label>
    <nameField>
        <label>Bizible Touchpoint</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bizible Touchpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestBizibleTouchPointsTrigger.cls
/**
 *Test Class for BizibleTouchPointTrigger
 * Case 1: Account with counts to increment
 * Case 2: Account with null counts
 * Case 3: Mixed null and counts to increment. Last Marketing Interaction field not updated
 *
 */
@isTest
private class TestBizibleTouchPointsTrigger {

    static testMethod void myUnitTest() {
       List<Account> insertAccts = new List<Account>();
       
       DateTime currTime = system.now();
        
       Account acct1 = new Account(name = 'acct1', MQI_Last_30_Days__c = 5, MQI_Last_60_Days__c = 5, MQI_Last_90_Days__c = 2, MQI_Total__c = 10);
       Account acct2 = new Account(name = 'acct2');
       Account acct3 = new Account(name = 'acct3', MQI_Last_30_Days__c = 0, MQI_Total__c = 3, Last_Marketing_Interaction__c = currTime);
       
       insertAccts.add(acct1); insertAccts.add(acct2); insertAccts.add(acct3);
        
       insert insertAccts;
        
       List<Contact> insertContacts = new List<Contact>();
       Contact con1 = new Contact(FirstName = 'Contact', LastName = 'One', AccountId = acct1.id);
       Contact con2 = new Contact(FirstName = 'Contact', LastName = 'Two', AccountId = acct2.id);
        
       insertContacts.add(con1); insertContacts.add(con2);
       insert insertContacts;
        
       List<Lead> insertLeads = new List<Lead>();
       Lead ld1 = new Lead(Account__c = acct3.id, FirstName = 'Lead', LastName = 'One', Company = 'Acct3', LeadSource = 'Inbound - website', Status = 'Suspect');
       Lead ld2 = new Lead(Account__c = acct1.id, FirstName = 'Lead', LastName = 'Two', Company = 'Acct1', LeadSource = 'Inbound - website', Status = 'Suspect');
        
       insertLeads.add(ld1); insertLeads.add(ld2);
       insert insertLeads;
        
       List<bizible2__Bizible_Person__c> insertPersons = new List<bizible2__Bizible_Person__c>();
        
       bizible2__Bizible_Person__c person1 = new bizible2__Bizible_Person__c(bizible2__Contact__c = con1.id);
       bizible2__Bizible_Person__c person2 = new bizible2__Bizible_Person__c(bizible2__Contact__c = con2.id);
       bizible2__Bizible_Person__c person3 = new bizible2__Bizible_Person__c(bizible2__Lead__c = ld1.id);
       bizible2__Bizible_Person__c person4 = new bizible2__Bizible_Person__c(bizible2__Lead__c = ld2.id);
       
       insertPersons.add(person1); insertPersons.add(person2); insertPersons.add(person3); insertPersons.add(person4);
       
       insert insertPersons;
       
       List<bizible2__Bizible_Touchpoint__c> insertMQI = new List<bizible2__Bizible_Touchpoint__c>();
       
       bizible2__Bizible_Touchpoint__c tp1 = new bizible2__Bizible_Touchpoint__c(bizible2__Contact__c = con1.id, bizible2__Bizible_Person__c = person1.id, bizible2__Touchpoint_Date__c = currTime);
       bizible2__Bizible_Touchpoint__c tp2 = new bizible2__Bizible_Touchpoint__c(bizible2__Contact__c = con1.id,bizible2__Bizible_Person__c = person1.id, bizible2__Touchpoint_Date__c = system.now().addDays(-40));
       bizible2__Bizible_Touchpoint__c tp3 = new bizible2__Bizible_Touchpoint__c(bizible2__Contact__c = con1.id,bizible2__Bizible_Person__c = person1.id, bizible2__Touchpoint_Date__c = system.now().addDays(-80));
       bizible2__Bizible_Touchpoint__c tp4 = new bizible2__Bizible_Touchpoint__c(bizible2__Contact__c = con1.id, bizible2__Bizible_Person__c = person1.id, bizible2__Touchpoint_Date__c = system.now().addDays(-120));
       
       bizible2__Bizible_Touchpoint__c tp5 = new bizible2__Bizible_Touchpoint__c(bizible2__Contact__c = con2.id, bizible2__Bizible_Person__c = person2.id, bizible2__Touchpoint_Date__c = system.now().addDays(-40));
       bizible2__Bizible_Touchpoint__c tp6 = new bizible2__Bizible_Touchpoint__c(bizible2__Contact__c = con2.id,bizible2__Bizible_Person__c = person2.id, bizible2__Touchpoint_Date__c = system.now().addDays(-70));
       
       
       bizible2__Bizible_Touchpoint__c tp7 = new bizible2__Bizible_Touchpoint__c(bizible2__Bizible_Person__c = person3.id,bizible2__Touchpoint_Date__c = currTime.addDays(-70));
       
       insertMQI.add(tp1); insertMQI.add(tp2); insertMQI.add(tp3); insertMQI.add(tp4); insertMQI.add(tp5);
       insertMQI.add(tp6); insertMQI.add(tp7);
       
       insert insertMQI;
       
       Map<id, Account> acctQuery = new Map<id, Account>([SELECT id, Last_Marketing_Interaction__c, MQI_Last_30_Days__c, MQI_Last_60_Days__c, MQI_Last_90_Days__c, MQI_Total__c FROM Account WHERE id =: acct1.id or id =: acct2.id or id =: acct3.id]);
       
       for (Account a: acctQuery.values()) {
       		if (a.id == acct1.id) {
       			system.assertEquals(a.MQI_Last_30_Days__c,6);
       			system.assertEquals(a.MQI_Last_60_Days__c,7);	
       			system.assertEquals(a.MQI_Last_90_Days__c,5);	
       			system.assertEquals(a.MQI_Total__c,14);
       			system.assertEquals(a.Last_Marketing_Interaction__c,tp1.bizible2__Touchpoint_Date__c);			
       		} else if (a.id == acct2.id) {
       			system.assertEquals(a.MQI_Last_30_Days__c,null);
       			system.assertEquals(a.MQI_Last_60_Days__c,1);	
       			system.assertEquals(a.MQI_Last_90_Days__c,2);	
       			system.assertEquals(a.MQI_Total__c,2);
       			system.assertEquals(a.Last_Marketing_Interaction__c,tp5.bizible2__Touchpoint_Date__c);			
        	} else if (a.id == acct3.id) {
       			system.assertEquals(a.MQI_Last_30_Days__c,0);
       			system.assertEquals(a.MQI_Last_60_Days__c,null);	
       			system.assertEquals(a.MQI_Last_90_Days__c,1);	
       			system.assertEquals(a.MQI_Total__c,4);
       			system.assertEquals(a.Last_Marketing_Interaction__c,currTime);			
       		}
        }
        
    }
}