src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Core_Count__c</fullName>
        <label>Core Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dial_Count__c</fullName>
        <label>Dial Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hardware_Vendor__c</fullName>
        <label>Hardware Vendor</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arista</fullName>
                </value>
                <value>
                    <fullName>Cisco</fullName>
                </value>
                <value>
                    <fullName>HP</fullName>
                </value>
                <value>
                    <fullName>Dell</fullName>
                </value>
                <value>
                    <fullName>IBM</fullName>
                </value>
                <value>
                    <fullName>Nutanix</fullName>
                </value>
                <value>
                    <fullName>Oracle/Sun</fullName>
                </value>
                <value>
                    <fullName>SimpliVity</fullName>
                </value>
                <value>
                    <fullName>Other (Specify)</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hypervisor_Vendor__c</fullName>
        <label>Hypervisor Vendor</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VMware</fullName>
                </value>
                <value>
                    <fullName>Hyper-V (Microsoft)</fullName>
                </value>
                <value>
                    <fullName>Xen (Open Source)</fullName>
                </value>
                <value>
                    <fullName>Xen (Citrix)</fullName>
                </value>
                <value>
                    <fullName>KVM (Openstack)</fullName>
                </value>
                <value>
                    <fullName>KVM (Redhat)</fullName>
                </value>
                <value>
                    <fullName>OracleVM</fullName>
                </value>
                <value>
                    <fullName>Heterogeneous</fullName>
                </value>
                <value>
                    <fullName>IBM PowerVM</fullName>
                </value>
                <value>
                    <fullName>Acropolis</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Other (Specify)</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Core_Count_Update_Date__c</fullName>
        <label>Last Core Count Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Dial_Date__c</fullName>
        <label>Last Dial Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Socket_Count__c</fullName>
        <label>Socket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Storage_Vendor__c</fullName>
        <label>Storage Vendor</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlantis</fullName>
                </value>
                <value>
                    <fullName>DataGravity</fullName>
                </value>
                <value>
                    <fullName>Dell Compellent</fullName>
                </value>
                <value>
                    <fullName>Dell MD Series  (NetApp OEM)</fullName>
                </value>
                <value>
                    <fullName>EMC (Other)</fullName>
                </value>
                <value>
                    <fullName>EMC (VMAX)</fullName>
                </value>
                <value>
                    <fullName>EMC (VNX)</fullName>
                </value>
                <value>
                    <fullName>EMC (VNX-F)</fullName>
                </value>
                <value>
                    <fullName>EMC (XtremIO)</fullName>
                </value>
                <value>
                    <fullName>Hitachi</fullName>
                </value>
                <value>
                    <fullName>HP (3PAR)</fullName>
                </value>
                <value>
                    <fullName>HP (Other)</fullName>
                </value>
                <value>
                    <fullName>IBM</fullName>
                </value>
                <value>
                    <fullName>IBM N Series  (NetApp OEM)</fullName>
                </value>
                <value>
                    <fullName>NetApp</fullName>
                </value>
                <value>
                    <fullName>Nimble Storage</fullName>
                </value>
                <value>
                    <fullName>Nutanix</fullName>
                </value>
                <value>
                    <fullName>Oracle</fullName>
                </value>
                <value>
                    <fullName>Other (Specify)</fullName>
                </value>
                <value>
                    <fullName>Pure Storage</fullName>
                </value>
                <value>
                    <fullName>SolidFire</fullName>
                </value>
                <value>
                    <fullName>Tegile</fullName>
                </value>
                <value>
                    <fullName>Tintri</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Violin Memory</fullName>
                </value>
                <value>
                    <fullName>XtremIO</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Concierge_Routing_Reason__c</fullName>
        <label>Concierge Routing Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Downloaded 30 Day</fullName>
                </value>
                <value>
                    <fullName>Downloaded Ops Man Lite</fullName>
                </value>
                <value>
                    <fullName>Downloaded VHM</fullName>
                </value>
                <value>
                    <fullName>Requested Capacity Planner</fullName>
                </value>
                <value>
                    <fullName>Requested Contact</fullName>
                </value>
                <value>
                    <fullName>Requested Demo</fullName>
                </value>
                <value>
                    <fullName>Requested Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Core_Count__c</fullName>
        <label>Core Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dial_Count__c</fullName>
        <label>Dial Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Dial_Date__c</fullName>
        <label>Last Dial Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Socket_Count__c</fullName>
        <label>Socket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Concierge_Routing_Reason__c</fullName>
        <label>Concierge Routing Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Downloaded 30 Day</fullName>
                </value>
                <value>
                    <fullName>Downloaded Ops Man Lite</fullName>
                </value>
                <value>
                    <fullName>Downloaded VHM</fullName>
                </value>
                <value>
                    <fullName>Requested Capacity Planner</fullName>
                </value>
                <value>
                    <fullName>Requested Contact</fullName>
                </value>
                <value>
                    <fullName>Requested Demo</fullName>
                </value>
                <value>
                    <fullName>Requested Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dial_Count_Since_Last_Status_Change__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dial Count Since Last Status Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dial_Count__c</fullName>
        <label>Dial Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Dial_Date__c</fullName>
        <label>Last Dial Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Change_Date__c</fullName>
        <defaultValue>DATE(1900,1,1)</defaultValue>
        <label>Status Change Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testTaskAfterInsertUpdate.cls
/* 
* Created by: Eustace Consulting [www.eustaceconsulting.com][Developer: Jennifer Blair] 
* Description: test class for TaskAfterInsertUpdate.trigger
*
*/
@isTest
private class testTaskAfterInsertUpdate {

    static testMethod void testDialComplete() {
        List<Task> tskList = new List<Task>();
    	
    	//Create Account
        Account acct1 = new Account(Name = 'Innitech');
        insert acct1;
        
        //Create Lead
        Lead lead1 = new Lead(Account__c = acct1.id, FirstName = 'Bob', LastName = 'Jones', Company = 'Innitech', LeadSource = 'Unknown', Status_Change_Date__c = Date.today().addDays(-15), Concierge_Routing_Reason__c = 'VHM Download');
        insert lead1;
        Lead lead2 = new Lead(Account__c = acct1.id, FirstName = 'Chris', LastName = 'Johnson', Company = 'Innitech', LeadSource = 'Unknown', Status_Change_Date__c = Date.today().addDays(-15), Concierge_Routing_Reason__c = 'VHM Download', Dial_Count_Since_Last_Status_Change__c = 2);
		insert lead2;
        //Create completed Task under Lead
        Task tsk1 = new Task(Status='Completed', Subject ='Call', Call_Disposition__c = 'Connect', ActivityDate=Date.Today().addDays(-10), WhoId=lead1.id);
        insert tsk1;
        Task tsk2 = new Task(Status='Completed', Subject ='Call', ActivityDate=Date.Today().addDays(-10), WhoId=lead2.id);
        tskList.add(tsk2);
        Task tsk3 = new Task(Status='Completed', Subject ='Call', ActivityDate=Date.Today().addDays(-12), WhoId=lead2.id);
        tskList.add(tsk3);
        insert tskList;
		
        
        //Verify fields on Lead & Account were updated
        acct1 = [select Dial_Count__c, Last_Dial_Date__c from Account where id =: acct1.id];
        lead1 = [select Dial_Count__c, Last_Dial_Date__c, Dial_Count_Since_Last_Status_Change__c, Concierge_Routing_Reason__c from Lead where id =: lead1.id];
        lead2 = [select Dial_Count_Since_Last_Status_Change__c, Concierge_Routing_Reason__c from Lead where id =: lead2.id];
        system.assert(acct1.Dial_Count__c ==3);
        system.assert(acct1.Last_Dial_Date__c == Date.today().addDays(-10));
        system.assert(lead1.Dial_Count__c ==1);
        system.assert(lead1.Last_Dial_Date__c == Date.today().addDays(-10));
        system.assertEquals(lead1.Dial_Count_Since_Last_Status_Change__c, 1);
        system.assertEquals(lead2.Dial_Count_Since_Last_Status_Change__c, 4);
        system.assert(lead1.Concierge_Routing_Reason__c == null);
        system.assert(lead2.Concierge_Routing_Reason__c == 'VHM Download');
        
        //Create Contact
        Contact con1 = new Contact(FirstName = 'Jane', LastName = 'Doe', AccountId = acct1.id, Concierge_Routing_Reason__c = 'Trial Download');
        insert con1;
        
        //Create completed Task under Lead
        Task tsk4 = new Task(Status='Completed', Subject ='Call', Call_Disposition__c = 'Connect', ActivityDate=Date.Today(), WhoId=con1.id);
        insert tsk4;
        
        //verify fields on Contact & Account were updated
        acct1 = [select Dial_Count__c, Last_Dial_Date__c from Account where id =: acct1.id];
        con1 = [select Dial_Count__c, Last_Dial_Date__c, Concierge_Routing_Reason__c from Contact where id =: con1.id];
        system.assert(acct1.Dial_Count__c ==4);
        system.assert(acct1.Last_Dial_Date__c == Date.today());
        system.assert(con1.Dial_Count__c ==1);
        system.assert(con1.Last_Dial_Date__c == Date.today());
        system.assert(con1.Concierge_Routing_Reason__c == null);
    }
    
    static testMethod void testTechTaskComplete() {
    	
        //Create Account
        Account acct1 = new Account(Name = 'Innitech');
        insert acct1;
        
        //Create Lead
        Lead lead1 = new Lead(Account__c = acct1.id, FirstName = 'Bob', LastName = 'Jones', Company = 'Innitech', LeadSource = 'Unknown');
        insert lead1;
        
        //Create completed Task under Lead
        Task tsk1 = new Task(Status='Completed', Type = 'Call', Call_Disposition__c = 'Connect', Subject ='Call', ActivityDate=Date.Today().addDays(-10), WhoId=lead1.id, 
          CPU_Sockets__c=10, Virtual_Machines_VMs__c=100, Cores__c = 80, Hardware_Vendor__c='Cisco', Hypervisor_Vendor__c='VMware', Storage_Vendor__c='NetApp');
        insert tsk1;
        
        //Verify fields on Account were updated
        acct1 = [select Socket_Count__c, VM_Count__c, Core_Count__c, Last_Core_Count_Update_Date__c, Hardware_Vendor__c, Hypervisor_Vendor__c, Storage_Vendor__c from Account where id =: acct1.id];
        system.assertEquals(acct1.Socket_Count__c,10);
        system.assertEquals(acct1.VM_Count__c,100);
        system.assertEquals(acct1.Core_Count__c,80);
        system.assertEquals(acct1.Last_Core_Count_Update_Date__c,date.today().addDays(-10));
        system.assertEquals(acct1.Hardware_Vendor__c,'Cisco');
        system.assertEquals(acct1.Hypervisor_Vendor__c,'VMware');
        system.assertEquals(acct1.Storage_Vendor__c,'NetApp');
        
        //Create Contact
        Contact con1 = new Contact(FirstName = 'Jane', LastName = 'Doe', AccountId = acct1.id);
        insert con1;
        
        //Create completed Task under Lead
        Task tsk2 = new Task(Status='Completed', Subject ='Call', ActivityDate=Date.Today(), WhoId=con1.id, 
          CPU_Sockets__c=30, Virtual_Machines_VMs__c=250, Cores__c = 240, Hardware_Vendor__c='Cisco;HP', Hypervisor_Vendor__c='VMware;Hyper-V (Microsoft)', Storage_Vendor__c='NetApp;EMC (VNX)');
       insert tsk2;
       //insert new List<Task>{tsk1,tsk2}; 
        
        //verify fields on Contact & Account were updated
        acct1 = [select Socket_Count__c, VM_Count__c, Core_count__c, Last_Core_Count_Update_Date__c, Hardware_Vendor__c, Hypervisor_Vendor__c, Storage_Vendor__c from Account where id =: acct1.id];
        system.assertEquals(acct1.Socket_Count__c,30);
        system.assertEquals(acct1.Core_Count__c, 240);
        system.assertEquals(acct1.Last_Core_Count_update_date__c,date.today());
        system.assertEquals(acct1.VM_Count__c,250);
        system.assertEquals(acct1.Hardware_Vendor__c,'Cisco;HP');
        system.assertEquals(acct1.Hypervisor_Vendor__c,'VMware;Hyper-V (Microsoft)');
        system.assertEquals(acct1.Storage_Vendor__c,'NetApp;EMC (VNX)');
    }
}