src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Core_Count__c</fullName>
        <label>Core Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socket_Count__c</fullName>
        <label>Socket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Core_Count__c</fullName>
        <label>Core Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Demo_Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The rep the demo should be assigned to</inlineHelpText>
        <label>Demo Assigned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Account Executive</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Demo_Date__c</fullName>
        <inlineHelpText>Demo Scheduled date for this contact</inlineHelpText>
        <label>Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Demo_Notes__c</fullName>
        <label>Demo Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Host_Count__c</fullName>
        <label>Host Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Open Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Engineer_for_Demo__c</fullName>
        <label>Sales Engineer for Demo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alec Kemp</fullName>
                </value>
                <value>
                    <fullName>Allen Patterson</fullName>
                </value>
                <value>
                    <fullName>Anson McCook</fullName>
                </value>
                <value>
                    <fullName>Aseem Anwar</fullName>
                </value>
                <value>
                    <fullName>Barry Howard</fullName>
                </value>
                <value>
                    <fullName>Brad Blodgett</fullName>
                </value>
                <value>
                    <fullName>Charles Russell</fullName>
                </value>
                <value>
                    <fullName>Chris Rauch</fullName>
                </value>
                <value>
                    <fullName>Chris Williamson</fullName>
                </value>
                <value>
                    <fullName>Daniel Butzer</fullName>
                </value>
                <value>
                    <fullName>Don McKeith</fullName>
                </value>
                <value>
                    <fullName>Eric Horsman</fullName>
                </value>
                <value>
                    <fullName>Hillel Adler</fullName>
                </value>
                <value>
                    <fullName>Iddo Avneri</fullName>
                </value>
                <value>
                    <fullName>Jacob Ben-David</fullName>
                </value>
                <value>
                    <fullName>James Dyckowski</fullName>
                </value>
                <value>
                    <fullName>Jamie Hodge</fullName>
                </value>
                <value>
                    <fullName>Jason Beaudette</fullName>
                </value>
                <value>
                    <fullName>Jason Howard</fullName>
                </value>
                <value>
                    <fullName>Jason Huff</fullName>
                </value>
                <value>
                    <fullName>Jeremy Levenson</fullName>
                </value>
                <value>
                    <fullName>Jerome Papazian</fullName>
                </value>
                <value>
                    <fullName>Jimmy Herbert</fullName>
                </value>
                <value>
                    <fullName>Joe Burke</fullName>
                </value>
                <value>
                    <fullName>Juan Santos</fullName>
                </value>
                <value>
                    <fullName>Jules Albin</fullName>
                </value>
                <value>
                    <fullName>Kent Nierendorf</fullName>
                </value>
                <value>
                    <fullName>Kevin Lamb</fullName>
                </value>
                <value>
                    <fullName>Luis DaSilva</fullName>
                </value>
                <value>
                    <fullName>Masa Kawano</fullName>
                </value>
                <value>
                    <fullName>Bosheng Song</fullName>
                    <isActive>false</isActive>
                    <label>Bosheng Song</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Demo__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check box if a demo has been scheduled with this contact</inlineHelpText>
        <label>Scheduled Demo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Socket_Count__c</fullName>
        <label>Socket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Open_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Open Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>WI Partner - dedup</description>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Auto_Number__c.object
<CustomObject>
    <label>Lead Auto Number</label>
    <nameField>
        <label>Lead Auto Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_Revenue_Type__c</fullName>
        <inlineHelpText>This field is to help with revenue forecasting.  If you don’t know for sure which item to choose, use your best guess based on discussions with the customer.</inlineHelpText>
        <label>Expected Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Perm with 1-2 Years Maintenance</fullName>
                </value>
                <value>
                    <fullName>Perm with 2+ Years Maintenance</fullName>
                </value>
                <value>
                    <fullName>Perm Combined with Term License Items</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
                <value>
                    <fullName>Training/Services Only</fullName>
                </value>
                <value>
                    <fullName>Maintenance Only</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_CPU_Sockets__c</fullName>
        <description>The number of CPU Sockets (or processors) in the contact&apos;s environment. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</description>
        <inlineHelpText>The number of CPU Sockets (or processors) related to this opportunity. As a standard, each physical server will likely have 2 or 4 sockets, however newer boxes have as many as 8 or 16 sockets.</inlineHelpText>
        <label># of CPU Sockets [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Virtual_Machines__c</fullName>
        <description>Number of Virtual Machines related to this opportunity.</description>
        <inlineHelpText>Number of Virtual Machines related to this opportunity.</inlineHelpText>
        <label># of Virtual Machines [R]</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testTaskSetOpenFlagOnLeadContact.cls
// Created by: Eustace Consulting [www.eustaceconsulting.com][Developer: Jennifer Blair]
// Tests: TaskSetOpenFlagOnLeadContact.trigger      
@isTest
private class testTaskSetOpenFlagOnLeadContact {

    static testMethod void myUnitTest() {
    	
    	//Lead_Auto_Number__c lan = new Lead_Auto_Number__c();
        //insert lan;
    	
        //Create Account
        Account acct = new Account(Name = 'ABC, Co.');
        insert acct;
        
        //Create Contact
        Contact con = new Contact(FirstName = 'John', LastName = 'Doe', AccountId = acct.id);
        insert con;
        
        //con.Scheduled_Demo__c = True;
        //update con;
        
        //Create Open Task under Contact
        Task tsk1 = new Task(Subject = 'Call', Status = 'Not Started', WhoId = con.id, ActivityDate = Date.today());
        insert tsk1;
        
        //verify "Open Task" box on Contact checked
        con = [select Open_Task__c, Scheduled_Demo__c, Socket_Count__c, VM_Count__c, Host_Count__c,Demo_Date__c,Demo_Notes__c,Related_Opportunity__c, Sales_Engineer_for_Demo__c from Contact where id =: con.id];
        
		
        //close Task
        tsk1 = [select Status from Task where id =: tsk1.id];
        tsk1.Status = 'Completed';
        update tsk1;
        
        //verify "Open Task" box on Contact unchecked
        con = [select Open_Task__c from Contact where id =: con.id];
        system.assert(con.Open_Task__c == false);
        
        //Create Open Task under Contact
        Task tsk4 = new Task(Subject = 'Call', Status = 'Not Started', WhoId = con.id, ActivityDate = Date.today());
        insert tsk4;
        
        //verify "Open Task" box on Contact checked
        con = [select Open_Task__c from Contact where id =: con.id];
        system.assert(con.Open_Task__c == true);
        
        //delete Task
        delete tsk4;
        
        //verify "Open Task" box on Lead unchecked
        con = [select Open_Task__c from Contact where id =: con.id];
        system.assert(con.Open_Task__c == false);
    }
        
    static testMethod void myUnitTest2() {
        //Create Lead
        Lead ld = new Lead(FirstName = 'Jane', LastName = 'Doe', Company = 'Acme', LeadSource = 'Unknown');
        insert ld;
        
        //Create Open Task under Lead
        Task tsk2 = new Task(Subject = 'Call', Status = 'Not Started', WhoId = ld.id, ActivityDate = Date.today());
        insert tsk2;
        
        //verify "Open Task" box on Lead checked
        ld = [select Open_Task__c from Lead where id =: ld.id];
        system.assert(ld.Open_Task__c == true);
        
        //close Task
        tsk2 = [select Status from Task where id =: tsk2.id];
        tsk2.Status = 'Completed';
        update tsk2;
        
        //verify "Open Task" box on Lead unchecked
        ld = [select Open_Task__c from Lead where id =: ld.id];
        system.assert(ld.Open_Task__c == false);
        
        //Create Open Task under Lead
        Task tsk3 = new Task(Subject = 'Call', Status = 'Not Started', WhoId = ld.id, ActivityDate = Date.today());
        insert tsk3;
        
        //verify "Open Task" box on Lead checked
        ld = [select Open_Task__c from Lead where id =: ld.id];
        system.assert(ld.Open_Task__c == true);
        
        //delete Task
        delete tsk3;
        
        //verify "Open Task" box on Lead unchecked
        ld = [select Open_Task__c from Lead where id =: ld.id];
        system.assert(ld.Open_Task__c == false);
    }
    
    static testMethod void myUnitTest3() {
    	
    	 //Create Account
        Account acct = new Account(Name = 'ABC, Co.');
        insert acct;
    	
    	 //Create Opportunity
        Opportunity opp = new Opportunity(Type='New',amount=100000,closedate=date.Today().addDays(30),stageName='Identify',name='opp1',accountId=acct.Id,leadsource='Prospecting-Other',Expected_Revenue_Type__c='Term',of_Virtual_Machines__c=800,of_CPU_Sockets__c=80);
		insert opp;
    	
    	
    	Contact con = new Contact(FirstName = 'John', LastName = 'Doe', AccountId = acct.id, Scheduled_Demo__c = True, Demo_Assigned_To__c = '005D0000005sEzl', VM_Count__c = 120, Socket_Count__c = 12, Host_Count__c = 6, Core_Count__c = 30, Demo_Date__c = date.Today().addDays(20), Demo_Notes__c = 'This is a test Demo5', Sales_Engineer_for_Demo__c = 'Bosheng Song', Related_Opportunity__c = opp.Id);
        insert con;
        
        //con.Scheduled_Demo__c = True;
        //update con;
    	
    	con = [select Open_Task__c, Scheduled_Demo__c, Socket_Count__c, VM_Count__c, Host_Count__c,Demo_Date__c,Demo_Notes__c,Related_Opportunity__c, Sales_Engineer_for_Demo__c from Contact where id =: con.id];
        system.assert(con.Open_Task__c == true);
        system.assertEquals(False, con.Scheduled_Demo__c);
		system.assertEquals(null,con.Socket_Count__c);
		system.assertEquals(null,con.VM_Count__c);
		system.assertEquals(null,con.Host_Count__c);
		system.assertEquals(null,con.Demo_Date__c);
		system.assertEquals(null,con.Demo_Notes__c);
		system.assertEquals(null,con.Related_Opportunity__c);
		system.assertEquals(null,con.Sales_Engineer_for_Demo__c);
    	
    }
    
}