src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>To identify the type of licenses that the account has</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Perm</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
                <value>
                    <fullName>Perm &amp; Term</fullName>
                </value>
                <value>
                    <fullName>CWOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>RIGHT(Status_Ordered__c,LEN(Status_Ordered__c)-4)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Host_Count__c</fullName>
        <label>Host Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PhoneHome_Data_Last_Refreshed__c</fullName>
        <label>PhoneHome Data Last Refreshed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PhoneHome_License_Type__c</fullName>
        <label>PhoneHome License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Freemium</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>30-Day Trial</fullName>
                </value>
                <value>
                    <fullName>VHM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhoneHome_Number_of_Hosts__c</fullName>
        <label>PhoneHome Number of Hosts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PhoneHome_Number_of_VMs__c</fullName>
        <label>PhoneHome Number of VMs</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PhoneHome_Data_Last_Refreshed__c</fullName>
        <label>PhoneHome Data Last Refreshed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PhoneHome_License_Type__c</fullName>
        <label>PhoneHome License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Freemium</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>30-Day Trial</fullName>
                </value>
                <value>
                    <fullName>VHM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhoneHome_Number_of_Hosts__c</fullName>
        <label>PhoneHome Number of Hosts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PhoneHome_Number_of_VMs__c</fullName>
        <label>PhoneHome Number of VMs</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PhoneHome_Data__c.object
<CustomObject>
    <fields>
        <fullName>Host_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Host Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Diag_Upload_Date__c</fullName>
        <label>Last Diag Upload Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Freemium</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>30-Day Trial</fullName>
                </value>
                <value>
                    <fullName>VHM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Licensee_Email__c</fullName>
        <label>Licensee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>VM_Count__c</fullName>
        <label>VM Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PhoneHome Data</label>
    <nameField>
        <label>PhoneHome Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PhoneHome Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Turbonomic_License__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Turbonomic Licenses</relationshipLabel>
        <relationshipName>Turbonomic_Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Turbonomic Licenses</relationshipLabel>
        <relationshipName>Turbonomic_Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Creation_Use_Cases__c</fullName>
        <label>License Creation Use Cases</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>License_Use_Cases</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_End_Date__c</fullName>
        <label>License End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Key_Plain_Text__c</fullName>
        <label>License Key (Plain Text)</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Eval</fullName>
                </value>
                <value>
                    <fullName>VHM</fullName>
                </value>
                <value>
                    <fullName>Freemium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Licensee_Email__c</fullName>
        <label>Licensee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Licensee_Name__c</fullName>
        <label>Licensee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Reason__c</fullName>
        <label>Other Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Turbonomic License</label>
    <nameField>
        <label>License Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turbonomic Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/License_Use_Cases.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>License Extension (Technical Issues)</fullName>
    </customValue>
    <customValue>
        <fullName>License Extension (Sales)</fullName>
    </customValue>
    <customValue>
        <fullName>License Not Sent to Customer from Download Form</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrading VHM to Eval</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrading Feature-Set</fullName>
    </customValue>
    <customValue>
        <fullName>Downgrading to VHM</fullName>
    </customValue>
    <customValue>
        <fullName>Updating Prospect Contact Info</fullName>
    </customValue>
    <customValue>
        <fullName>Updating Socket/Core Count</fullName>
    </customValue>
    <customValue>
        <fullName>NFR License</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Use</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Form Download</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial License Creation</fullName>
    </customValue>
    <masterLabel>License Use Cases</masterLabel>
</GlobalValueSet>

src/classes/TestBatchFillPhoneHomeData.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBatchFillPhoneHomeData {

    static testMethod void myUnitTest() {
    	
    	Account acct1 = new Account(name = 'VMTurbo');
    	insert acct1;
        
        List<Lead> leadInsert = new List<Lead>();
        
        Lead l1 = new Lead(firstName = 'Test', lastName = 'One', company = 'VMTurbo', email = 'abc@vmturbo.com', leadSource = 'Inbound - VHM', account__c = acct1.id);
        leadInsert.add(l1);
        Lead l2 = new Lead(firstName = 'Test', lastName = 'Two', company = 'Some Company that Does not Exist', email = 'def@vmturbo.com', leadSource = 'Inbound - VHM');
        leadInsert.add(l2);
        
        insert leadInsert;
        
        List<PhoneHome_Data__c> phInsert = new List<PhoneHome_Data__c>();
        
        PhoneHome_Data__c ph1 = new PhoneHome_Data__c(Licensee_Email__c = 'abc@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-20), host_count__c = 20, vm_count__c = 200, license_type__c = 'VHM');
		phInsert.add(ph1);
		PhoneHome_Data__c ph2 = new PhoneHome_Data__c(Licensee_Email__c = 'abc@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-10), host_count__c = 25, vm_count__c = 250, license_type__c = 'vmt_freemium');
		phInsert.add(ph2);
		PhoneHome_Data__c ph3 = new PhoneHome_Data__c(Licensee_Email__c = 'abc@vmturbo.com', Last_Diag_Upload_Date__c = date.today(), host_count__c = 50, vm_count__c = 500, license_type__c = 'VHM');
		phInsert.add(ph3);
		PhoneHome_Data__c ph4 = new PhoneHome_Data__c(Licensee_Email__c = 'def@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-20), host_count__c = 20, vm_count__c = 200, license_type__c = 'VHM');
		phInsert.add(ph4);        
        PhoneHome_Data__c ph5 = new PhoneHome_Data__c(Licensee_Email__c = 'def@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-18), host_count__c = 21, vm_count__c = 195, license_type__c = '30-Day Trial');
		phInsert.add(ph5); 
		
		insert phInsert;
		
		List<Turbonomic_License__c> tlInsert = new List<Turbonomic_License__c>();
		
		Turbonomic_License__c tl1 = new Turbonomic_License__c(Licensee_Email__c = 'abc@vmturbo.com', licensee_name__c = 'Test One', License_Type__c = 'Eval', License_end_date__c = date.today().addDays(-5), status__c = 'Open', license_creation_use_Cases__c = 'Other', other_reason__c = 'I dunno', license_key_plain_text__c = 'blah');
		tlInsert.add(tl1);
		Turbonomic_License__c tl2 = new Turbonomic_License__c(Licensee_Email__c = 'def@vmturbo.com', licensee_name__c = 'Test Two', License_Type__c = 'Eval', License_end_date__c = date.today().addDays(-5), status__c = 'Open', license_creation_use_cases__c = 'Other', other_reason__c = 'I dunno', license_key_plain_text__c = 'blah');
		tlInsert.add(tl2);
		
		insert tlInsert;
		
		Test.startTest();
		BatchFillPhoneHomeData b = new BatchFillPhoneHomeData();
		b.query = 'SELECT id, account__c, email, phoneHome_Data_Last_Refreshed__c, phoneHome_Number_of_Hosts__c, phoneHome_Number_of_VMs__c, phoneHome_License_Type__c from Lead where id = \'' + l1.id + '\' or id = \'' + l2.id + '\'';
		ID batchprocessid = Database.executeBatch(b);
		Test.stopTest();
		
		List<Lead> leadResults = [select id, phoneHome_Data_Last_Refreshed__c, phoneHome_Number_of_Hosts__c, phoneHome_Number_of_VMs__c, phoneHome_License_Type__c from Lead where id =: l1.id or id =: l2.id];
		List<Turbonomic_License__c> tlResults = [select id, account__c, lead__c, status__c from Turbonomic_License__c where id =: tl1.id or id =: tl2.id];
		
		for (Lead l : leadResults){
			if (l.id == l1.id) {
				system.assertEquals(l.phoneHome_Data_Last_Refreshed__c,date.today());
				system.assertEquals(l.phoneHome_Number_of_Hosts__c,50);
				system.assertEquals(l.phoneHome_Number_of_VMs__c,500);
				system.assertEquals(l.phoneHome_License_Type__c,'VHM');
			} else if (l.id == l2.id) {
				system.assertEquals(l.phoneHome_Data_Last_Refreshed__c,date.today().addDays(-18));
				system.assertEquals(l.phoneHome_Number_of_Hosts__c,21);
				system.assertEquals(l.phoneHome_Number_of_VMs__c,195);
				system.assertEquals(l.phoneHome_License_Type__c,'30-Day Trial');
			}
		}
		
		for (Turbonomic_License__c tl : tlResults) {
			if (tl.id == tl1.id) {
				system.assertEquals(tl.account__c,acct1.id);
				system.assertEquals(tl.lead__c,l1.id);
				system.assertEquals(tl.status__c,'Expired');
			} else {
				system.assertEquals(tl.account__c,null);
				system.assertEquals(tl.lead__c,l2.id);
				system.assertEquals(tl.status__c,'Expired');
			}
		}
		
    }
    
    
    static testMethod void myUnitTest2() {
    	
    	Account acct1 = new Account(name = 'VMTurbo');
    	insert acct1;
    	
    	List<Contact> leadInsert = new List<Contact>();
        
        Contact l1 = new Contact(firstName = 'Test', lastName = 'One', email = 'abc@vmturbo.com', leadSource = 'Inbound - VHM', accountId = acct1.id);
        leadInsert.add(l1);
        Contact l2 = new Contact(firstName = 'Test', lastName = 'Two', email = 'def@vmturbo.com', leadSource = 'Inbound - VHM');
        leadInsert.add(l2);
        
        insert leadInsert;
        
        List<PhoneHome_Data__c> phInsert = new List<PhoneHome_Data__c>();
        
        PhoneHome_Data__c ph1 = new PhoneHome_Data__c(Licensee_Email__c = 'abc@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-20), host_count__c = 20, vm_count__c = 200, license_type__c = 'VHM');
		phInsert.add(ph1);
		PhoneHome_Data__c ph2 = new PhoneHome_Data__c(Licensee_Email__c = 'abc@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-10), host_count__c = 25, vm_count__c = 250, license_type__c = 'vmt_freemium');
		phInsert.add(ph2);
		PhoneHome_Data__c ph3 = new PhoneHome_Data__c(Licensee_Email__c = 'abc@vmturbo.com', Last_Diag_Upload_Date__c = date.today(), host_count__c = 50, vm_count__c = 500, license_type__c = 'VHM');
		phInsert.add(ph3);
		PhoneHome_Data__c ph4 = new PhoneHome_Data__c(Licensee_Email__c = 'def@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-20), host_count__c = 20, vm_count__c = 200, license_type__c = 'VHM');
		phInsert.add(ph4);        
        PhoneHome_Data__c ph5 = new PhoneHome_Data__c(Licensee_Email__c = 'def@vmturbo.com', Last_Diag_Upload_Date__c = date.today().addDays(-18), host_count__c = 21, vm_count__c = 195, license_type__c = '30-Day Trial');
		phInsert.add(ph5); 
		
		insert phInsert;
		
		List<Turbonomic_License__c> tlInsert = new List<Turbonomic_License__c>();
		
		Turbonomic_License__c tl1 = new Turbonomic_License__c(Licensee_Email__c = 'abc@vmturbo.com', licensee_name__c = 'Test One', License_Type__c = 'Eval', License_end_date__c = date.today().addDays(-5), status__c = 'Open', license_creation_use_Cases__c = 'Other', other_reason__c = 'I dunno', license_key_plain_text__c = 'blah');
		tlInsert.add(tl1);
		Turbonomic_License__c tl2 = new Turbonomic_License__c(Licensee_Email__c = 'def@vmturbo.com', licensee_name__c = 'Test Two', License_Type__c = 'Eval', License_end_date__c = date.today().addDays(-5), status__c = 'Open', license_creation_use_cases__c = 'Other', other_reason__c = 'I dunno', license_key_plain_text__c = 'blah');
		tlInsert.add(tl2);
		
		insert tlInsert;
		
		Test.startTest();
		BatchFillPhoneHomeDataCon b = new BatchFillPhoneHomeDataCon();
		b.query = 'SELECT id, accountId, email, phoneHome_Data_Last_Refreshed__c, phoneHome_Number_of_Hosts__c, phoneHome_Number_of_VMs__c, phoneHome_License_Type__c from Contact where id = \'' + l1.id + '\' or id = \'' + l2.id + '\'';
		ID batchprocessid = Database.executeBatch(b);
		Test.stopTest();
		
		List<Contact> leadResults = [select id, phoneHome_Data_Last_Refreshed__c, phoneHome_Number_of_Hosts__c, phoneHome_Number_of_VMs__c, phoneHome_License_Type__c from Contact where id =: l1.id or id =: l2.id];
		List<Turbonomic_License__c> tlResults = [select id, Account__c, status__c from Turbonomic_License__c where id =: tl1.id or id =: tl2.id];
		
		
		for (Contact l : leadResults){
			if (l.id == l1.id) {
				system.assertEquals(l.phoneHome_Data_Last_Refreshed__c,date.today());
				system.assertEquals(l.phoneHome_Number_of_Hosts__c,50);
				system.assertEquals(l.phoneHome_Number_of_VMs__c,500);
				system.assertEquals(l.phoneHome_License_Type__c,'VHM');
			} else if (l.id == l2.id) {
				system.assertEquals(l.phoneHome_Data_Last_Refreshed__c,date.today().addDays(-18));
				system.assertEquals(l.phoneHome_Number_of_Hosts__c,21);
				system.assertEquals(l.phoneHome_Number_of_VMs__c,195);
				system.assertEquals(l.phoneHome_License_Type__c,'30-Day Trial');
			}
		}
		
		for (Turbonomic_License__c tl : tlResults) {
			if (tl.id == tl1.id) {
				system.assertEquals(tl.account__c, acct1.id);
				system.assertEquals(tl.status__c, 'Expired');
			} else {
				system.assertEquals(tl.account__c, null);
				system.assertEquals(tl.status__c, 'Expired');
			}
		}
    	
    	
    	
    }
}