src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Original Velocity/Enterprise Account type</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Lookup</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Active Contacts</relationshipLabel>
        <relationshipName>Active_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <inlineHelpText>Use these status to remove contacts from your contact view when appropriate</inlineHelpText>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Suspect</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Call_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Do Not Call Lookup</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Do Not Call Contacts</relationshipLabel>
        <relationshipName>Do_Not_Call</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inactive Lookup</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inactive Contacts</relationshipLabel>
        <relationshipName>Inactive_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inbound_SLA_Core_Market__c</fullName>
        <description>For use in filtering Core Market contacts for Inbound SLAs (CampaignMemberCreateSLA.trigger)</description>
        <formula>IF(ISBLANK(Account.Name),
CASE(UPPER(MailingCountry), 
&quot;UNITED KINGDOM&quot;,&quot;EMEA&quot;, 
&quot;SPAIN&quot;, &quot;EMEA&quot;, 
&quot;PORTUGAL&quot;, &quot;EMEA&quot;, 
&quot;FRANCE&quot;, &quot;EMEA&quot;, 
&quot;ICELAND&quot;,&quot;EMEA&quot;, 
&quot;GREAT BRITAIN&quot;,&quot;EMEA&quot;, 
&quot;GERMANY&quot;,&quot;EMEA&quot;, 
&quot;BELGIUM&quot;,&quot;EMEA&quot;, 
&quot;EUROPE&quot;,&quot;EMEA&quot;, 
&quot;POLAND&quot;,&quot;EMEA&quot;, 
&quot;THE NETHERLANDS&quot;,&quot;EMEA&quot;, 
&quot;NETHERLANDS&quot;,&quot;EMEA&quot;, 
&quot;NEDERLANDS&quot;,&quot;EMEA&quot;, 
&quot;LUXEMBOURG&quot;,&quot;EMEA&quot;, 
&quot;SWITZERLAND&quot;,&quot;EMEA&quot;, 
&quot;AUSTRIA&quot;,&quot;EMEA&quot;, 
&quot;IRELAND&quot;,&quot;EMEA&quot;, 
&quot;ITALY&quot;,&quot;EMEA&quot;, 
&quot;DENMARK&quot;,&quot;EMEA&quot;, 
&quot;FINLAND&quot;,&quot;EMEA&quot;, 
&quot;SWEDEN&quot;,&quot;EMEA&quot;, 
&quot;NORWAY&quot;,&quot;EMEA&quot;, 
&quot;POLAND&quot;,&quot;EMEA&quot;, 
&quot;SOUTH AFRICA&quot;,&quot;EMEA&quot;, 
&quot;ISRAEL&quot;,&quot;EMEA&quot;, 
&quot;SCOTLAND&quot;,&quot;EMEA&quot;, 
&quot;UNITED STATES&quot;,&quot;NORAM&quot;, 
&quot;CANADA&quot;,&quot;NORAM&quot;, 
&quot;N/A&quot;), 
IF(CONTAINS(&quot;EMEA&quot;, Account.Territory_Owner_Team__c),&quot;EMEA&quot;,&quot;NORAM&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inbound SLA Core Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Contact_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Do Not Call</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Environment under 8 hosts</fullName>
                </value>
                <value>
                    <fullName>Existing open opportunity</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer at Company</fullName>
                </value>
                <value>
                    <fullName>Not a Stakeholder</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Recently Closed/Unqualified Opportunity</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact - Bad Data</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact - Language Barrier</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact - Non Responsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <description>Automated formula to check if Contact matches our Active criteria. Will be used in conjunction with a Contact Trigger Method to set the Active Contact Lookup to the Account</description>
        <formula>OR(
Active_Contact_Manual__c = True,
AND( 
OR( 
NOT(ISPICKVAL(Contact_Status__c,&quot;Closed&quot;)), 
AND( 
ISPICKVAL(Contact_Status__c,&quot;Closed&quot;), 
OR(ISPICKVAL(Status_Reason__c,&quot;Unable to Contact - Non Responsive&quot;),ISPICKVAL(Status_Reason__c,&quot;Recently Closed/Unqualified Opportunity&quot;),ISPICKVAL(Status_Reason__c,&quot;Existing Open opportunity&quot;)) 
) 
), 
OR( 
Opened_Marketo_Email_in_Last_Year__c, 
Last_Engagement_Date__c &gt;=TODAY() - 365,
DATEVALUE(CreatedDate) &gt;= TODAY()-365 
) 
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLA__c.object
<CustomObject>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SLAs</relationshipLabel>
        <relationshipName>SLAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA_1_Met__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLA 1 Met</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLA_Status__c</fullName>
        <label>SLA Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed (New SLA Came In)</fullName>
                </value>
                <value>
                    <fullName>Closed (Expired)</fullName>
                </value>
                <value>
                    <fullName>Closed (Demo Scheduled)</fullName>
                </value>
                <value>
                    <fullName>Closed (SLA Met)</fullName>
                </value>
                <value>
                    <fullName>Closed (Manually Dispositioned)</fullName>
                </value>
                <value>
                    <fullName>Closed (Meeting Set)</fullName>
                </value>
                <value>
                    <fullName>Closed (Lead Dispositioned)</fullName>
                </value>
                <value>
                    <fullName>Closed (Contact Dispositioned)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Zone_Offset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>GMT_Offset__c</fullName>
        <label>GMT Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Time Zone Offset</label>
</CustomObject>

src/classes/ContactMethods.cls
global class ContactMethods {
 
 /*	
*	Index	Method Name									Method Description
*	-------------------------------------------------------------------------------------------------------------------------
*	[C1]	ContactDispositionSlaMet					mark open sla met if contact dispositioned within 24 hours
*	[C2]    setContactLookups							Set the Active Contact Lookup to Account for active Contacts
*
*
*
*
*/


 	/*
 	*  [C1]
 	*  ContactDispositionSlaMet method
	*
	*
	*/ 
	public static void ContactDispositionSlaMet(Map<id,Contact> contacts, Map<id,Contact> oldContacts) {
	
		Set<id> closedContacts = new Set<id>(); //Set to hold dispostioned contacts
		Map<id,Integer> conGmtOffsetMap = new Map<id, Integer>(); //Map to hold Time Zone Offset for Contacts
		
		Integer emeaOffset; Integer usOffset;
		Map<String, Time_Zone_Offset__c> gmtOffSetMap = Time_Zone_Offset__c.getall();
		// 0 during winter, 1 during British Summer Time
		if (gmtOffSetMap.containsKey('EMEA')) emeaOffset = (Integer) gmtOffSetMap.get('EMEA').GMT_Offset__c; else emeaOffset = 1;
		//-5 during EST, -4 during EDT
    	if (gmtOffSetMap.containsKey('EMEA')) usOffset = (Integer) gmtOffSetMap.get('NORAM').GMT_Offset__c; else usOffset = -4;
		
		for (Contact con : contacts.values()) {
			//if the Contact is dispositioned within 24 hours of SLA creation mark SLA 1 as met
			if (con.Contact_Status__c == 'Closed' && oldContacts.get(con.id).Contact_Status__c != 'Closed') {
				closedContacts.add(con.id);
				if (con.Inbound_SLA_Core_Market__c == 'NORAM') conGmtOffsetMap.put(con.id,usOffset);
				else conGmtOffsetMap.put(con.id,emeaOffset);
			}
		}
		
		//Query all open SLAs associated with the converted and closed Leads
		if (closedContacts.size() > 0) {
			Map<id, SLA__C> slaMap = new Map<id, SLA__c>([SELECT id, Contact__c, SLA_1_Met__c, CreatedDate FROM SLA__c WHERE SLA_Status__c = 'Open' AND (Contact__c in: closedContacts)]);	
			List<SLA__c> updateSLA = new List<SLA__c>();
			
			DateTime currTime = System.now();
			for (SLA__c s: slaMap.values()) {
				boolean updated = false;
				
				Integer offSet = 0; //default Time Zone offset to zero
				if (conGmtOffsetMap.containsKey(s.Contact__c)) offSet = conGmtOffsetMap.get(s.Contact__c); //If an offset was set during initial loop, grab offset 
				DateTime dateToCompare = SLAMethods.AdjustedSLATime(s.CreatedDate, offSet); //Call method to grab SLA's adjusted create time for comparison
				
				//If the disposition or the conversion is happening within 24 hours of the SLA's adjusted Create time and SLA 1 is not currently checked, mark SLA 1 as met
				if (currTime < dateToCompare.addHours(24)) {
					if (!s.SLA_1_Met__c) {
						s.SLA_1_Met__c = true;
						updated = true;
					}
				}
				
				if (closedContacts.contains(s.Contact__c)) {
					s.SLA_Status__c = 'Closed (Contact Dispositioned)';
					s.Close_Date__c = system.now();
					updated = true;
				}
				
				if (updated) updateSLA.add(s);
			}
			if (updateSLA.size() > 0) update updateSLA;		
		}
		
		
	}
	
	/*
 	*  [C2]
 	*  setContactLookups method
	*
	*
	*/ 
	public static void setContactLookups(List<Contact> contacts) {
		
		for (Contact c: contacts) {
			//Set Do not Call Look up for Contacts with Do not call checkbox is True or Status reason of "Do not call"
			if (c.DoNotCall == true || c.Status_Reason__c == 'Do Not Call') {
				system.debug('DNC Contact is: ' + c.firstName + ' ' + c.LastName);
				if (c.Inactive_Lookup__c != null) c.Inactive_Lookup__c = null; //Clear out inactive look up if not blank
				if (c.Active_Lookup__c != null) c.Active_Lookup__c = null; //Clear out Active look up if not blank
				if (c.Do_Not_Call_Lookup__c == null) c.Do_Not_Call_Lookup__c = c.AccountId;
				else if (c.Do_Not_Call_Lookup__c != c.AccountId) c.Do_Not_Call_Lookup__c = c.AccountId;
			}
			//Set Active Lookups for Active Contacts
			else if (c.IsActive__c) {
				system.debug('Active Contact is: ' + c.firstName + ' ' + c.LastName);
				if (c.Inactive_Lookup__c != null) c.Inactive_Lookup__c = null; //Clear out inactive look up if not blank
				if (c.Do_Not_Call_Lookup__c != null) c.Do_Not_Call_Lookup__c = null; //Clear out Do Not Call look up if not blank
				if (c.Active_Lookup__c == null) c.Active_Lookup__c = c.accountId; //If active look up is blank, fill with current account
				else if (c.Active_Lookup__c != c.accountId) c.Active_Lookup__c = c.accountId; //if Active lookup does not equal current account, update to current account
			}
			//Set Inactive Lookups for Inactive Contacts
			else {
				system.debug('Inctive Contact is: ' + c.firstName + ' ' + c.LastName);
				if (c.Active_Lookup__c != null) c.Active_Lookup__c = null; //Clear out Active look up if not blank
				if (c.Do_Not_Call_Lookup__c != null) c.Do_Not_Call_Lookup__c = null; //Clear out Do Not Call look up if not blank
				if (c.Inactive_Lookup__c == null) c.Inactive_Lookup__c = c.accountId; //if Inactive look up is blank fill with current account
				else if (c.Inactive_Lookup__c != c.accountId) c.Inactive_Lookup__c = c.accountId; // Else, if the inactive look up does not equal the current acocunt, update to current account
			} 
		}
		
	}
	
}