src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PhoneHome_Data_Last_Refreshed__c</fullName>
        <label>PhoneHome Data Last Refreshed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PhoneHome_License_Type__c</fullName>
        <label>PhoneHome License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Freemium</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>30-Day Trial</fullName>
                </value>
                <value>
                    <fullName>VHM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhoneHome_Number_of_Hosts__c</fullName>
        <label>PhoneHome Number of Hosts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PhoneHome_Number_of_VMs__c</fullName>
        <label>PhoneHome Number of VMs</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SchedBatchFillPhoneHomeDataCon.cls
global class SchedBatchFillPhoneHomeDataCon implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		BatchFillPhoneHomeDataCon b = new BatchFillPhoneHomeDataCon();
		b.query = 'SELECT id, email, accountId, phoneHome_Data_Last_Refreshed__c, phoneHome_Number_of_Hosts__c, phoneHome_Number_of_VMs__c, phoneHome_License_Type__c from Contact where email != null and isDeleted = false';
		
		ID batchprocessid = Database.executeBatch(b, 150);
	}
	
}