src/objects/Demo__c.object
<CustomObject>
    <label>Demo</label>
    <nameField>
        <label>Demo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meaningful Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SLA__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>SLAs</relationshipLabel>
        <relationshipName>SLAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SLAs</relationshipLabel>
        <relationshipName>SLAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Demo__c</fullName>
        <label>Demo</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>SLAs</relationshipLabel>
        <relationshipName>SLAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rapid_Response_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rapid Response Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLA_1_Met__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLA 1 Met</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLA_2_Met__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLA 2 Met</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLA_3_Met__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLA 3 Met</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLA_Connect_Count__c</fullName>
        <label>SLA Connect Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_Conversation_Count__c</fullName>
        <label>SLA Conversation Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_Dial_Count__c</fullName>
        <label>SLA Dial Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_Status__c</fullName>
        <label>SLA Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed (New SLA Came In)</fullName>
                </value>
                <value>
                    <fullName>Closed (Expired)</fullName>
                </value>
                <value>
                    <fullName>Closed (Demo Scheduled)</fullName>
                </value>
                <value>
                    <fullName>Closed (SLA Met)</fullName>
                </value>
                <value>
                    <fullName>Closed (Manually Dispositioned)</fullName>
                </value>
                <value>
                    <fullName>Closed (Meeting Set)</fullName>
                </value>
                <value>
                    <fullName>Closed (Lead Dispositioned)</fullName>
                </value>
                <value>
                    <fullName>Closed (Contact Dispositioned)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SchedBatchUpdateSLATracking.cls
global class SchedBatchUpdateSLATracking implements schedulable{
	
	global void execute(SchedulableContext sc) {
	    BatchUpdateSLATracking b = new BatchUpdateSLATracking();
	    b.query = 'SELECT id, SLA_1_Met__c, SLA_2_Met__c, SLA_3_Met__c, SLA_Status__c, Close_Date__c, Campaign__c, Contact__c, Lead__c, Expiration_Date__c, Rapid_Response_Eligible__c, CreatedDate, Demo__c, SLA_Dial_Count__c, SLA_Connect_Count__c, SLA_Conversation_Count__c FROM SLA__c WHERE CreatedDate = LAST_N_DAYS:70';
		ID batchprocessid = Database.executeBatch(b, 20);
	}
	
}