src/objects/LBI__ScoringRule__c.object
<CustomObject>
    <fields>
        <fullName>LBI__isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Lattice Scoring Rule</label>
    <nameField>
        <displayFormat>SR-{000000000}</displayFormat>
        <label>Lattice Scoring Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lattice Scoring Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SchedBatchRunLatticeModels.cls
global class SchedBatchRunLatticeModels implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		
		LBI.BatchProcessScoringForCurentRule b = new LBI.BatchProcessScoringForCurentRule('a6C57000000XdJl');
		//LBI.BatchProcessScoringForCurentRule b = new LBI.BatchProcessScoringForCurentRule();
		//b.query = 'SELECT id from LBI__ScoringRule__c where LBI__isActive__c = true';
		
		ID batchprocessid = Database.executeBatch(b, 1);
	}
    
}