src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>Personal Email Flag for use in the Lead Inbound Routing rules. If this field is set to true and the lead does not have a phone number, then the lead will be routed to a marketing user (Charles Wu) for nurturing purposes.</description>
        <formula>IF(
OR(
Contains(Email,&quot;@yahoo&quot;),
Contains(Email,&quot;@gmail&quot;),
Contains(Email,&quot;@outlook&quot;),
Contains(Email,&quot;@hotmail&quot;),
Contains(Email,&quot;@aol&quot;),
Contains(Email,&quot;@live&quot;),
Contains(Email,&quot;@msn&quot;),
Contains(Email,&quot;@me&quot;),
Contains(Email,&quot;@icloud&quot;),
Contains(Email,&quot;@mail&quot;),
Contains(Email,&quot;@ymail&quot;),
Contains(Email,&quot;@yopmail&quot;),
Contains(Email,&quot;@googlemail&quot;),
Contains(Email,&quot;@juno&quot;),
Contains(Email,&quot;@rocketmail&quot;),
Contains(Email,&quot;@earthlink&quot;),
Contains(Email,&quot;@optonline&quot;)
),
TRUE,FALSE)</formula>
        <inlineHelpText>Personal Email Flag for use in the Lead Inbound Routing rules.</inlineHelpText>
        <label>Personal Email?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retrigger_Assignment_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retrigger Assignment Rules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MyLeadReassignmentClass.cls
public class MyLeadReassignmentClass {
	
	public static boolean futureMethodAlreadyCalled = false;
	
	@future
	public static void reassignLeadWithActiveRule(Set<id> leadIds) {
		futureMethodAlreadyCalled = true;
		
		system.debug('### Entering reassign with assignment rules');
		system.debug('### leadIds has ' + leadIds.size() + ' elements');
		
		AssignmentRule ar = new AssignmentRule();
		ar = [select id from AssignmentRule where SobjectType = 'Lead' and Active = true limit 1];
		
		Database.DMLOptions dmlOpts = new Database.DMLOptions();
		dmlOpts.assignmentRuleHeader.assignmentRuleId = ar.id;
//		dmlOpts.assignmentRuleHeader.useDefaultRule = true;
		
		List<Lead> leadList = [select id, ownerId, retrigger_assignment_rules__c, email, phone, personal_email__c from Lead where id in: leadIds];
		List<Lead> updateList = new List<Lead>();
		
		for (Lead l : leadList) {
			if (l.retrigger_assignment_rules__c) {
				system.debug(l);
				l.setOptions(dmlOpts);
				l.retrigger_assignment_rules__c = false;
				updateList.add(l);
			}
		}
		
		try {
			Database.update(updateList,dmlOpts);
		}catch (DMLException e) {
			system.debug(e);
		}
	}
	
}