src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dial_Count_Since_Last_Status_Change__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dial Count Since Last Status Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dial_Count__c</fullName>
        <label>Dial Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dials_until_First_Conversation__c</fullName>
        <label># Dials until First Conversation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Connect_Date__c</fullName>
        <label>First Connect Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Conversation_Date__c</fullName>
        <label>First Conversation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Dial_Date_Time__c</fullName>
        <label>First Dial Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>First_Dial_Date__c</fullName>
        <label>First Dial Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inbound_Qualified_By__c</fullName>
        <label>Inbound Qualified By</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inbound_Qualified_Date_Stamp__c</fullName>
        <label>Inbound Qualified Date Stamp</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inbound_Qualified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inbound Qualified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Connect_Date__c</fullName>
        <label>Last Connect Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Conversation_Date__c</fullName>
        <label>Last Conversation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Dial_Date__c</fullName>
        <label>Last Dial Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Change_Date__c</fullName>
        <defaultValue>DATE(1900,1,1)</defaultValue>
        <label>Status Change Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SchedBatchUpdateTaskCallsLeads.cls
global class SchedBatchUpdateTaskCallsLeads implements Schedulable{
	
	global void execute(SchedulableContext sc) {
        BatchUpdateTaskCallsLeads b = new BatchUpdateTaskCallsLeads();
	   	b.query = 'SELECT id, name, status, first_dial_date__c, last_dial_date__c, dial_count__c, first_connect_date__c, last_Connect_Date__c, first_Conversation_Date__c, last_Conversation_Date__c, ' +
	   				'Dial_Count_since_Last_Status_Change__c, first_Dial_Date_Time__c, Status_Change_Date__c, Dials_until_First_Conversation__c,Inbound_Qualified__c, Inbound_Qualified_By__c, Inbound_Qualified_Date_Stamp__c from Lead where Account__c = NULL AND systemModStamp >= 2015-01-01T00:00:00Z AND isConverted = false';
	   	
	   	ID batchprocessid = Database.executeBatch(b, 70);
	}
	

}