src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <description>Deal type for Registrations</description>
        <inlineHelpText>Deal type for Registrations. Select &quot;Direct&quot; if this deal does not have any partner involvement.</inlineHelpText>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Deal_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
            <errorMessage>The Partner Manager needs to be in a Channel Manager role</errorMessage>
            <filterItems>
                <field>User.Team__c</field>
                <operation>equals</operation>
                <value>Xccelerators</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Channel Manager&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Director of Channels&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Luis DaSilva</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Greg Beale</value>
            </filterItems>
            <infoMessage>Filter calls for users in the Channel Manager role</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Partner_Manager__c</fullName>
        <label>Registration Partner Manager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/VartopiaDRS__Registration__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incremental</fullName>
                </value>
                <value>
                    <fullName>Joint/Accelerated</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Manager_Name__c</fullName>
        <formula>Partner_Manager__r.Full_Name__c</formula>
        <label>Partner Manager Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VartopiaDRS__Vendor_Status__c</fullName>
        <label>Vendor Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Closed-Won</fullName>
                </value>
                <value>
                    <fullName>Closed-Lost</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>Reg{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Deal_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Incremental</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated</fullName>
    </customValue>
    <customValue>
        <fullName>Fulfillment</fullName>
    </customValue>
    <customValue>
        <fullName>Cisco</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated-Revived</fullName>
        <isActive>false</isActive>
        <label>Joint/Accelerated-Revived</label>
    </customValue>
    <description>Registration Deal Type</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

src/classes/RegistrationMethods.cls
global class RegistrationMethods {
	
	public static void regFillOppInfo(List<VartopiaDRS__Registration__c> regList) {
		
		Map<id,VartopiaDRS__Registration__c> regMap = new Map<id,VartopiaDRS__Registration__c>();
		//Map<id,VartopiaDRS__Registration__c> regMap2 = new Map<id,VartopiaDRS__Registration__c>();
		Map<id,id> regToOppIds = new Map<id,id>();
		
		for (VartopiaDRS__Registration__c reg : regList) {
			regMap.put(reg.id,reg);
			if (reg.VartopiaDRS__Opportunity__c != null && reg.VartopiaDRS__Opportunity__c != '006D000000GvUcfIAF')
				regToOppIds.put(reg.id,reg.VartopiaDRS__Opportunity__c);
		}
		
		Map<id,Opportunity> oppMap = new Map<id,Opportunity>([select id, name, Registration_Partner_Manager__c, Partner_Manager__c, Deal_Type__c from Opportunity where id in: regToOppIds.values()]);
	
		List<Opportunity> updateOpps = new List<Opportunity>();
		
		for (VartopiaDRS__Registration__c reg : regMap.values()) {
			
			Opportunity opp = oppMap.get(regToOppIds.get(reg.id));
			if (opp != null) {
				Boolean updated = false;
				
				if (reg.VartopiaDRS__Vendor_Status__c == 'Submitted' || reg.VartopiaDRS__Vendor_Status__c == 'Approved' || reg.VartopiaDRS__Vendor_Status__c == 'Closed-Won') {
					if (reg.Partner_Manager_Name__c != null) {
				
						if (opp.Registration_Partner_Manager__c == null) {
							opp.Registration_Partner_Manager__c = reg.Partner_Manager_Name__c;
							updated = true;
						} else {
							if (opp.Registration_Partner_Manager__c != reg.Partner_Manager_Name__c) {
								opp.Registration_Partner_Manager__c = reg.Partner_Manager_Name__c;
								updated = true;
							}
						}
						
						if (opp.Partner_Manager__c == null) {
							opp.Partner_Manager__c = reg.Partner_Manager__c;
							updated = true;
						} else {
							if (reg.Partner_Manager__c != opp.Partner_Manager__c) {
								opp.Partner_Manager__c = reg.Partner_Manager__c;
								updated = true;
							}
						}
					}
				}
				
				if (reg.Deal_Type__c != null) {
					if (opp.Deal_Type__c == null) {
						opp.Deal_Type__c = reg.Deal_Type__c;
						updated = true;
					} else {
						if (opp.Deal_Type__c != reg.Deal_Type__c) {
							opp.Deal_Type__c = reg.Deal_Type__c;
							updated = true;
						}
					}
				}
				
				if (updated) updateOpps.add(opp);
			}
		}
		
		if (updateOpps.size() > 0) {
			Set<Opportunity> noDupeList = new Set<Opportunity>();
			List<Opportunity> finalList = new List<Opportunity>();
			noDupeList.addAll(updateOpps);
			finalList.addAll(noDupeList);
			update finalList;
		}
	}
	
}