src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_Role_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Count of Contact Roles attached to the opportunity</description>
        <label>Number of Key Stakeholders Engaged</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <description>Deal type for Registrations</description>
        <inlineHelpText>Deal type for Registrations. Select &quot;Direct&quot; if this deal does not have any partner involvement.</inlineHelpText>
        <label>Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Deal_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Demo_Contact_Safe_ID__c</fullName>
        <label>First Demo Contact Safe ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Highest_Vendor_Status__c</fullName>
        <description>Filled by batch (BatchFillHighestVendorStatus.cls)</description>
        <label>Highest Vendor Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
            <errorMessage>The Partner Manager needs to be in a Channel Manager role</errorMessage>
            <filterItems>
                <field>User.Team__c</field>
                <operation>equals</operation>
                <value>Xccelerators</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Channel Manager&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>&quot;Director of Channels&quot;</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Luis DaSilva</value>
            </filterItems>
            <filterItems>
                <field>User.Full_Name__c</field>
                <operation>equals</operation>
                <value>Greg Beale</value>
            </filterItems>
            <infoMessage>Filter calls for users in the Channel Manager role</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Deal_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Incremental</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated</fullName>
    </customValue>
    <customValue>
        <fullName>Fulfillment</fullName>
    </customValue>
    <customValue>
        <fullName>Cisco</fullName>
    </customValue>
    <customValue>
        <fullName>Joint/Accelerated-Revived</fullName>
        <isActive>false</isActive>
        <label>Joint/Accelerated-Revived</label>
    </customValue>
    <description>Registration Deal Type</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

src/classes/SchedBatchFillHighestRegStatus.cls
global class SchedBatchFillHighestRegStatus implements Schedulable {
	
	global void execute(SchedulableContext sc) {
        BatchFillHighestRegistrationStatus b = new BatchFillHighestRegistrationStatus();
     	b.query = 'SELECT Id, name, highest_vendor_status__c, partner_manager__c, Contact_Role_Count__c, Type, First_Demo_Contact_Safe_Id__c, Deal_Type__c from Opportunity where (stageName = \'Identify\' or stageName = \'Pipeline\' or stageName = \'Upside\' or stageName = \'Strong Upside\' or stageName = \'Commit\' or stageName = \'PO Received\' or stageName = \'Closed Won\')';	   	
	   	ID batchprocessid = Database.executeBatch(b, 30);

	}
	
}