src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName&amp;&quot; &quot;&amp;LastName</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>For lead score (for US reps, foreign leads show up at the top of the lead view in the morning)</description>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestBatchCreateCalls.cls
@isTest
private class TestBatchCreateCalls {

    static testMethod void myUnitTest() {
        
    	User user1 = [select id, name, location__c from User where full_name__c =: 'Brian Gramza'];
        
        Test.StartTest();
      	BatchCreateCallsForEntReps n = new BatchCreateCallsForEntReps();
      	n.query = 'SELECT id, name FROM User WHERE id = \'' + user1.id + '\'';
      	ID batchprocessid = Database.executeBatch(n);
      	Test.StopTest();
        
        List<Task> tskList = [select id, subject, activityDate from Task where (activityDate =: Date.today() and OwnerId =: user1.id)];
        system.assertEquals(tskList.size(), 30);		
    }
}