src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>IF(City_Defined__c,4,0)+ 
IF(Latitude_Longitude_Defined__c,6,0)+ 
IF(Round_Robin_Defined__c,3,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TerritoryWrapper.cls
global class TerritoryWrapper implements Comparable{
	
	public Territory__c territory;
	
	public TerritoryWrapper(Territory__c t) {
		territory = t;
	}
	
	global Integer compareTo(Object compareTo) {
		
		TerritoryWrapper compareToTerritory = (TerritoryWrapper) compareTo;
		
		Integer returnValue = 0;
		if (territory.sort_order__c < compareToTerritory.territory.sort_order__c) {
			returnValue = 1;
		} else {
			returnValue = -1;
		}
		
		return returnValue;
	}
	
	
}