src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Calculate_SF_Metrics__c</fullName>
        <description>Last modification was to add the &quot;Commercial Rep&quot; line - ccm_3/19</description>
        <formula>IF(
OR(
CONTAINS(User_Role_Name__c,&quot;Sales Development Rep&quot;),
CONTAINS(User_Role_Name__c,&quot;Business Development Rep&quot;),
CONTAINS(User_Role_Name__c,&quot;Enterprise Rep&quot;),
CONTAINS(User_Role_Name__c,&quot;Commercial Rep&quot;),
CONTAINS(User_Role_Name__c,&quot;Alliance&quot;),
CONTAINS(User_Role_Name__c,&quot;Account Executive&quot;),
CONTAINS(User_Role_Name__c,&quot;APAC&quot;),
CONTAINS(User_Role_Name__c,&quot;Inside Sales Rep&quot;)
),true,false)</formula>
        <label>Calculate SF Metrics</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName&amp;&quot; &quot;&amp;LastName</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Talent_Management_File__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Talent Management File</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trigger_Workflow_Rules__c</fullName>
        <label>Trigger Workflow Rules</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SchedBatchFillCorporateSFMetrics.cls
global class SchedBatchFillCorporateSFMetrics implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		
		BatchFillCorporateSFMetrics b = new BatchFillCorporateSFMetrics();
		b.query = 'SELECT id, full_name__c, trigger_workflow_rules__c, has_talent_management_file__c from User where isActive = true and calculate_sf_metrics__c = true';
		
		ID batchprocessid = Database.executeBatch(b, 10);
	}
}