src/objects/VartopiaDRS__Registration__c.object
<CustomObject>
    <fields>
        <fullName>VartopiaDRS__Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>Reg{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RegistrationWrapper.cls
global class RegistrationWrapper implements comparable{
	
	public VartopiaDRS__Registration__c thisReg;
	
	public RegistrationWrapper(VartopiaDRS__Registration__c reg) {
		thisReg = reg;
	}
	
	global Integer compareTO(Object compareTo) {
		
		RegistrationWrapper compareToReg = (RegistrationWrapper) compareTo;
		
		Integer returnValue = 0;
		if (thisReg.VartopiaDRS__Date_Submitted__c > compareToReg.thisReg.VartopiaDRS__Date_Submitted__c) {
			returnValue = 1;
		} else {
			returnValue = -1;
		}
		
		return returnValue;
		
	}
	
}